### ISSUE TITLE
Files duplication on paste action

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#10045]
Build:https://drone.owncloud.com/owncloud/web/40558/9/15
```
1) Scenario: Copy and move resources in personal space (attempt 2) # tests/e2e/cucumber/features/smoke/copyMove.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:43
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   ✔ And "Alice" creates the following folders in personal space using API # tests/e2e/cucumber/steps/api.ts:56
       | name                  |
       | PARENTCopy1           |
       | PARENTCopy2           |
       | PARENTMove            |
       | PARENTCopy3           |
       | PARENTCopy4/Sub1/Sub2 |
       | PARENT                |
       | PARENT/Sub1/Sub       |
       | PARENT/Sub2           |
       | PARENT/Sub3           |
       | PARENT/Sub4           |
       | PARENT/Sub5           |
   ✔ And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:101
       | pathToFile               | content                             |
       | PARENTCopy3/example1.txt | example text                        |
       | PARENTCopy3/example2.txt | example text                        |
       | KeyboardExample.txt      | copy with the help of keyboard      |
       | dragDrop.txt             | copy with the help of drag-drop     |
       | sidebar.txt              | copy with the help of sidebar panel |
       | PARENT/fileToCopy1.txt   | some content                        |
       | PARENT/fileToCopy2.txt   | some content                        |
       | PARENT/fileToCopy3.txt   | some content                        |
       | PARENT/fileToCopy4.txt   | some content                        |
       | PARENT/fileToCopy5.txt   | some content                        |
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:14
   ✔ When "Alice" copies the following resource using sidebar-panel # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource    | to          |
       | sidebar.txt | PARENTCopy2 |
   ✔ And "Alice" copies the following resource using dropdown-menu # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource                 | to          |
       | PARENTCopy3/example1.txt | PARENTCopy1 |
   ✔ And "Alice" copies the following resource using batch-action # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource                 | to          |
       | PARENTCopy3/example2.txt | PARENTCopy1 |
   ✔ And "Alice" copies the following resource using keyboard # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource            | to          |
       | KeyboardExample.txt | PARENTCopy3 |
   ✔ And "Alice" moves the following resource using drag-drop # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource     | to          |
       | dragDrop.txt | PARENTCopy2 |
   ✔ And "Alice" moves the following resource using dropdown-menu # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource                 | to         |
       | PARENTCopy1/example1.txt | PARENTMove |
   ✔ And "Alice" moves the following resource using batch-action # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource                 | to         |
       | PARENTCopy1/example2.txt | PARENTMove |
   ✔ And "Alice" moves the following resource using keyboard # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource    | to         |
       | PARENTCopy2 | PARENTMove |
   ✔ And "Alice" moves the following resource using sidebar-panel # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource    | to         |
       | PARENTCopy3 | PARENTMove |
   ✔ And "Alice" opens folder "PARENTCopy4" # tests/e2e/cucumber/steps/ui/resources.ts:302
   ✔ And "Alice" opens folder "Sub1" # tests/e2e/cucumber/steps/ui/resources.ts:302
   ✔ And "Alice" moves the following resource using drag-drop-breadcrumb # tests/e2e/cucumber/steps/ui/resources.ts:117
       | resource | to          |
       | Sub2     | PARENTCopy4 |
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:14
   ✔ And "Alice" opens folder "PARENT" # tests/e2e/cucumber/steps/ui/resources.ts:302
   ✔ And "Alice" copies the following resources to "PARENT/Sub1" at once using dropdown-menu # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub4            |
       | Sub5            |
   ✔ And "Alice" copies the following resources to "PARENT/Sub2" at once using batch-action # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub4            |
       | Sub5            |
   ✖ And "Alice" copies the following resources to "PARENT/Sub3" at once using keyboard # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub4            |
       | Sub5            |
       locator.waitFor: Error: strict mode violation: locator('#files-space-table [data-test-resource-name="fileToCopy4.txt"]') resolved to 2 elements:
           1) <span title="fileToCopy4.txt" class="oc-resource-name"…>…</span> aka getByRole('button', { name: 'fileToCopy4 .txt' }).first()
           2) <span title="fileToCopy4.txt" class="oc-resource-name"…>…</span> aka getByRole('button', { name: 'fileToCopy4 .txt' }).nth(1)

       =========================== logs ===========================
       waiting for locator('#files-space-table [data-test-resource-name="fileToCopy4.txt"]') to be visible
       ============================================================
           at /var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/utils.ts:45:79
           at waitForResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/utils.ts:45:11)
           at Object.moveOrCopyMultipleResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:785:25)
           at async Resource.copyMultipleResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:85:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:153:5)
   - And "Alice" opens folder "Sub1" # tests/e2e/cucumber/steps/ui/resources.ts:302
   - And "Alice" moves the following resources to "PARENT/Sub1/Sub" at once using dropdown-menu # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub4            |
       | Sub5            |
   - And "Alice" opens folder "Sub" # tests/e2e/cucumber/steps/ui/resources.ts:302
   - And "Alice" moves the following resources to "PARENT/Sub1" at once using batch-action # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub4            |
       | Sub5            |
   - And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:14
   - And "Alice" opens folder "PARENT" # tests/e2e/cucumber/steps/ui/resources.ts:302
   - And "Alice" moves the following resources to "Sub4" at once using drag-drop # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub1            |
       | Sub2            |
   - And "Alice" opens folder "Sub4" # tests/e2e/cucumber/steps/ui/resources.ts:302
   - And "Alice" moves the following resources to "PARENT" at once using drag-drop-breadcrumb # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub1            |
       | Sub2            |
   - And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:14
   - And "Alice" opens folder "PARENT" # tests/e2e/cucumber/steps/ui/resources.ts:302
   - And "Alice" moves the following resources to "PARENT/Sub4" at once using keyboard # tests/e2e/cucumber/steps/ui/resources.ts:139
       | resource        |
       | fileToCopy1.txt |
       | fileToCopy2.txt |
       | fileToCopy3.txt |
       | fileToCopy4.txt |
       | fileToCopy5.txt |
       | Sub1            |
       | Sub2            |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:43
   ✔ After # tests/e2e/cucumber/environment/index.ts:109
```
Trace: npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/40558/tracing/copy-and-move-resources-in-personal-space-alice-2023-11-23-04-32-56.zip

**Comment by PrajwolAmatya** [comment]
Currently after the paste action, the files are duplicated due to which we are getting this error, this occurs while running tests. 

![image](https://github.com/owncloud/web/assets/83579989/4497114b-dfa1-49b1-9f67-cf4af224284c)

cc @ScharfViktor @saw-jan

**Comment by ScharfViktor** [comment]
it's reproducible locally
Steps: 
- create files and folders
- select all, copy and move to another folder

Actual: duplicate files


https://github.com/owncloud/web/assets/84779829/f3168e7f-3e69-4429-b8bc-d0f76c0afb16

**Comment by ScharfViktor** [comment]
some strange bug. probably same problem 

https://github.com/owncloud/web/assets/84779829/8d4dc505-b32e-41f8-a48a-8ca37e7ffd8c
