### ISSUE TITLE
[Nightly] wopiserver is not properly started

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#10060]
Failing frequently in nightly CI

Builds:
https://drone.owncloud.com/owncloud/web/40613/11/10
https://drone.owncloud.com/owncloud/web/40559/11/10
https://drone.owncloud.com/owncloud/web/40558/11/10
https://drone.owncloud.com/owncloud/web/40556/11/10

wopiserver pipeline:
```console
v10.2.1: Pulling from cs3org/wopiserver
v10.2.1: Pulling from cs3org/wopiserver
Digest: sha256:8a1b1a56bb75d6d5038a95c3322db59269d46b596244e99e0b154205fd5f9036
Status: Downloaded newer image for cs3org/wopiserver:v10.2.1
+ echo 'LoremIpsum567' > /etc/wopi/wopisecret
+ cp /var/www/owncloud/web/tests/drone/wopiserver/wopiserver.conf /etc/wopi/wopiserver.conf
+ /app/wopiserver.py
{"time": "2023-11-24T01:42:10.905", "host": "9329c3849699", "level": "ERROR", "process": "wopiserver", "module": "cs3iface", "msg": "Failed to connect to Reva via GRPC", "error": ""}
{"time": "2023-11-24T01:42:10.906", "host": "9329c3849699", "level": "CRITICAL", "process": "wopiserver", "module": "wopiserver", "msg": "Failed to initialize the service, aborting", "error": ""}
Failed to initialize the service: 

Traceback (most recent call last):
  File "/app/core/cs3iface.py", line 47, in init
    grpc.channel_ready_future(ch).result(timeout=10)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/usr/local/lib/python3.11/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/wopiserver.py", line 544, in <module>
    Wopi.init()
  File "/app/wopiserver.py", line 137, in init
    storage.init(cls.config, cls.log)   # initialize the storage layer
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/cs3iface.py", line 50, in init
    raise IOError(e)
OSError
```

wait-for-wopi-server pipeline:
```console
latest: Pulling from owncloudci/wait-for
Digest: sha256:25e32539ce450fc65cb9af472b6d71f68ac62e2089fc4b0de9477cec8e7efe00
Status: Image is up to date for owncloudci/wait-for:latest
+ wait-for -it wopiserver:8880 -t 300
services aren't ready in 5m0s
```

**Comment by JammingBen** [comment]
We recently updated the wopiserver image (https://github.com/owncloud/web/pull/10001), could be related? oCIS is running `v10.1.0` AFAIK, so if nothing helps, maybe a downgrade does.

**Comment by amrita-shrestha** [comment]
@JammingBen still failing https://drone.owncloud.com/owncloud/web/40651

**Comment by JammingBen** [comment]
> @JammingBen still failing https://drone.owncloud.com/owncloud/web/40651

Yes, I haven't changed anything regarding the issue (yet) 😅 I just wanted to inform you about the version bump in the first place. However, just ping me if you want to try downgrading the wopi version, then I will do so.

**Comment by SagarGi** [comment]
I will make a PR to downground the wopi version.

**Comment by SagarGi** [comment]
Closing this since the nightly build is passing.
