### ISSUE TITLE
E2E tests failed on office suites

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/web#10351]
### Description 
Nightly build https://drone.owncloud.com/owncloud/web/41902/11/20
```
Scenario: create an OpenDocument file with Collabora # tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature:15
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
(node:21) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
    And "Alice" logs in
    And "Alice" opens the "files" app
    When "Alice" creates the following resources
      │ resource         │ type         │ content              │
      │ OpenDocument.odt │ OpenDocument │ OpenDocument Content │
    ✖ failed
      locator.isVisible: Error: strict mode violation: locator('xpath=//ul[@id="create-list"]//span[text()="OpenDocument"]') resolved to 2 elements:
          1) <span class="create-list-file-item-text">OpenDocument</span> aka getByRole('button', { name: 'OpenDocument odt' }).first()
          2) <span class="create-list-file-item-text">OpenDocument</span> aka getByRole('button', { name: 'OpenDocument odt' }).nth(1)

      =========================== logs ===========================
        checking visibility of locator('xpath=//ul[@id="create-list"]//span[text()="OpenDocument"]')
      ============================================================
          at isAppProviderServiceForOfficeSuitesReadyInWebUI (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:389:8)
          at async createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:287:44)
          at async createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:268:7)
          at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:418:3)
          at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:14:5)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:25:7)
    And "Alice" creates a public link creates a public link of following resource using the sidebar panel
      │ resource         │ role     │ password │
      │ OpenDocument.odt │ Can edit │ %public% │
    - skipped
    And "Alice" logs out
    - skipped
    And "Anonymous" opens the public link "Link"
    - skipped
    And "Anonymous" unlocks the public link with password "%public%"
    - skipped
    Then "Anonymous" should see the content "OpenDocument Content" in editor "Collabora"
    - skipped
```

**Comment by JammingBen** [comment]
Possibly related to changes in https://github.com/owncloud/web/pull/10346. @dschmidt and I can have a look since it's probably not the test's fault here.

**Comment by SagarGi** [comment]
@JammingBen sure thanks for noticing!
