### ISSUE TITLE
User other than admin cannot share resources to other users

### ISSUE THREAD

**Issue by nabim777** [owncloud/web#10712]
## Describe the bug
There is redundant resharing feature in the ocis that makes nightly builds failure. From this issue https://github.com/owncloud/web/issues/10559, we changed ocis caching behaviour on nightly. Currently, web PR builds uses specified ocis commitId and ocis branch from .drone.env file to cache ocis on nightly build. But on nightly, script file runs which update ocis commit ID of .drone.env file to latest commit id of ocis repo.

The solution for this issue is bump latest commit of ocis and remove or update step where reshare-related code is implemented.
https://drone.owncloud.com/owncloud/web/43795/10/12

```feature
Scenario: delete and restore a file inside a received shared folder (attempt 1, retried) # tests/e2e/cucumber/features/smoke/trashbinDelete.feature:45
   ✔ Before # tests/e2e/cucumber/environment/index.ts:43
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
       | Brian |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   ✔ Given "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource      | type   |
       | folderToShare | folder |
   ✔ And "Alice" uploads the following resource # tests/e2e/cucumber/steps/ui/resources.ts:35
       | resource  | to            |
       | lorem.txt | folderToShare |
   ✖ And "Alice" shares the following resource using the sidebar panel # tests/e2e/cucumber/steps/ui/shares.ts:30
       | resource      | recipient | type | role     | resourceType |
       | folderToShare | Brian     | user | Can edit | folder       |
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at Function.sendInvitation (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:110:14)
           at Function.inviteCollaborators (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:134:24)
           at async Object.createShare (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/actions.ts:80:3)
           at async Share.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/index.ts:15:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:38:7)
```

```feature
4) Scenario: delete and restore a file inside a received shared folder (attempt 1, retried) # tests/e2e/cucumber/features/smoke/trashbinDelete.feature:45
   ✔ Before # tests/e2e/cucumber/environment/index.ts:43
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
       | Brian |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   ✔ Given "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource      | type   |
       | folderToShare | folder |
   ✔ And "Alice" uploads the following resource # tests/e2e/cucumber/steps/ui/resources.ts:35
       | resource  | to            |
       | lorem.txt | folderToShare |
   ✖ And "Alice" shares the following resource using the sidebar panel # tests/e2e/cucumber/steps/ui/shares.ts:30
       | resource      | recipient | type | role     | resourceType |
       | folderToShare | Brian     | user | Can edit | folder       |
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at Function.sendInvitation (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:110:14)
           at Function.inviteCollaborators (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:134:24)
           at async Object.createShare (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/actions.ts:80:3)
           at async Share.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/index.ts:15:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:38:7)
   - And "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   - And "Brian" navigates to the shared with me page # tests/e2e/cucumber/steps/ui/shares.ts:120
   - And "Brian" opens folder "folderToShare" # tests/e2e/cucumber/steps/ui/resources.ts:365
```

**Comment by saw-jan** [comment]
Findings:

1. As admin user:
    - group share works :heavy_check_mark:
    - user share works :heavy_check_mark:
2. As Normal user:
    - group share works :heavy_check_mark:
    - user share fails with `400` :x:
:exclamation: payload is wrong :exclamation: 
```yml
POST:
https://host.docker.internal:9200/graph/v1beta1/drives/096026b0-bf97-4b86-801c-2c6775f8dc4e%244c510ada-c86b-4815-8820-42cdf82c3d51/items/096026b0-bf97-4b86-801c-2c6775f8dc4e%244c510ada-c86b-4815-8820-42cdf82c3d51!658376fe-e972-43ca-80f6-6bbb050ab391/invite

Payload:
{
  "roles": [
    "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5"
  ],
  "recipients": [
    {
      "objectId": "d6350143-b4f3-4662-a612-760411c3bfbd",
      "@libre.graph.recipient.type": "group" ❗--> should be "user"
    }
  ]
}
```

**Comment by saw-jan** [comment]
users other than admin user cannot see the mail of other users. So, the problem might be from this line:
https://github.com/owncloud/web/blob/b68ab5e0d9dc5cb7aad57b58c2bb5f6e3424f43a/packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue#L313-L315

CC @JammingBen

**Comment by SagarGi** [comment]
The nightly build seems to be passing. So this issue can be closed. https://drone.owncloud.com/owncloud/web/43831
