### ISSUE TITLE
App provider tests failing in nightly while waiting for locator

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#10857]
### Description
Test scenarios in `e2e-tests-oCIS-app-provider` are failing while waiting for locator.

Build:
- https://drone.owncloud.com/owncloud/web/44307/13/19

Failed Scenarios:
```feature
Scenario: file lock indication # tests/e2e/cucumber/features/app-provider/lock.feature:7
...
When "Brian" opens the following file in Collabora
      │ resource │
      │ test.odt │
    Then "Brian" should see the content "some content" in editor "Collabora"
No welcome modal found. Continue...
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for frameLocator('[name="app-iframe"]').locator('.leaflet-layer')
      ============================================================
          at Object.openAndGetContentOfDocument (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:404:68)
          at async Public.getContentOfOpenDocumentOrMicrosoftWordDocument (/var/www/owncloud/web/tests/e2e/support/objects/app-files/page/public.ts:96:12)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/public.ts:97:31)
```

```feature
Scenario: create an OpenDocument file with Collabora # tests/e2e/cucumber/features/app-provider/officeSuites.feature:15
Given "Admin" creates following users using API
      │ id    │
      │ Alice │
    And "Alice" logs in
    And "Alice" opens the "files" app
    When "Alice" creates the following resources
      │ resource         │ type         │ content              │
      │ OpenDocument.odt │ OpenDocument │ OpenDocument Content │
No welcome modal found. Continue...
    ✖ failed
      locator.fill: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for frameLocator('[name="app-iframe"]').locator('#clipboard-area')
      ============================================================
          at createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:348:67)
          at async createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:301:7)
          at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:457:3)
          at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:14:5)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:26:7)
```

```feature
Scenario: create a Microsoft Word file with OnlyOffice # tests/e2e/cucumber/features/app-provider/officeSuites.feature:28
Given "Admin" creates following users using API
      │ id    │
      │ Alice │
    And "Alice" logs in
    And "Alice" opens the "files" app
    When "Alice" creates the following resources
      │ resource           │ type           │ content                │
      │ MicrosoftWord.docx │ Microsoft Word │ Microsoft Word Content │
    ✖ failed
      locator.fill: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for frameLocator('[name="app-iframe"]').frameLocator('[name="frameEditor"]').locator('#area_id')
      ============================================================
          at createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:356:64)
          at async createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:306:7)
          at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:457:3)
          at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:14:5)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:26:7)
```

```feature
Scenario: open office suite files with Collabora and onlyOffice # tests/e2e/cucumber/features/app-provider/urlJourneys.feature:10
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
    And "Alice" logs in
    And "Alice" creates the following files into personal space using API
      │ pathToFile       │ content              │
      │ OpenDocument.odt │ OpenDocument Content │
    And "Alice" creates the following resources
      │ resource           │ type           │ content                │
      │ MicrosoftWord.docx │ Microsoft Word │ Microsoft Word Content │
    ✖ failed
      locator.fill: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for frameLocator('[name="app-iframe"]').frameLocator('[name="frameEditor"]').locator('#area_id')
      ============================================================
          at createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:356:64)
          at async createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:306:7)
          at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:457:3)
          at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:14:5)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:26:7)
```

**Comment by saw-jan** [comment]
Needs some extra configs
See: https://github.com/owncloud/ocis/commit/bdbba929d04bc04037987c56b4cd59cfacaf1ba3
