### ISSUE TITLE
Nightly failure on keycloak pipeline

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#10860]
### Description
E2E tests on keycloak are failing with following error:
```feature
Scenario: Alice can share this weeks meal plan with all parents # tests/e2e/cucumber/features/journeys/kindergarten.feature:21
    ✖ failed
      page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
          at Session.login (/var/www/owncloud/web/tests/e2e/support/objects/runtime/session.ts:42:18)
          at getTokenFromLogin (/var/www/owncloud/web/tests/e2e/support/utils/tokenHelper.ts:27:31)
          at async setAdminToken (/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:184:10)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:71:5)
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
      │ Brian │
      │ Carol │
    - skipped
    And "Admin" creates following group using API
      │ id       │
      │ sales    │
      │ security │
    - skipped
    And "Admin" adds user to the group using API
      │ user  │ group │
      │ Brian │ sales │
    - skipped
    When "Alice" logs in
    - skipped
```

Build:
- https://drone.owncloud.com/owncloud/web/44307/14/15

**Comment by saw-jan** [comment]
Needs changes similar to https://github.com/owncloud/ocis/commit/bdbba929d04bc04037987c56b4cd59cfacaf1ba3
