### ISSUE TITLE
[QA] Flaky e2e test

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#11028]
## Description
flaky e2e tests:
https://drone.owncloud.com/owncloud/web/45061/13/18

```feature
Scenario: create a Microsoft Word file with OnlyOffice (attempt 2) # tests/e2e/cucumber/features/app-provider/officeSuites.feature:79
   ...
   ✖ And "Alice" opens the following file in OnlyOffice # tests/e2e/cucumber/steps/ui/resources.ts:559
       | resource           |
       | MicrosoftWord.docx |
       locator.waitFor: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for frameLocator('[name="app-iframe"]').frameLocator('[name="frameEditor"]').locator('#area_id') to be visible
       ============================================================
           at Object.openFileInViewer (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:1684:69)
           at async Resource.openFileInViewer (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:235:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:566:7)
```
```feature
Scenario: space sse events (attempt 2) # tests/e2e/cucumber/features/smoke/sse.feature:32
   ...
   ✖ And "Alice" removes access to following users from the project space # tests/e2e/cucumber/steps/ui/spaces.ts:104
       | user  |
       | Brian |
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#sidebar-panel-space-share-select')
       ============================================================
           at Object.openPanel (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:70:23)
           at async openSharingPanel (/var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/actions.ts:33:3)
           at async Object.removeAccessSpaceMembers (/var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/actions.ts:244:3)
           at async Spaces.removeAccessToMember (/var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/index.ts:64:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:114:7)
```
```feature
Scenario: sse events on file operations (attempt 1, retried) # tests/e2e/cucumber/features/smoke/sse.feature:166
   ...
   ✖ When "Brian" navigates to the trashbin of the project space "marketing" # tests/e2e/cucumber/steps/ui/spaces.ts:140
       locator.waitFor: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator(':is(#files-space-table, #files-trashbin-empty)') to be visible
       ============================================================
           at Overview.navigate (/var/www/owncloud/web/tests/e2e/support/objects/app-files/page/trashbin/overview.ts:13:80)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:145:5)
```

**Comment by saw-jan** [comment]
>Scenario: space sse events (attempt 2) # tests/e2e/cucumber/features/smoke/sse.feature:32

this was fixed in https://github.com/owncloud/web/pull/11024/commits/aa7dd0c5c0f2559fcfb735c449d93f9ae60396ab
