### ISSUE TITLE
[QA] Nightly UI tests failing (master)

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#11046]
## Describe the bug
UI tests are failing mostly when setting expiration date

```
1) Scenario: share with expiration date (attempt 2) # tests/e2e/cucumber/features/shares/share.feature:181
   ✔ Before # tests/e2e/cucumber/environment/index.ts:43
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
       | Brian |
   ✔ Given "Admin" creates following group using API # tests/e2e/cucumber/steps/api.ts:39
       | id    |
       | sales |
   ✔ And "Admin" adds user to the group using API # tests/e2e/cucumber/steps/api.ts:51
       | user  | group |
       | Brian | sales |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:45
   ✔ And "Alice" creates the following folder in personal space using API # tests/e2e/cucumber/steps/api.ts:64
       | name       |
       | myfolder   |
       | mainFolder |
   ✔ And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:108
       | pathToFile           | content      |
       | new.txt              | some content |
       | mainFolder/lorem.txt | lorem epsum  |
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:15
   ✔ When "Alice" shares the following resource using the sidebar panel # tests/e2e/cucumber/steps/ui/shares.ts:37
       | resource   | recipient | type  | role     | resourceType | expirationDate |
       | new.txt    | Brian     | user  | Can edit | file         | +5 days        |
       | myfolder   | sales     | group | Can view | folder       | +10 days       |
       | mainFolder | Brian     | user  | Can edit | folder       |                |
   ✖ And "Alice" sets the expiration date of share "mainFolder" of user "Brian" to "+5 days" # tests/e2e/cucumber/steps/ui/shares.ts:287
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at Object.addExpirationDate (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/actions.ts:272:10)
           at async Share.addExpirationDate (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/index.ts:87:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:299:5)
   - And "Alice" checks the following access details of share "mainFolder" for user "Brian" # tests/e2e/cucumber/steps/ui/shares.ts:313
       | Name | Brian Murphy |
       | Type | User         |
   - And "Alice" checks the following access details of share "mainFolder/lorem.txt" for user "Brian" # tests/e2e/cucumber/steps/ui/shares.ts:313
       | Name | Brian Murphy |
       | Type | User         |
   - And "Alice" sets the expiration date of share "myfolder" of group "sales" to "+3 days" # tests/e2e/cucumber/steps/ui/shares.ts:287
   - And "Alice" checks the following access details of share "myfolder" for group "sales" # tests/e2e/cucumber/steps/ui/shares.ts:313
       | Name | sales department |
       | Type | Group            |
   - When "Alice" removes following sharee # tests/e2e/cucumber/steps/ui/shares.ts:97
       | resource | recipient | type  |
       | myfolder | sales     | group |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:58
   ✔ After # tests/e2e/cucumber/environment/index.ts:111
```

https://drone.owncloud.com/owncloud/web/45189/12/10
https://drone.owncloud.com/owncloud/web/45189/11/8
https://drone.owncloud.com/owncloud/web/45191/11/8
https://drone.owncloud.com/owncloud/web/45194/12/10

## Setup
CI

**Comment by kulmann** [comment]
This is also happening in drone runs triggered by pull requests. seems to be flaky, I saw sometimes more, sometimes less and sometimes even 0 failures related to expiration dates.

**Comment by saw-jan** [comment]
Hot fix in https://github.com/owncloud/web/pull/11051

**Comment by amrita-shrestha** [comment]
nightly build passed today so closing this issue
