### ISSUE TITLE
Unit test failing in nightly (stable-8)

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#11047]
## Describe the bug
Nightly for stable branch has been failing when running unit test
```bash
Summary of all failing tests

FAIL packages/web-pkg/tests/unit/composables/actions/files/useFileActionsCopy.spec.ts
  ● Test suite failed to run
    A jest worker process (pid=125) was terminated by another process: signal=SIGKILL, exitCode=null. Operating system logs may contain more information on why this occurred.
      at ChildProcessWorker._onExit (node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:370:23)


FAIL packages/web-app-files/tests/unit/views/FilesDrop.spec.ts
  ● Test suite failed to run
    A jest worker process (pid=132) was terminated by another process: signal=SIGKILL, exitCode=null. Operating system logs may contain more information on why this occurred.
      at ChildProcessWorker._onExit (node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/ChildProcessWorker.js:370:23)

```

Builds: 
https://drone.owncloud.com/owncloud/web/45193/7/4
https://drone.owncloud.com/owncloud/web/45190/7/4

## Setup
CI

</p>
</details>

**Comment by amrita-shrestha** [comment]
cc @micbar  @JammingBen

**Comment by kulmann** [comment]
That just happens sometimes. Was debugged in the past, with mitigation but no completely stable solution. I'd close here and only look at it if it happens multiple days in a row.

In web master we switched to vitest and made more improvements, master is running stable so far.
