### ISSUE TITLE
Flaky e2e test on pagination related scenario

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#11210]
## Description
Build: https://drone.owncloud.com/owncloud/web/45882/13/8

Failed Scenario:
```feature
Scenario: pagination (attempt 2) # tests/e2e/cucumber/features/navigation/personalSpacePagination.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:44
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:45
   ✔ And "Alice" creates 55 folders in personal space using API # tests/e2e/cucumber/steps/api.ts:74
   ✖ And "Alice" creates 55 files in personal space using API # tests/e2e/cucumber/steps/api.ts:137
       Error: expect(received).not.toBeDefined()

       Received: [Error: Unknown error]
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.44.1/node_modules/playwright/lib/matchers/expect.js:177:37)
           at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:30:31)
           at Page.emit (node:events:514:28)
           at Page.emit (node:domain:489:12)
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/browserContext.js:124:34)
           at Proxy.emit (node:events:514:28)
           at Proxy.emit (node:domain:489:12)
           at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/connection.js:202:21)
           at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
           at processImmediate (node:internal/timers:476:21)
   - And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:108
       | pathToFile           | content                |
       | .hidden-testFile.txt | This is a hidden file. |
   - And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:15
   - When "Alice" navigates to page "2" of the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:716
   - Then "Alice" should see the text "111 items with 1 kB in total (56 files including 1 hidden, 55 folders)" at the footer of the page # tests/e2e/cucumber/steps/ui/resources.ts:734
   - And "Alice" should see 10 resources in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:744
   - When "Alice" enables the option to display the hidden file # tests/e2e/cucumber/steps/ui/resources.ts:395
   - Then "Alice" should see 11 resources in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:744
   - When "Alice" changes the items per page to "500" # tests/e2e/cucumber/steps/ui/resources.ts:725
   - Then "Alice" should not see the pagination in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:754
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:58
   ✖ After # tests/e2e/cucumber/environment/index.ts:112
       Error: expect(received).not.toBeDefined()

       Received: [Error: Unknown error]
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.44.1/node_modules/playwright/lib/matchers/expect.js:177:37)
           at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:30:31)
           at Page.emit (node:events:514:28)
           at Page.emit (node:domain:489:12)
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/browserContext.js:124:34)
           at Proxy.emit (node:events:514:28)
           at Proxy.emit (node:domain:489:12)
           at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/client/connection.js:202:21)
           at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.44.1/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
           at processImmediate (node:internal/timers:476:21)
```

**Comment by JammingBen** [comment]
Roughly 80% of my CIs fail because of that test. Can we temporarily skip the test until it is resolved?

**Comment by PrajwolAmatya** [comment]
> Roughly 80% of my CIs fail because of that test. Can we temporarily skip the test until it is resolved?

Yes we can skip this test temporarily for now until resolved. :+1:

**Comment by ScharfViktor** [comment]
sometimes we have 500 error during the creating files via API
web catches it and interrupts the test.

ocis log: 
`{"level":"error","service":"ocdav","name":"com.owncloud.web.ocdav","traceid":"a4a6d84ea343a0960a90ab8934b4493d","request-id":"a5f2dd075b84/IKIyk1o97j-010951","spaceid":"eaac99b4-1710-4ebf-b7bd-23addaca23c2$75f61a46-a175-4128-86d9-5be779c6c946","path":"/testfile36.txt","status":{"code":15,"message":"stat:node.Xattr /root/.ocis/storage/users/spaces/75/f61a46-a175-4128-86d9-5be779c6c946/nodes/75/f6/1a/46/-a175-4128-86d9-5be779c6c946 user.ocis.name: no data available","trace":"a4a6d84ea343a0960a90ab8934b4493d"},"code":500,"time":"2024-07-18T10:50:19Z","message":"Internal Server Error"}`
