### ISSUE TITLE
[QA] Lists of flaky e2e tests.

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#11247]
### Description
These are the flaky tests that occurs on e2e tests. Investigate will be needed for the following tests. Please add more flaky e2e tests if found in the following list. 

- https://github.com/owncloud/web/issues/11246 (fixed test code)
- https://github.com/owncloud/ocis/issues/9648 (server side problem)
- `Scenario: public link` - `tests/e2e/cucumber/features/shares/link.feature:9`
    ```feature
    And "Anonymous" renames the following public link resources # tests/e2e/cucumber/steps/ui/public.ts:141
       | resource     | as               |
       | lorem.txt    | lorem_new.txt    |
       | textfile.txt | textfile_new.txt |
   ✖ And "Anonymous" deletes the following resources from public link using batch action # tests/e2e/cucumber/steps/ui/public.ts:200
       | resource  | from     |
       | lorem.txt | myfolder |
       | child     | myfolder |
       Error: expect(received).not.toBeDefined()

       Received: [f]
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.45.0/node_modules/playwright/lib/matchers/expect.js:194:37)
           at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:30:31)
           at Page.emit (node:events:514:28)
           at Page.emit (node:domain:489:12)
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/client/browserContext.js:127:34)
           at Proxy.emit (node:events:514:28)
           at Proxy.emit (node:domain:489:12)
           at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/client/connection.js:202:21)
           at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
           at processImmediate (node:internal/timers:476:21)
    ```

**Comment by saw-jan** [comment]
Similar flakiness tracked in https://github.com/owncloud/web/issues/11496
Closing this here
