### ISSUE TITLE
[QA] online office e2e test suite fails with latest ocis commit

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#11283]
Builds:
- https://drone.owncloud.com/owncloud/web/46117/14/14
- https://drone.owncloud.com/owncloud/web/46122/15/14

```feature
Scenario: file lock indication (attempt 2) # tests/e2e/cucumber/features/app-provider/lock.feature:8
   ✔ Before # tests/e2e/cucumber/environment/index.ts:44
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
       | Brian |
       | Carol |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:45
   ✖ When "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource | type         | content      |
       | test.odt | OpenDocument | some content |
       locator.fill: Timeout 30000ms exceeded.
       Call log:
         - waiting for frameLocator('[name="app-iframe"]').locator('#clipboard-area')

           at createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:356:67)
           at async createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:304:7)
           at async Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:481:3)
           at async Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:15:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:26:7)

Scenario: open office suite files with Collabora and onlyOffice (attempt 2) # tests/e2e/cucumber/features/app-provider/urlJourneys.feature:10
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:15
   ✔ When "Alice" opens the file "OpenDocument.odt" of space "personal" in Collabora through the URL for desktop client # tests/e2e/cucumber/steps/ui/navigateByUrl.ts:31
   ✖ Then "Alice" should see the content "OpenDocument Content" in editor "Collabora" # tests/e2e/cucumber/steps/ui/public.ts:87
       locator.click: Timeout 30000ms exceeded.
       Call log:
         - waiting for frameLocator('[name="app-iframe"]').locator('.leaflet-layer')

           at Object.openAndGetContentOfDocument (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:428:68)
           at async Public.getContentOfOpenDocumentOrMicrosoftWordDocument (/var/www/owncloud/web/tests/e2e/support/objects/app-files/page/public.ts:96:12)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/public.ts:97:31)
```

**Comment by saw-jan** [comment]
Collabora app isn't working
![Screenshot from 2024-07-26 14-10-28](https://github.com/user-attachments/assets/aee63a07-a3a1-4c9d-b863-909867659c10)
