### ISSUE TITLE
[QA] Nightly UI tests failing (master)

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/web#11373]
Test is failing when trying to open collabora
```
Then "Brian" should see following actions for file "secureDocument.odt"
      │ action            │
      │ Open in Collabora │
    ✖ failed
      Error: expect(received).toContain(expected) // indexOf
      Expected value: "Open in Collabora"
      Received array: ["Hide ", "Disable sync ", "Open in Collabora Hold ctrl and click to open in new tab", "Hide ", "Disable sync "]
          at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.45.0/node_modules/playwright/lib/matchers/expect.js:194:37)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:930:75)
```
and when opening OnlyOffice too

```
 Then "Alice" should see the content "Microsoft Word Content" in editor "OnlyOffice"
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
```

builds:
https://drone.owncloud.com/owncloud/web/46584/15/14
https://drone.owncloud.com/owncloud/web/46585/14/14

**Comment by saw-jan** [comment]
Should be done in PR https://github.com/owncloud/web/pull/11366
