### ISSUE TITLE
Flaky nightly failure in `e2e tests-3`

### ISSUE THREAD

**Issue by S-Panta** [owncloud/web#11496]
### Description
THere is a flaky failure on `e2e tests-3` suite:
```feature
 Scenario: Search using mediaType filter # tests/e2e/cucumber/features/search/search.feature:156
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
    And "Alice" logs in
    And "Alice" creates the following folders in personal space using API
      │ name      │
      │ mediaTest │
    And "Alice" uploads the following local file into personal space using API
      │ localFile                     │ to            │
      │ filesForUpload/testavatar.jpg │ mediaTest.jpg │
    And "Alice" creates the following files into personal space using API
      │ pathToFile    │ content        │
      │ mediaTest.txt │ I'm a Document │
      │ mediaTest.pdf │ I'm a PDF      │
      │ mediaTest.mp3 │ I'm a Audio    │
      │ mediaTest.zip │ I'm a Archive  │
[UNCAUGHT EXCEPTION] "Error: Unknown error"
    ✖ failed
      Error: expect(received).not.toBeDefined()

      Received: [Error: Unknown error]
          at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.45.0/node_modules/playwright/lib/matchers/expect.js:194:37)
          at Page.<anonymous> (/var/www/owncloud/web/tests/e2e/support/environment/actor/actor.ts:32:31)
          at Page.emit (node:events:514:28)
          at Page.emit (node:domain:489:12)
          at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/client/browserContext.js:127:34)
          at Proxy.emit (node:events:514:28)
          at Proxy.emit (node:domain:489:12)
          at Connection.dispatch (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/client/connection.js:202:21)
          at Immediate.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright-core@1.45.0/node_modules/playwright-core/lib/inProcessFactory.js:49:83)
          at processImmediate (node:internal/timers:476:21)
    When "Alice" opens the "files" app
    - skipped
```

Failure log:
https://drone.owncloud.com/owncloud/web/47146/12/10
https://drone.owncloud.com/owncloud/web/47074/12/10

Failed with error in console:
![image](https://github.com/user-attachments/assets/13be385e-0ac0-4211-a1ac-b19e50d62df7)

Tracing:
```
npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/47146/tracing/search-using-media-type-filter-alice-2024-9-2-12-41-59.zip 
```

**Comment by saw-jan** [comment]
>[UNCAUGHT EXCEPTION] "Error: Unknown error"

Must be a console error in the browser.

**Comment by saw-jan** [comment]
@S-Panta, please add the tracing report links as well

**Comment by S-Panta** [comment]
failing to reproduce this locally.

**Comment by S-Panta** [comment]
@saw-jan  I think this error is same as https://github.com/owncloud/ocis/issues/9648#issuecomment-2259937299
Removing this line might work https://github.com/owncloud/web/blob/f67c1202c4c224fb30c398fd31015fcf6472e43a/tests/e2e/cucumber/features/search/search.feature#L173
