### ISSUE TITLE
[QA] download related e2e tests fail on chromium-based browser when playwright tracing is enabled

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/web#11541]
### Description
Multiple builds are failing on keycloak tests while downloading resources via sidebar panel.

```feature
     And "Carol" navigates to the shared with me page # tests/e2e/cucumber/steps/ui/shares.ts:136
   ✖ And "Carol" downloads the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:105
       | resource      | from      | type   |
       | data.zip      | meal plan | file   |
       | lorem.txt     | meal plan | file   |
       | lorem-big.txt | meal plan | file   |
       | meal plan     |           | folder |
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('.oc-files-actions-show-details-trigger')
       ============================================================
           at openForResource (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:16:64)
           at async Object.open (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:51:14)
           at async Object.downloadResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:675:9)
           at async Resource.download (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:66:23)
           at async processDownload (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:492:17)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:110:5)
```

Builds:
- https://drone.owncloud.com/owncloud/web/47326
- https://drone.owncloud.com/owncloud/web/47327
- https://drone.owncloud.com/owncloud/web/47330
- https://drone.owncloud.com/owncloud/web/47331
- https://drone.owncloud.com/owncloud/web/47334

**Comment by saw-jan** [comment]
This is preproducable only when running test with `REPORT_TRACING=true`. :face_exhaling: 
and in CI we have `REPORT_TRACING=true` for keycloak pipeline

**Comment by saw-jan** [comment]
Tracing fix: https://github.com/owncloud/web/pull/11571

**Comment by saw-jan** [comment]
Looks like the playwright tracing `tracing.start` is broken when using download action in the ocis-web

**Comment by saw-jan** [comment]
Doesn't look like a problem with ocis or web. The problem might be with playwright library

**Comment by saw-jan** [comment]
might be a google-chrome versions: tests were working with `Google Chrome 123.0.6312.105` but started failing with `Google Chrome 128.0.6613.119`
Version got updated with the recent build of `owncloudci/nodejs` image

**Comment by saw-jan** [comment]
With the latest chromium-based browser and playwright tracing enabled, the HEAD request to download file causes the `Sign In` alert to appear. I don't think we can do anything from the test side
https://github.com/owncloud/web/blob/9a93ca210152d99332e33b836831a141e38c376d/packages/web-client/src/webdav/getFileUrl.ts#L45

**Comment by saw-jan** [comment]
Re-test it with the latest chromium/chrome browser

**Comment by PrajwolAmatya** [comment]
Tested with chromium version `131.0.6778.108` and `REPORT_TRACING=true`, we still get the same failure. `Sign In` alert appears.

**Comment by PrajwolAmatya** [comment]
> Tested with chromium version `131.0.6778.108` and `REPORT_TRACING=true`, we still get the same failure. `Sign In` alert appears during the download step.

Moving this to backlog for now.

**Comment by saw-jan** [comment]
Found out that it's not the issue with web, ocis or the chromium browser.
This is something playwright can fix: https://github.com/microsoft/playwright/issues/35891

**Comment by saw-jan** [comment]
The download seems to work fine in the test environment, even with tracing enabled.
But the issue can still occur in Ubuntu host machines. This will be discussed in https://github.com/microsoft/playwright/issues/35891

And we can close this one here
