### ISSUE TITLE
Activity e2e test failed with latest (master) ocis

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#11625]
## Describe 
Failed at tests/e2e/cucumber/features/smoke/activity.feature:12
Build: https://drone.owncloud.com/owncloud/web/47755/10/8

```
 Scenario: activity (attempt 2) # tests/e2e/cucumber/features/smoke/activity.feature:12
   ✔ Before # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:28
   ✔ Given "Admin" creates following users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:4
       | id    |
       | Alice |
       | Brian |
   ✔ And "Admin" assigns following roles to the users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:11
       | id    | role        |
       | Alice | Space Admin |
   ✔ When "Alice" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ And "Alice" creates the following project space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:113
       | name | id     |
       | team | team.1 |
   ✔ And "Alice" creates the following folder in personal space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:42
       | name                   |
       | sharedFolder/subFolder |
   ✔ And "Alice" shares the following resource using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:54
       | resource     | recipient | type | role     |
       | sharedFolder | Brian     | user | Can edit |
   ✔ And "Alice" opens the "files" app # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/application.ts:9
   ✔ Then "Alice" should see activity of the following resource # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:615
       | resource     | activity                             |
       | sharedFolder | alice shared sharedFolder with brian |
   ✔ And "Alice" navigates to the project space "team.1" # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:21
   ✖ Then "Alice" should see activity of the space # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:137
       | activity                      |
       | alice added readme.md to team |
       Error: Timed out 5000ms waiting for expect(locator).toContainText(expected)

       Locator: locator('#sidebar-panel-activities .sidebar-panel__body-content')
       Expected string: "alice added readme.md to team"
       Received string: "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
       Call log:
         - locator._expect with timeout 5000ms
         - waiting for locator('#sidebar-panel-activities .sidebar-panel__body-content')
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value ""
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "alice added readme.md to .space Sep 23, 2024, 4:19 AMalice added .space to team Sep 23, 2024, 4:19 AM Showing 2 activities"

           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.47.1/node_modules/playwright/lib/matchers/expect.js:198:37)
           at Module.checkSpaceActivity (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/actions.ts:189:65)
           at async Spaces.checkSpaceActivity (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/index.ts:74:9)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:141:9)
   - And "Alice" logs out # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:42
   - When "Brian" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   - And "Brian" navigates to the shared with me page # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:82
   - Then "Brian" should see activity of the following resource # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:615
       | resource               | activity                              |
       | sharedFolder/subFolder | alice added subFolder to Alice Hansen |
   - And "Brian" logs out # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:42
   ✔ After # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:91
```

**Comment by saw-jan** [comment]
Changes in ocis: https://github.com/owncloud/ocis/pull/10049

**Comment by amrita-shrestha** [comment]
Today it fail on https://drone.owncloud.com/owncloud/web/47802/10/8
```
1) Scenario: activity (attempt 1, retried) # tests/e2e/cucumber/features/smoke/activity.feature:12
   ✔ Before # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:28
   ✔ Given "Admin" creates following users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:4
       | id    |
       | Alice |
       | Brian |
   ✔ And "Admin" assigns following roles to the users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:11
       | id    | role        |
       | Alice | Space Admin |
   ✔ When "Alice" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ And "Alice" creates the following project space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:113
       | name | id     |
       | team | team.1 |
   ✔ And "Alice" creates the following folder in personal space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:42
       | name                   |
       | sharedFolder/subFolder |
   ✔ And "Alice" shares the following resource using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:54
       | resource     | recipient | type | role     |
       | sharedFolder | Brian     | user | Can edit |
   ✔ And "Alice" opens the "files" app # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/application.ts:9
   ✔ Then "Alice" should see activity of the following resource # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:615
       | resource     | activity                             |
       | sharedFolder | alice shared sharedFolder with brian |
   ✔ And "Alice" navigates to the project space "team.1" # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:21
   ✔ Then "Alice" should see activity of the space # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:137
       | activity                        |
       | alice added readme.md to .space |
   ✔ And "Alice" logs out # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:42
   ✔ When "Brian" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ And "Brian" navigates to the shared with me page # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:82
   ✖ Then "Brian" should see activity of the following resource # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:615
       | resource               | activity                              |
       | sharedFolder/subFolder | alice added subFolder to sharedFolder |
       Error: Timed out 5000ms waiting for expect(locator).toContainText(expected)

       Locator: locator('#sidebar-panel-activities .sidebar-panel__body-content')
       Expected string: "alice added subFolder to sharedFolder"
       Received string: "No activities"
       Call log:
         - locator._expect with timeout 5000ms
         - waiting for locator('#sidebar-panel-activities .sidebar-panel__body-content')
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"
         -   locator resolved to <div class="sidebar-panel__body-content sidebar-panel__body-content-stretch">…</div>
         -   unexpected value "No activities"

           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.47.2/node_modules/playwright/lib/matchers/expect.js:198:37)
           at Module.checkActivity (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:1394:65)
           at async Resource.checkActivity (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:265:9)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:619:9)
   - And "Brian" logs out # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:42
   ✖ After # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:91
       Error: ENOENT: no such file or directory, scandir 'reports/e2e/playwright/tracing'
           at Object.readdirSync (node:fs:1507:26)
           at filterTracingReports (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:135:28)
           at World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:112:9)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
