### ISSUE TITLE
Nightly failure due to unready app provider service

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/web#11647]
## Description
`e2e-tests` failure on `e2e-tests-app-provider` pipeline due to app provider service for `Collabora` and `OnlyOffice` not being ready while creating resource.
```
✖ And "Alice" creates the following resources # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:7
       | resource           | type         | content                 |
       | secureDocument.odt | OpenDocument | very important document |
       Error: The document of type OpenDocument did not appear in the webUI for Collabora. Possible reason could be the app provider service for Collabora was not ready yet.
           at createDocumentFile (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:239:15)
           at async createNewFileOrFolder (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:222:13)
           at async Module.createResources (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:381:5)
           at async Resource.create (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:10:9)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:11:9)
```
```
✖ And "Alice" creates the following resources # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:7
       | resource           | type         | content                 |
       | secureDocument.odt | OpenDocument | very important document |
       Error: The document of type OpenDocument did not appear in the webUI for Collabora. Possible reason could be the app provider service for Collabora was not ready yet.
           at createDocumentFile (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:239:15)
           at async createNewFileOrFolder (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:222:13)
           at async Module.createResources (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:381:5)
           at async Resource.create (file:///var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:10:9)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:11:9)
```
Build: https://drone.owncloud.com/owncloud/web/47874/14

**Comment by S-Panta** [comment]
Fails when running test on `full-ci`.
https://drone.owncloud.com/owncloud/web/47879/15/14
