### ISSUE TITLE
e2e test failing intermittently: `502 Message: Bad Gateway`

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/web#11669]
## Description

Build: https://drone.owncloud.com/owncloud/web/47922/15/8

```
Failures:

1) Scenario: access token renewal via iframe (attempt 2) # tests/e2e/cucumber/features/oidc/iframeTokenRenewal.feature:8
   ✖ Before # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:28
       Error: Logon failed: Expected status code be 200 but received 502 Message: Bad Gateway
           at getAuthorizedEndPoint (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:26:15)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
           at async setAccessAndRefreshToken (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:76:38)
           at async setAccessToken (file:///var/www/owncloud/web/tests/e2e/support/utils/tokenHelper.ts:19:5)
           at async setAdminToken (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:183:12)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:60:13)
   - Given "Admin" creates following users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:4
       | id    |
       | Alice |
   - And "Admin" assigns following roles to the users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:11
       | id    | role        |
       | Alice | Space Admin |
   - And "Alice" logs in # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:33
   - And "Alice" opens the "files" app # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/application.ts:9
   - And "Alice" navigates to the projects space page # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:9
   - And "Alice" creates the following project spaces # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:14
       | name | id     |
       | team | team.1 |
   - When "Alice" waits for token renewal via iframe # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:60
   - And "Alice" navigates to the project space "team.1" # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:21
   - And "Alice" creates the following resources # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:7
       | resource     | type   |
       | space-folder | folder |
   - Then following resources should be displayed in the files list for user "Alice" # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:228
       | resource     |
       | space-folder |
   - And "Alice" logs out # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/session.ts:42
   ✔ After # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:91
   ```

**Comment by saw-jan** [comment]
Other failing builds:
- https://drone.owncloud.com/owncloud/web/48008/15/8

**Comment by PrajwolAmatya** [comment]
ocis logs:
```console
{"level":"error","service":"proxy","error":"not found","service":"com.owncloud.web.idp","time":"2024-10-08T04:23:48Z","message":"could not select service from the registry"}
2024/10/08 04:23:48 http: proxy error: unsupported protocol scheme ""
{"level":"error","service":"proxy","error":"not found","service":"com.owncloud.web.idp","time":"2024-10-08T04:23:48Z","message":"could not select service from the registry"}
2024/10/08 04:23:48 http: proxy error: unsupported protocol scheme ""
```

**Comment by PrajwolAmatya** [comment]
Related PR https://github.com/owncloud/web/pull/11791.

**Comment by saw-jan** [comment]
We may now close this one. I haven't seen any failure related to this.

**Comment by prashant-gurung899** [comment]
@saw-jan sure, closing it now.

**Comment by nabim777** [comment]
Reopening this issue as the same failure has occurred

Build: https://drone.owncloud.com/owncloud/web/49973/15/10

```feature
Feature: Token renewal using iframe # tests/e2e/cucumber/features/oidc/iframeTokenRenewal.feature:1

  As a user
  I want the web application to automatically renew access token just before access token expires using an iframe in the background,
  So that I can be confident the application will not encounter issues related to expired access tokens.

  Scenario: access token renewal via iframe # tests/e2e/cucumber/features/oidc/iframeTokenRenewal.feature:8
(node:43) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
    ✖ failed
      Error: Logon failed: Expected status code be 200 but received 502 Message: Bad Gateway
          at getAuthorizedEndPoint (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:26:15)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async Module.setAccessAndRefreshToken (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:76:38)
          at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:55:13)
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
    - skipped
    And "Admin" assigns following roles to the users using API
      │ id    │ role        │
      │ Alice │ Space Admin │
    - skipped
    And "Alice" logs in
    - skipped
    And "Alice" opens the "files" app
    - skipped
    And "Alice" navigates to the projects space page
    - skipped
    And "Alice" creates the following project spaces
      │ name │ id     │
      │ team │ team.1 │
    - skipped
    When "Alice" waits for token renewal via iframe
    - skipped
    And "Alice" navigates to the project space "team.1"
    - skipped
    And "Alice" creates the following resources
      │ resource     │ type   │
      │ space-folder │ folder │
    - skipped
    Then following resources should be displayed in the files list for user "Alice"
      │ resource     │
      │ space-folder │
    - skipped
    And "Alice" logs out
    - skipped
```

**Comment by PrajwolAmatya** [comment]
Just ran into this failure.

Build: https://drone.owncloud.com/owncloud/web/50535/13/12

```feature
Scenario: search for content of file (attempt 2) # tests/e2e/cucumber/features/search/fullTextSearch.feature:6
   ✖ Before # file:/var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:22
       Error: Logon failed: Expected status code be 200 but received 502 Message: Bad Gateway
           at getAuthorizedEndPoint (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:26:15)
           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
           at async Module.setAccessAndRefreshToken (file:///var/www/owncloud/web/tests/e2e/support/api/token/utils.ts:76:38)
           at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/environment/index.ts:55:13)
   - Given "Admin" creates following users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:4
       | id    |
       | Alice |
       | Brian |
   - And "Admin" assigns following roles to the users using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:11
       | id    | role        |
       | Brian | Space Admin |
   - And "Alice" uploads the following local file into personal space using API # file:/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:101
       | localFile                   | to              |
       | filesForUpload/textfile.txt | fileToShare.txt |
```

**Comment by PrajwolAmatya** [comment]
Recent Builds:-
- https://drone.owncloud.com/owncloud/web/50592/16/10

**Comment by PrajwolAmatya** [comment]
This failure occurred in `e2e-test` of ocis build. Reopening the issue.
https://drone.owncloud.com/owncloud/ocis/44269/68/9

**Comment by saw-jan** [comment]
In ocis, we are using commit `eae32d564f8b2e016624b584b0e99addf802ca63` from `stable-11.0` branch and this branch doesn't contain the fix commits. The failure is due to the old commits.
