### ISSUE TITLE
Nightly fails on OCM while generating invitation token for federation share

### ISSUE THREAD

**Issue by ishabaral** [owncloud/web#12017]
## Describe the bug
Build: https://drone.owncloud.com/owncloud/web/49487/17/12
Failed scenario: user creates a federated share # tests/e2e/cucumber/features/ocm/ocm.feature:7

```
 And "Alice" generates invitation token for the federation share
    ✖ failed
      Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

      Locator: locator('span:has-text("a28b64ac-4fa4-40e4-8ff5-d564ed6bfee4")')
      Expected: visible
      Received: <element(s) not found>
      Call log:
        - locator._expect with timeout 5000ms
        - waiting for locator('span:has-text("a28b64ac-4fa4-40e4-8ff5-d564ed6bfee4")')

          at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/playwright@1.49.0/node_modules/playwright/lib/matchers/expect.js:227:37)
          at Module.generateInvitation (file:///var/www/owncloud/web/tests/e2e/support/objects/federation/actions.ts:29:74)
          at async Federation.generateInvitation (file:///var/www/owncloud/web/tests/e2e/support/objects/federation/index.ts:8:9)
          at async World.<anonymous> (file:///var/www/owncloud/web/tests/e2e/cucumber/steps/ui/federation.ts:8:5)
```

**Comment by amrita-shrestha** [comment]
@JammingBen It seems the changes in this PR https://github.com/owncloud/web/pull/11992 are the cause of the OCM test failures. This issue went unnoticed because the dev PRs were run without the full-ci tag. Is the base64-encoded invite token an intended feature?

**Comment by JammingBen** [comment]
Ah, I forgot that we already have e2e tests for OCM. Yes, the base64 encoded invite token is an intended feature, it replaces the "old" token. The process is simpler than before, `user a` needs to create an invite token, `user b` then just needs to paste it into the input field.
