### ISSUE TITLE
file might be locked when batch deleting files from trashbin

### ISSUE THREAD

**Issue by individual-it** [owncloud/web#1502]
### Steps to reproduce
1. run trashbin tests with MySQL (see  #1499)
2. get unlucky

### Expected behaviour
deleting files from trashbin should work fine

### Actual behaviour
It might happen that a file is locked

![68747470733a2f2f6d696e696f2e6f776e636c6f75642e636f6d2f70686f656e69782f73637265656e73686f74732f343031312f32303139303731312d3037313935382d3939352e706e67](https://user-images.githubusercontent.com/2425577/61044166-b75bb100-a3f7-11e9-86d5-7df263bb6b15.png)
![68747470733a2f2f6d696e696f2e6f776e636c6f75642e636f6d2f70686f656e69782f73637265656e73686f74732f343031312f32303139303731312d3037313934352d3831382e706e67](https://user-images.githubusercontent.com/2425577/61044169-b75bb100-a3f7-11e9-8d23-503b2a456127.png)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"dcdc8c1d-cadd-4519-8ef4-b19364df5bff","level":4,"time":"2019-07-11T07:19:58+00:00","remoteAddr":"192.168.176.3","user":"user1","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/trash-bin\/user1\/505","message":"Exception: \"files\/4ba94e5b88b19d9c0e3c178dda39c1dc\" is locked: {\"Exception\":\"OCP\\\\Lock\\\\LockedException\",\"Message\":\"\\\"files\\\/4ba94e5b88b19d9c0e3c178dda39c1dc\\\" is locked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(660): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/4ba94e5b8...', 2)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(591): OC\\\\Files\\\\Storage\\\\Common->acquireLock('scanner::files_...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(591): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::files_...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(591): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::files_...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(326): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('scanner::files_...', 2, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(917): OC\\\\Files\\\\Cache\\\\Scanner->scan('files_trashbin\\\/...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(700): OCA\\\\Files_Trashbin\\\\Trashbin::getVersionsFromTrash('lorem.txt', 1562829596, 'user1')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(672): OCA\\\\Files_Trashbin\\\\Trashbin::deleteVersions(Object(OC\\\\Files\\\\View), 'lorem.txt.d1562...', 'lorem.txt', 1562829596, 'user1')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/TrashBin\\\/AbstractTrashBinNode.php(138): OCA\\\\Files_Trashbin\\\\Trashbin::delete('lorem.txt', 'user1', 1562829596)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(183): OCA\\\\DAV\\\\TrashBin\\\\AbstractTrashBinNode->delete()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(295): Sabre\\\\DAV\\\\Tree->delete('trash-bin\\\/user1...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:DELETE', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(309): Sabre\\\\DAV\\\\Server->start()\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(307): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php\",\"Line\":190}"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paurakhsharma** [comment]
- [ ] Unskip test which is skipped in #1521 when the issue is fixed.

**Comment by DeepDiver1975** [comment]
How many files are in the trashbin at that point in time? @individual-it @paurakhsharma 

We need some kind of trottling in phoenix - something like: delete 4 files in parallel and not perform all requests at once - this applies to folder and files upload as well ....

This cries for some job queue or something ..... will research ...

**Comment by DeepDiver1975** [comment]
well - might even be a server issue .....

**Comment by DeepDiver1975** [comment]
@individual-it do we have a similar scenario in core? Where multiple trash items are deleted using the webdav api? This could help nailing this down ....

**Comment by individual-it** [comment]
@DeepDiver1975 we would have to send multiple webdav requests in parallel, maybe easier to implement it also as an UI test in core. Does the core UI send parallel requests when batch deleting/restoring files from trashbin?

**Comment by DeepDiver1975** [comment]
Core ui is still using the old api. We need to write this scenario as API test

**Comment by DeepDiver1975** [comment]
Got it - deleting a file from trashbin causes a scan of the full versions folder ..... which locks the folder and as a result a follow up request will trap into this locked state

https://github.com/owncloud/core/blob/51c09791790e3c260f3eef7c5388b37eea2023ef/apps/files_trashbin/lib/Trashbin.php#L917

:see_no_evil:

**Comment by DeepDiver1975** [comment]
taken care of -> close

**Comment by individual-it** [comment]
tests unskipped in https://github.com/owncloud/phoenix/pull/1798

**Comment by individual-it** [comment]
reopening because there seems to be still an issue, see https://drone.owncloud.com/owncloud/phoenix/4719/10/11 from line 894

**Comment by individual-it** [comment]
could not reproduce it locally anymore in  #6927 checking if that is still an issue in CI

**Comment by individual-it** [comment]
@kulmann please review #6927
