### ISSUE TITLE
Federation tests failing when running with openId Connect

### ISSUE THREAD

**Issue by dpakach** [owncloud/web#3309]
### Description 
Some test scenarios for federation test sharing which shares a folder and checks the contents of that folder fail while running tests with openId Connect.

Tests
```
tests/acceptance/features/webUISharingExternal/federationSharing.feature:84-125
```

Example
``` gherkin
  Scenario: upload a new file in a received share - remote server shares - local server receives
    Given the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes"
    And user "user1" from remote server has shared "simple-folder" with user "user1" from local server
    When the user opens folder "simple-folder (2)" directly on the webUI
    # Files  Should be shown in the webUI
    # But it needs page reload to show the files
    And the user reloads the current page of the webUI
    And the user uploads file "new-lorem.txt" using the webUI
    Then as "user1" file "simple-folder/new-lorem.txt" should exist on remote server

**Comment by individual-it** [comment]
It seems only to happen when navigating directly to the folder via URL, but not if clicking the shared folder

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/21946/38/29
`webUISharingExternal/federationSharing.feature:106` failed in nightly CI.
```
2) Scenario: overwrite a file in a received share - remote server shares - local server receives # features/webUISharingExternal/federationSharing.feature:106
   ✔ Before # setup.js:34
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:59
   ✔ Before # setup.js:66
   ✔ Before # setup.js:77
   ✔ Before # stepDefinitions/filesContext.js:18
   ✔ Before # stepDefinitions/generalContext.js:232
   ✔ Before # stepDefinitions/generalContext.js:278
   ✔ Before # stepDefinitions/generalContext.js:290
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given app "notifications" has been "enabled" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "no" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "no" # stepDefinitions/generalContext.js:175
   ✔ And the setting "shareapi_auto_accept_share" of app "core" has been set to "no" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And the setting "shareapi_auto_accept_share" of app "core" has been set to "no" # stepDefinitions/generalContext.js:175
   ✔ And the administrator has set the default folder for received shares to "Shares" # stepDefinitions/sharingContext.js:1339
   ✔ And the administrator has set the default folder for received shares to "Shares" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And server "%remote_backend_url%" has been added as trusted server # stepDefinitions/generalContext.js:211
   ✔ And server "%backend_url%" has been added as trusted server # stepDefinitions/generalContext.js:211
   ✔ And server "%backend_url%" has been added as trusted server on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And server "%remote_backend_url%" has been added as trusted server on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has been created with default attributes and without skeleton files on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:70
   ✔ Given user "Alice" has created folder "simple-folder" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem.txt" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" from remote server has shared "simple-folder" with user "Alice" from local server # stepDefinitions/sharingContext.js:78
   ✔ And user "Alice" from server "LOCAL" has accepted the last pending share # stepDefinitions/sharingContext.js:1207
   ✔ When the user reloads the current page of the webUI # stepDefinitions/filesContext.js:468
   ✔ And the user opens folder "Shares" using the webUI # stepDefinitions/filesContext.js:142
   ✔ And the user opens folder "simple-folder" using the webUI # stepDefinitions/filesContext.js:142
   ✔ And the user uploads overwriting file "lorem.txt" using the webUI # stepDefinitions/filesContext.js:1083
   ✖ Then as "Alice" the content of "Shares/simple-folder/lorem.txt" should be the same as the content of local file "lorem.txt" # stepDefinitions/generalContext.js:135
       Error: HTTP Request Failed: Could not download file., Status: 423 undefined
           at Object.checkStatus (/var/www/owncloud/web/tests/acceptance/helpers/httpHelper.js:44:11)
           at /var/www/owncloud/web/tests/acceptance/helpers/webdavHelper.js:30:31
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/generalContext.js:139:18)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:296
   ✔ After # stepDefinitions/generalContext.js:257
   ✔ After # stepDefinitions/generalContext.js:215
   ✔ After # setup.js:110
   ✔ After # setup.js:106
   ✔ After # setup.js:102
   ✔ After # setup.js:95
   ✔ After # setup.js:86
```

I wonder if this fail is related to this issue, or is a separate intermittent fail?

Adding to the current sprint so that someone can look.

**Comment by SwikritiT** [comment]
Similar failure here https://drone.owncloud.com/owncloud/web/21999/41/29 `webUISharingExternalToRoot/federationSharing.feature:111`

```
@notToImplementOnOCIS @disablePreviews @issue-3309
  Scenario: overwrite a file in a received share - remote server shares - local server receives # features/webUISharingExternalToRoot/federationSharing.feature:111
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (446ms).
  Using: chrome (94.0.4606.61) on Linux platform.

	Could not read config file.
	Set correct path of config file in WEB_UI_CONFIG env variable to fix this.
	Some tests may fail as a result.
    Given app "notifications" has been "enabled" in the server
    And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes" on remote server
    And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "no"
    And server "%remote_backend_url%" has been added as trusted server
    And server "%backend_url%" has been added as trusted server
    And server "%backend_url%" has been added as trusted server on remote server
    And server "%remote_backend_url%" has been added as trusted server on remote server
    And user "Alice" has been created with default attributes and without skeleton files on remote server
    And user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <#user> was visible after 1366 milliseconds.
√ Element <#user> was not present after 25 milliseconds.
√ Element <button[type=submit]> was visible after 41 milliseconds.
√ Element <button[type=submit]> was not present after 61 milliseconds.
√ Element <.app-content> was visible after 1389 milliseconds.
    Given the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes"
    And user "Alice" has created folder "simple-folder" on remote server
    And user "Alice" has created file "simple-folder/lorem.txt" on remote server
    And user "Alice" from remote server has shared "simple-folder" with user "Alice" from local server
    And the user reloads the current page of the webUI
    And the user opens folder "simple-folder" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"9375ff5517000df6239b5b67187c4b17","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.navigateToFolder (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:196:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 23 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 22 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 496 milliseconds.
    When the user uploads overwriting file "lorem.txt" using the webUI
√ Element <#new-file-menu-btn:enabled> was visible after 46 milliseconds.
√ Element <#files-file-upload-button> was visible after 60 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal> was not present after 20 milliseconds.
Timeout waiting for Ajax calls to start
    Then as "Alice" the content of "simple-folder/lorem.txt" should be the same as the content of local file "lorem.txt"
    ✖ failed
      Error: HTTP Request Failed: Could not download file., Status: 423 undefined
          at Object.checkStatus (/var/www/owncloud/web/tests/acceptance/helpers/httpHelper.js:44:11)
          at /var/www/owncloud/web/tests/acceptance/helpers/webdavHelper.js:30:31
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/generalContext.js:139:18)

  Result: FAILED
```

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22000/41/29
```
The following scenarios passed on retry:
-------------------------------
- webUISharingExternalToRoot/federationSharing.feature:111
-------------------------------
```

So this is an intermittent test :(

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22002/40/29
```
The following scenarios passed on retry:
-------------------------------
- webUISharingExternal/federationSharing.feature:106
-------------------------------
```

So 111 is not the only scenario that is intermittent.

Maybe there is just some timing issues with the federated share actually being seen in the web UI?

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/22031/38/29

`webUISharingExternal/federationSharing.feature:106` failed in nightly CI last night.

**Comment by saw-jan** [comment]
Passed on retry https://drone.owncloud.com/owncloud/web/22137/41/29
```

Scenario: overwrite a file in a received share - remote server shares - local server receives (attempt 1, retried) # features/webUISharingExternalToRoot/federationSharing.feature:111
   ✔ Before # setup.js:34
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:59
   ✔ Before # setup.js:66
   ✔ Before # setup.js:77
   ✔ Before # stepDefinitions/filesContext.js:18
   ✔ Before # stepDefinitions/generalContext.js:290
   ✔ Before # stepDefinitions/generalContext.js:336
   ✔ Before # stepDefinitions/generalContext.js:348
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given app "notifications" has been "enabled" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "no" # stepDefinitions/generalContext.js:177
   ✔ And server "%remote_backend_url%" has been added as trusted server # stepDefinitions/generalContext.js:213
   ✔ And server "%backend_url%" has been added as trusted server # stepDefinitions/generalContext.js:213
   ✔ And server "%backend_url%" has been added as trusted server on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And server "%remote_backend_url%" has been added as trusted server on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has been created with default attributes and without skeleton files on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:70
   ✔ Given the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes" # stepDefinitions/generalContext.js:177
   ✔ And user "Alice" has created folder "simple-folder" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem.txt" on remote server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" from remote server has shared "simple-folder" with user "Alice" from local server in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the user reloads the current page of the webUI # stepDefinitions/filesContext.js:468
   ✔ And the user opens folder "simple-folder" using the webUI # stepDefinitions/filesContext.js:142
   ✔ When the user uploads overwriting file "lorem.txt" using the webUI # stepDefinitions/filesContext.js:1083
   ✖ Then as "Alice" the content of "simple-folder/lorem.txt" should be the same as the content of local file "lorem.txt" # stepDefinitions/generalContext.js:137
       Error: HTTP Request Failed: Could not download file., Status: 423 undefined
           at Object.checkStatus (/var/www/owncloud/web/tests/acceptance/helpers/httpHelper.js:44:11)
           at /var/www/owncloud/web/tests/acceptance/helpers/webdavHelper.js:30:31
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/generalContext.js:141:18)
```
