### ISSUE TITLE
scrollTo broken with oCIS

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#4994]
### Steps to reproduce
1. start oCIS single binary from v1.5.0-rc1 (or final)
2. Create a folder

### Expected behaviour
The UI should scroll to the created folder.

### Actual behaviour
Doesn't scroll.

#### Browser log
```
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '.oc-tbody-tr-MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OmM1Nzc1OTJlLTk3NDQtNDgwMi1iMWY2LTQyZmI0ZWU5YzgyMA==' is not a valid selector.
    at Object.$ (https://localhost:9200/js/_chunks/vendor-59cd3ff3.js:346:43901)
    at s.z [as $scrollTo] (https://localhost:9200/js/_chunks/vendor-59cd3ff3.js:346:45548)
    at scrollToResource (https://localhost:9200/js/web-app-files-cfb2e803.js:1:28115)
    at https://localhost:9200/js/web-app-files-cfb2e803.js:1:104613
```

**Comment by pascalwengerter** [comment]
Closing in favor of #5967 which keeps track of scrollTo topics
