### ISSUE TITLE
Investigate web test nightly fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6053]
These tests failed last night in CI:

https://drone.owncloud.com/owncloud/web/20441/51/13

webUIRenameFolders/renameFolders.feature:148

https://drone.owncloud.com/owncloud/web/20441/54/13

webUIDeleteFilesFolders/deleteFilesFolders.feature:239

Both failed with:
`NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>:`

I think that the sidebar was refactored recently, so there might be some timing issue...

Investigate and see if the tests need fixing, or is there a real problem with the web UI or backend system-under-test.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20441/51/13

webUIRenameFolders/renameFolders.feature:148

```
  Scenario: User tries to rename a folder that used to exist but does not anymore # features/webUIRenameFolders/renameFolders.feature:148
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (1249ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files
    And user "Alice" has created folder "simple-folder"
    And user "Alice" has created folder "simple-empty-folder"
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 968 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 76 milliseconds.
√ Element <.oc-app-container> was visible after 1210 milliseconds.
    And the user has browsed to the files page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'All files')]> was visible after 26 milliseconds.
    Given the user has browsed to the files page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'All files')]> was visible after 139 milliseconds.
    And the following files have been deleted by user "Alice"
      │ name          │
      │ simple-folder │
    When the user tries to rename folder "simple-folder" to "new-simple-folder" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"346263e29af9497e83ef740aaac972dc","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:43:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:18)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:84:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:346:53)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"346263e29af9497e83ef740aaac972dc","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:238:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:84:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"346263e29af9497e83ef740aaac972dc","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:346:24)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:84:7)
Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 5000 milliseconds. - expected "found" but got: "not found" (5007ms)
undefined    ✖ failed
      Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 5000 milliseconds. - expected "found" but got: "not found" (5007ms)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:348:18)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
          at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:84:7)
    Then the error message with header 'Error while renaming "simple-folder" to "new-simple-folder"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then folder "simple-folder" should not be listed on the webUI
    - skipped
    And folder "new-simple-folder" should not be listed on the webUI
    - skipped
    And as "Alice" folder "simple-folder" should not exist
    - skipped
    And as "Alice" folder "new-simple-folder" should not exist
    - skipped
```

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/20441/54/13

webUIDeleteFilesFolders/deleteFilesFolders.feature:239

```
  Scenario: Try to delete file and folder that used to exist but does not anymore # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:239
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (394ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 845 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 367 milliseconds.
√ Element <.oc-app-container> was visible after 893 milliseconds.
    And the user reloads the current page of the webUI
    Given user "Alice" has created folder "simple-folder"
    And user "Alice" has created file "lorem.txt"
    And the user has browsed to the files page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button) and contains(text(),'All files')]> was visible after 270 milliseconds.
    And the following files have been deleted by user "Alice"
      │ name          │
      │ lorem.txt     │
      │ simple-folder │
    When the user deletes file "lorem.txt" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"323dcef245fed94dd373d44bcdd4b0a9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:43:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:18)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:52:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:197:51)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"323dcef245fed94dd373d44bcdd4b0a9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:238:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:52:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"323dcef245fed94dd373d44bcdd4b0a9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:346:24)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:52:7)
Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 5000 milliseconds. - expected "found" but got: "not found" (5020ms)
undefined    ✖ failed
      Timed out while waiting for element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> to be present for 5000 milliseconds. - expected "found" but got: "not found" (5020ms)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:348:18)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
          at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:52:7)
    Then the error message with header 'Error while deleting "lorem.txt"' should be displayed on the webUI
    - skipped
    When the user clears all error message from the webUI
    - skipped
    And the user deletes folder "simple-folder" using the webUI
    - skipped
    Then the error message with header 'Error while deleting "simple-folder"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
    And folder "simple-folder" should not be listed on the webUI
    - skipped
    And as "Alice" file "lorem.txt" should not exist
    - skipped
    And as "Alice" folder "simple-folder" should not exist
    - skipped
```

**Comment by pascalwengerter** [comment]
#6039 is not yet merged, the "not finding sidebar" logs are just noise and the real issues are the `Timed out while waiting for element ...` lines

**Comment by dpakach** [comment]
The reason for this seems to be the nightwatch timeout being too low in https://github.com/owncloud/web/blob/master/tests/acceptance/nightwatch.conf.js#L55.

@pascalwengerter I believe you reduced that to make the CI  builds faster. Should we increase the timeout and make tradeoff with few minutes of extra Build time in CI?

**Comment by phil-davis** [comment]
Note: both the fails that happened the other night were when running with oCIS as the back-end system in the test environment. I thought that the oCIS backend would be faster than the oC10 backend, and so we would see this problem more often when running with the oC10 backend.

Am I thinking straight? Or is there some reason that oCIS sometimes slows down doing these actions? Or is it just random, and the problem also sometimes happens when running with the oC10 backend?

**Comment by kulmann** [comment]
> The reason for this seems to be the nightwatch timeout being too low in https://github.com/owncloud/web/blob/master/tests/acceptance/nightwatch.conf.js#L55.
> 
> @pascalwengerter I believe you reduced that to make the CI builds faster. Should we increase the timeout and make tradeoff with few minutes of extra Build time in CI?

Please don't. CI is already running for a huge amount of time, if any I want that to go down, not up.

**Comment by phil-davis** [comment]
IMO that wait is a "polling wait". If a UI element "appears" in 1 second, then the real-time wait will be only about 1.1 seconds (whenever the next poll-check is sent from the test framework to the browser). So the 5 seconds only happens if the element does not appear.

Tests that are checking for "negative" conditions (that an element does not exist) are only waiting for `waitForNegativeConditionTimeout` before assuming that the element does not and will not exist.

@dpakach please correct me if I am talking rubbish.

**Comment by dpakach** [comment]
> IMO that wait is a "polling wait". If a UI element "appears" in 1 second, then the real-time wait will be only about 1.1 seconds (whenever the next poll-check is sent from the test framework to the browser). So the 5 seconds only happens if the element does not appear.
> 
> Tests that are checking for "negative" conditions (that an element does not exist) are only waiting for `waitForNegativeConditionTimeout` before assuming that the element does not and will not exist. We should be usng that constant for all "negative" tests.
> 
> @dpakach please correct me if I am talking rubbish.

@phil-davis that is correct. So In fact even having higher timeout will not increase the total build time by too much. so we can increase the timeout as long as `waitForNegativeConditionTimeout` is low.

**Comment by kulmann** [comment]
Ah ok, thanks for taking the time to investigate and explain. 👍 
In that case I'd be fine with increasing the timeout again to work around the issue. Please double check if the CI runtime is not affected by this.
