### ISSUE TITLE
webUISharingAcceptSharesToRoot/acceptShares.feature:108 fails intermittently

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6097]
https://drone.owncloud.com/owncloud/web/20687/16/20
```
  Scenario: unshare auto-accepted shares # features/webUISharingAcceptSharesToRoot/acceptShares.feature:108
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (237ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given these users have been created with default attributes and without skeleton files:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Brian" has logged in using the webUI
√ Element <#user> was visible after 765 milliseconds.
√ Element <#user> was not present after 9 milliseconds.
√ Element <button[type=submit]> was visible after 33 milliseconds.
√ Element <button[type=submit]> was not present after 32 milliseconds.
√ Element <.oc-app-container> was visible after 763 milliseconds.
    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "yes"
    And user "Alice" has created folder "/simple-folder"
    And user "Alice" has uploaded file "testavatar.jpg" to "/testimage.jpg"
    And these groups have been created:
      │ groupname │
      │ grp1      │
    And user "Brian" has been added to group "grp1"
    And user "Alice" has shared folder "/simple-folder" with group "grp1"
    And user "Alice" has shared folder "/testimage.jpg" with user "Brian"
    And the user has browsed to the shared-with-me page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 362 milliseconds.
    When the user unshares folder "simple-folder" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:43:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:18)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:287:51)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:238:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:346:24)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 11 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 11 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.activatePanel (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:71:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:219:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 9 milliseconds.
    And the user unshares file "testimage.jpg" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='testimage.jpg' or @data-test-resource-path='/testimage.jpg')]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:48:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:11)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:346:24)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:251:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:241:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:218:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='testimage.jpg' or @data-test-resource-path='/testimage.jpg')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 11 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 8 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"15ecc616aaeabf6c75f62aaa5cc68669","status":0,"value":[]}
       at Proxy.activatePanel (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:71:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:219:7)
       at Proxy.declineShare (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:72:7)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 9 milliseconds.
    And the user browses to the files page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 160 milliseconds.
    Then folder "simple-folder" should not be listed on the webUI
√ Passed [ok]: Folder 'simple-folder' is not listed on the filesList
    And file "testimage.jpg" should not be listed on the webUI
Failed [ok]: (Error: File 'testimage.jpg' is listed on the filesList) - expected "true" but got: "false" (0ms)
undefined    ✖ failed
      Error while running "ok" command: Failed [ok]: (Error: File 'testimage.jpg' is listed on the filesList) - expected "true" but got: "false" (0ms)
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:447:28
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    When the user browses to the shared-with-me page in declined shares view
    - skipped
    Then folder "simple-folder" shared by "Alice Hansen" should be in "Declined" state on the webUI
    - skipped
    And file "testimage.jpg" shared by "Alice Hansen" should be in "Declined" state on the webUI
    - skipped

  Result: FAILED
```

**Comment by kiranparajuli589** [comment]
the test PR verifies the reported flaky scenario is behaving fine now in the CI

> issue can be reopened if the reported behaviour persists

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/21524/15/22
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingAcceptSharesToRoot/acceptShares.feature:108
```

```
2) Scenario: unshare auto-accepted shares (attempt 2) # features/webUISharingAcceptSharesToRoot/acceptShares.feature:108
   ✔ Before # setup.js:34
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:59
   ✔ Before # setup.js:66
   ✔ Before # setup.js:77
   ✔ Before # stepDefinitions/filesContext.js:20
   ✔ Before # stepDefinitions/generalContext.js:231
   ✔ Before # stepDefinitions/generalContext.js:277
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:73
       | username |
       | Alice    |
       | Brian    |
   ✔ And user "Brian" has logged in using the webUI # stepDefinitions/loginContext.js:70
   ✔ Given the setting "shareapi_auto_accept_share" of app "core" has been set to "yes" # stepDefinitions/generalContext.js:174
   ✔ And user "Alice" has created folder "/simple-folder" # stepDefinitions/filesContext.js:1053
   ✔ And user "Alice" has uploaded file "testavatar.jpg" to "/testimage.jpg" # stepDefinitions/filesContext.js:114
   ✔ And these groups have been created in the server: # stepDefinitions/middlewareContext.js:73
       | groupname |
       | grp1      |
   ✔ And user "Brian" has been added to group "grp1" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has shared folder "/simple-folder" with group "grp1" # stepDefinitions/sharingContext.js:501
   ✔ And user "Alice" has shared folder "/testimage.jpg" with user "Brian" # stepDefinitions/sharingContext.js:487
   ✔ And the user has browsed to the shared-with-me page # stepDefinitions/filesContext.js:49
   ✔ When the user unshares folder "simple-folder" using the webUI # stepDefinitions/filesContext.js:274
   ✔ And the user unshares file "testimage.jpg" using the webUI # stepDefinitions/filesContext.js:274
   ✔ And the user browses to the files page # stepDefinitions/filesContext.js:25
   ✔ Then folder "simple-folder" should not be listed on the webUI # stepDefinitions/filesContext.js:439
   ✖ And file "testimage.jpg" should not be listed on the webUI # stepDefinitions/filesContext.js:428
       Error while running "ok" command: Failed [ok]: (Error: File 'testimage.jpg' is listed on the filesList) - expected "true" but got: "false" (0ms)
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:435:28
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - When the user browses to the shared-with-me page in declined shares view # stepDefinitions/filesContext.js:45
   - Then folder "simple-folder" shared by "Alice Hansen" should be in "Declined" state on the webUI # stepDefinitions/sharingContext.js:1146
   - And file "testimage.jpg" shared by "Alice Hansen" should be in "Declined" state on the webUI # stepDefinitions/sharingContext.js:1146
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:295
   ✔ After # stepDefinitions/generalContext.js:256
   ✔ After # stepDefinitions/generalContext.js:214
   ✔ After # setup.js:110
   ✔ After # setup.js:106
   ✔ After # setup.js:102
   ✔ After # setup.js:95
   ✔ After # setup.js:86
```

It can still fail.

**Comment by phil-davis** [comment]
Another example of fail in PR #6274

**Comment by kiranparajuli589** [comment]
I suspect the issue is similar to https://github.com/owncloud/web/issues/6227, but yes it needs further inspection

**Comment by phil-davis** [comment]
In PR #6308 
https://drone.owncloud.com/owncloud/web/22152/15/21
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingAcceptSharesToRoot/acceptShares.feature:108
```

**Comment by kiranparajuli589** [comment]
passed on retry in #6281 
build: https://github.com/owncloud/web/pull/6281#issuecomment-1021936556

**Comment by phil-davis** [comment]
failed in nightly last night: https://drone.owncloud.com/owncloud/web/22203/13/21

**Comment by phil-davis** [comment]
failed on retry here: https://github.com/owncloud/web/pull/6357#issuecomment-1028571910

**Comment by phil-davis** [comment]
passed on retry here: https://github.com/owncloud/web/pull/6357#issuecomment-1028589758

**Comment by phil-davis** [comment]
filed on retry here: https://github.com/owncloud/web/pull/6357#issuecomment-1028668926

This fail happens quite often.

**Comment by phil-davis** [comment]
I added this to the current sprint and put QA-p1 because this happens frequently enough that it really needs to be sorted out.
