### ISSUE TITLE
failing acceptance test webUISharingInternalGroups/shareWithGroups.feature:255

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6171]
https://drone.owncloud.com/owncloud/web/21180/28/22
```
Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="26" and @aria-label="Sunday, December 26, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10014ms)
undefined    ✖ failed
      Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="26" and @aria-label="Sunday, December 26, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10014ms)
          at Proxy.isExpiryDateDisabled (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:107:20)
          at Proxy.setExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:178:37)
          at Proxy.changeCollaboratorExpiryDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:554:73)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I have restarted the CI. Let's see if it is intermittent.

**Comment by phil-davis** [comment]
webUISharingInternalGroupsToRoot/shareWithGroups.feature:229
https://drone.owncloud.com/owncloud/web/21181/29/22
```
Error while running .executeScript() protocol action: An error occurred while executing user supplied JavaScript. – javascript error: Cannot read properties of null (reading ...

Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="26" and @aria-label="Sunday, December 26, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10011ms)
undefined    ✖ failed
      Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="26" and @aria-label="Sunday, December 26, 2021"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10011ms)
          at Proxy.isExpiryDateDisabled (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:107:20)
          at Proxy.setExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:178:37)
          at Proxy.changeCollaboratorExpiryDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:554:73)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This looks similar.
