### ISSUE TITLE
'Given user "Alice" has created file "simple-folder/lorem.txt" on remote server' failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6225]
I guess that this is now failing after the changes in the middleware yesterday:
https://github.com/owncloud/owncloud-test-middleware/pull/73
https://github.com/owncloud/owncloud-test-middleware/pull/74

This morning nodejs in the middleware has been bumped from 14 to 16:
https://github.com/owncloud/owncloud-test-middleware/pull/76

and there is less failing.

But:

https://drone.owncloud.com/owncloud/web/21605/41/29
```
Scenario: automatically accept a federation share when it is allowed by the config # features/webUISharingExternalToRoot/federationSharing.feature:73
- Connecting to selenium on port 4444...
  Connected to selenium on port 4444 (326ms).
  Using: chrome (94.0.4606.61) on Linux platform.
	Could not read config file.
	Set correct path of config file in WEB_UI_CONFIG env variable to fix this.
	Some tests may fail as a result.
    Given app "notifications" has been "enabled" in the server
    And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes" on remote server
    And the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "no"
    And server "%remote_backend_url%" has been added as trusted server
    And server "%backend_url%" has been added as trusted server
    And server "%backend_url%" has been added as trusted server on remote server
    And server "%remote_backend_url%" has been added as trusted server on remote server
    And user "Alice" has been created with default attributes and without skeleton files on remote server
    And user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <#user> was visible after 768 milliseconds.
√ Element <#user> was not present after 13 milliseconds.
√ Element <button[type=submit]> was visible after 38 milliseconds.
√ Element <button[type=submit]> was not present after 41 milliseconds.
√ Element <.oc-app-container> was visible after 813 milliseconds.
    Given the setting "auto_accept_trusted" of app "federatedfilesharing" has been set to "yes"
    And user "Alice" has created folder "simple-folder" on remote server
    And user "Alice" has created file "simple-folder/lorem.txt" on remote server
    ✖ failed
      Error: Error: HTTP Request Failed: Could not create the file "simple-folder/lorem.txt" for user "Alice"., Status: 409 undefined
          at Object.checkStatus (/usr/src/app/src/helpers/httpHelper.js:44:11)
          at Object.exports.createFile (/usr/src/app/src/helpers/webdavHelper.js:199:43)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/stepDefinitions/filesContext.js:120:5
          at async Object.exports.runOnRemoteBackend (/usr/src/app/src/helpers/backendHelper.js:44:11)
          at async /usr/src/app/src/app.js:66:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by phil-davis** [comment]
PR #6223 has passed. CI is green again.

**Comment by kulmann** [comment]
Thank you! ❤️

**Comment by kulmann** [comment]
Thank you! ❤️
