### ISSUE TITLE
webUIPrivateLinks/accessingPrivateLinks.feature:17 is failing frequently and needs investigation

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#6227]
This test is failing frequently in oC10IntegrationApp1-chrome-latest  and sometimes passing on retry
https://drone.owncloud.com/owncloud/web/21634/68/22
https://drone.owncloud.com/owncloud/web/21618/68/22

```
 @smokeTest @ocisSmokeTest
  Scenario: Access private link before authorisation # features/webUIPrivateLinks/accessingPrivateLinks.feature:17
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (375ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    When an anonymous user tries to navigate to the private link created by user "Alice" for file "lorem.txt"
√ Element <#web> was not present after 19 milliseconds.
    Then the user should be redirected to the IdP login page
√ Element <#body-login> was visible after 1311 milliseconds.
√ Passed [ok]: true ok
    When user "Alice" has logged in using the webUI
√ Element <#user> was visible after 1012 milliseconds.
√ Element <#user> was not present after 20 milliseconds.
√ Element <button[type=submit]> was visible after 46 milliseconds.
√ Element <button[type=submit]> was not present after 16 milliseconds.
√ Element <.oc-app-container> was visible after 1548 milliseconds.
    Then the app-sidebar for file "lorem.txt" should be visible on the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"eae59fb39941fe063b985ee1677dc8e1","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:43:24)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1027:69)
    ✖ failed
      AssertionError [ERR_ASSERTION]: app-sidebar should be visible, but is not
          + expected - actual

          -false
          +true

          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1031:12)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And the "details" details panel should be visible
    - skipped

  Result: FAILED
```

**Comment by phil-davis** [comment]
It failed last night in the pipeline that runs with oc10IntegrationApp:
https://drone.owncloud.com/owncloud/web/21720/66/22

**Comment by kiranparajuli589** [comment]
passed on retry for this [build](https://drone.owncloud.com/owncloud/web/21754/13/1) in https://github.com/owncloud/web/pull/6238

**Comment by phil-davis** [comment]
webUIPrivateLinks/accessingPrivateLinks.feature:17 failed in nightly last night:
https://drone.owncloud.com/owncloud/web/21803/66/22

**Comment by saw-jan** [comment]
Cannot get a single fail with 80 runs
https://drone.owncloud.com/owncloud/web/21814/8/21
I am trying to fix the screenshot in PR https://github.com/owncloud/web/pull/6244 maybe we can find something in screenshot.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/web/21860/68/22

It seems to fail in the oC10IntegrationApp1 pipeline. @saw-jan try running it many times in that drone CI environment.

**Comment by kiranparajuli589** [comment]
https://drone.owncloud.com/owncloud/web/21900/68/1 at https://github.com/owncloud/web/pull/6181

**Comment by saw-jan** [comment]
100 runs passed
https://drone.owncloud.com/owncloud/web/21942/9/22
