### ISSUE TITLE
webUIUserJourney/journey1.feature:11 passes on retry

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6317]
Build link https://drone.owncloud.com/owncloud/web/22182/66/1

```console
  @journey
  Scenario: simple upload of a file that does not exist before # features/webUIUserJourney/journey1.feature:11
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (390ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Brian" has been created with default attributes and without skeleton files in the server
    When user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 739 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 117 milliseconds.
√ Element <.app-content> was visible after 924 milliseconds.
    And the user uploads file "new-lorem.txt" using the webUI
√ Element <#new-file-menu-btn:enabled> was visible after 37 milliseconds.
√ Element <#files-file-upload-button> was visible after 48 milliseconds.
√ Element <#files-upload-progress> was visible after 33 milliseconds.
√ Element <#files-upload-progress> was not visible after 29 milliseconds.
    Then no message should be displayed on the webUI
    And file "new-lorem.txt" should be listed on the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 18 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 19 milliseconds.
    And as "Alice" the content of "new-lorem.txt" should be the same as the content of local file "new-lorem.txt" in the server
    When the user browses to the files page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 18 milliseconds.
    And the user downloads file "new-lorem.txt" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:52:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:18)
       at Proxy.downloadFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:158:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:1114:51)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:252:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.downloadFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:158:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.downloadFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:158:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem.txt' or @data-test-resource-path='/new-lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 21 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 12 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.activatePanel (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:80:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:233:7)
       at Proxy.downloadFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:158:7)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 13 milliseconds.
    Then no message should be displayed on the webUI
    And the user renames file "new-lorem.txt" to "new-lorem2.txt" using the webUI
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 12 milliseconds.
√ Element <.oc-modal> was visible after 40 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal> was not present after 108 milliseconds.
    And file "new-lorem2.txt" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 19 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 11 milliseconds.
    And the user deletes file "new-lorem2.txt" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:52:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:18)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:159:51)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:252:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 21 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 11 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.activatePanel (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:80:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:233:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:7)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 14 milliseconds.
√ Element <.oc-modal> was not present after 115 milliseconds.
    And the user browses to the trashbin page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 12 milliseconds.
    And file "new-lorem2.txt" should be listed on the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 13 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 12 milliseconds.
    And the user restores file "new-lorem2.txt" from the trashbin using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:52:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:28)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:18)
       at Proxy.restoreFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:128:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:919:53)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:252:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.restoreFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:128:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.restoreFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:128:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 11 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 13 milliseconds.
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 12 milliseconds.
    And the user browses to the files page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 187 milliseconds.
    And file "new-lorem2.txt" should be listed on the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt') and @data-test-resource-type='file']>: 
   {"sessionId":"5b0360f186f2321616d4d56c92b7a0fb","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:367:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:336:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:343:51)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-lorem2.txt' or @data-test-resource-path='/new-lorem2.txt') and @data-test-resource-type='file']>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:377:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:336:7)
```

**Comment by pascalwengerter** [comment]
@kiranparajuli589 @phil-davis have you come across this recently? If so, what's the plan of actions? If not, please close :)

**Comment by phil-davis** [comment]
@kiranparajuli589 I haven't noticed this lately, have you?

**Comment by kiranparajuli589** [comment]
No more reports are made here, seems like it's stable now.
closing
