### ISSUE TITLE
Lots of warnings & errors when running unit tests

### ISSUE THREAD

**Issue by pascalwengerter** [owncloud/web#6337]
### Expected behaviour
(Successful) Unit test runs provide minimal output to console

### Actual behaviour
(Successful) Unit test runs spam the console with warnings & errors

### Hints
Especially the tests in `packages/web-app-files/tests/unit/views/` seem to be offenders

**Comment by pascalwengerter** [comment]
@individual-it could your team take a look in the upcoming weeks?

**Comment by phil-davis** [comment]
I added to the Test Automation Backlog project. We will put it in a test automation sprint.

**Comment by kulmann** [comment]
Related to this: https://github.com/owncloud/web/issues/6130

**Comment by individual-it** [comment]
added it to the current sprint and assigned myselg, could be as simple as adding `--silent` to yest

**Comment by phil-davis** [comment]
Agree ^ - fix/refactor anything that is actually "dodgy"

**Comment by individual-it** [comment]
So I misunderstood what the task is about
I've created now a couple PRs with some easy fixes - mostly pinging those who have worked last/initially on them to review. But of-course everybody please feel free to review.

What I could not solve so far:
- mocking elements with `v-translate` https://github.com/owncloud/web/pull/6404#pullrequestreview-877568680
- finding out from which test these kind of messages come, the error output seems not to be related to the test run output
   ```
   node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

    [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: router.replace is not a function".] {
     code: 'ERR_UNHANDLED_REJECTION'
   }
   ```

any ideas on those issues?

**Comment by individual-it** [comment]
after #6415 those tests should not pass anymore

**Comment by individual-it** [comment]
after merging #6421 this should be fixed
![grafik](https://user-images.githubusercontent.com/2425577/153572218-6069f28f-f410-4408-86b9-a8d4545ec23c.png)

**Comment by kulmann** [comment]
wow 😍

**Comment by individual-it** [comment]
reopening because there is a new error
![grafik](https://user-images.githubusercontent.com/2425577/156704099-202c69b4-8741-4a21-aecb-585c19cb309b.png)

**Comment by individual-it** [comment]
reopening because seeing this in nightly builds:
```
PASS packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.js (16.156 s)
  ● Console
    console.error
      [Vue warn]: The setup binding property "sharesLoading" is already declared.

      found in
      ---> <FileShares>
             <Root>
```

```
PASS packages/web-app-files/tests/unit/components/SideBar/Details/FileDetails.spec.js
  ● Console
    console.error
      [Vue warn]: Unknown custom element: <oc-status-indicators> - did you register the component correctly? For recursive components, make sure to provide the "name" option.      

      found in

      ---> <FileDetails>
             <Root>
```

```
PASS packages/web-app-files/tests/unit/components/AppBar/SharesNavigation.spec.js
  ● Console
    console.warn
      [vue-router] Route with name 'files-shares-with-me' does not exist

      22 |   return comparatives
      23 |     .map((comparative) => {
    > 24 |       const { href: comparativeHref } = router.resolve({
         |                                                ^
      25 |         ...comparative
      26 |         // ...(comparative.name && { name: resolveRouteName(comparative.name) })
      27 |       })
......

    console.warn
      [vue-router] Route with name 'files-shares-with-others' does not exist

      22 |   return comparatives
      23 |     .map((comparative) => {
    > 24 |       const { href: comparativeHref } = router.resolve({
         |                                                ^
      25 |         ...comparative
      26 |         // ...(comparative.name && { name: resolveRouteName(comparative.name) })
      27 |       })

.......

    console.warn
      [vue-router] Route with name 'files-shares-via-link' does not exist

      22 |   return comparatives
      23 |     .map((comparative) => {
    > 24 |       const { href: comparativeHref } = router.resolve({
         |                                                ^
      25 |         ...comparative
      26 |         // ...(comparative.name && { name: resolveRouteName(comparative.name) })
      27 |       })
```

**Comment by individual-it** [comment]
for now this should be fixed after  #6732 &  #6733 get merged

**Comment by kulmann** [comment]
Thanks for taking care! Closing now, since I merged your two PRs.

**Comment by individual-it** [comment]
reopening because seeing this in nightly builds:
```
PASS packages/web-runtime/tests/unit/components/Topbar/FeedbackLink.spec.js
  ● Console

    console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/var/www/owncloud/web/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at Request.<anonymous> (/var/www/owncloud/web/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (events.js:412:35)
          at ClientRequest.<anonymous> (/var/www/owncloud/web/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
          at ClientRequest.emit (events.js:400:28)
          at Socket.socketErrorListener (_http_client.js:475:9)
          at Socket.emit (events.js:400:28)
          at emitErrorNT (internal/streams/destroy.js:106:8)
          at emitErrorCloseNT (internal/streams/destroy.js:74:3)
          at processTicksAndRejections (internal/process/task_queues.js:82:21) undefined

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:66:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)

**Comment by individual-it** [comment]
reopening again, because log output came back, mostly share jail
see https://drone.owncloud.com/owncloud/web/25449/8/6
