### ISSUE TITLE
shareWithUsers.feature:342 test can fail in CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6341]
https://drone.owncloud.com/owncloud/web/22275/56/15

```
10) Scenario: Sharing the share_folder to user is not possible # features/webUISharingInternalUsers/shareWithUsers.feature:342
    ✔ Before # setup.js:34
    ✔ Before # setup.js:38
    ✔ Before # setup.js:42
    ✔ Before # setup.js:59
    ✔ Before # setup.js:66
    ✔ Before # setup.js:77
    ✔ Before # stepDefinitions/filesContext.js:18
    ✔ Before # stepDefinitions/generalContext.js:237
    ✔ Before # stepDefinitions/generalContext.js:275
    ✔ Before # stepDefinitions/middlewareContext.js:46
    ✔ Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" # stepDefinitions/generalContext.js:124
    ✔ And the administrator has set the default folder for received shares to "Shares" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:73
        | username |
        | Alice    |
        | Brian    |
    ✔ And user "Brian" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
    ✔ Given user "Carol" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Brian" has shared folder "simple-folder" with user "Alice" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has accepted the share "Shares/simple-folder" offered by user "Brian" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:70
    ✔ When the user opens the share dialog for file "Shares" using the webUI # stepDefinitions/sharingContext.js:593
    ✖ Then the share permission denied message should be displayed in the sharing dialog on the webUI # stepDefinitions/sharingContext.js:579
        Timed out while waiting for element <//p[@data-testid="files-collaborators-no-reshare-permissions-message"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10014ms)
            at Proxy.isSharePermissionMessageVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/sharingDialog.js:531:19)
            at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/sharingContext.js:582:57)
    ✔ After # stepDefinitions/middlewareContext.js:60
    ✔ After # stepDefinitions/generalContext.js:293
    ✔ After # stepDefinitions/generalContext.js:262
    ✔ After # stepDefinitions/generalContext.js:203
    ✔ After # setup.js:110
    ✔ After # setup.js:106
    ✔ After # setup.js:102
    ✔ After # setup.js:95
    ✔ After # setup.js:86
```

Needs investigation.

**Comment by SwikritiT** [comment]
@phil-davis this test is failing because sometimes you can share the `Shares` folder. Couldn't reproduce manually but it got caught when running the test multiple times. Probably similar to  #6419. What do we do now?
![Screenshot from 2022-02-17 16-23-09](https://user-images.githubusercontent.com/41103328/154459959-ca765b3d-0605-4e67-afaa-ccee52b7c42c.png)

**Comment by phil-davis** [comment]
> What do we do now?

@SwikritiT is there a separate issue raised about this?

**Comment by SwikritiT** [comment]
> > What do we do now?
> 
> @SwikritiT is there a separate issue raised about this?

There's this issue https://github.com/owncloud/web/issues/6419 for being able to create a public link for `Shares` folder I couldn't find for sharing with people

**Comment by phil-davis** [comment]
> @phil-davis Shall I create a separate issue or the public link one will do? They seem to be related.

The comment you made in #6419 looks good. That will be enough.

**Comment by phil-davis** [comment]
closing this issue - it can be followed-up in #6419 

If someone notices these fails again in CI, then please post the details in #6419
