### ISSUE TITLE
webUISharingPublicManagement/shareByPublicLink.feature:90 failed in nightly

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6482]
https://drone.owncloud.com/owncloud/web/23063/66/15
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingPublicManagement/shareByPublicLink.feature:90
```

Plenty of output from the test!
```
  Scenario: access details dialog of public share and check the tabs displayed # features/webUISharingPublicManagement/shareByPublicLink.feature:90
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (426ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "/simple-folder" in the server
    Given user "Alice" has created file "simple-folder/lorem.txt" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 859 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 137 milliseconds.
√ Element <#files-view> was visible after 860 milliseconds.
    When the user creates a new public link for folder "simple-folder" using the webUI with
      │ role │ Editor │
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:52:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:28)
       at Proxy.openPublicLinkDialog (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:33:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:20:52)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:252:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openPublicLinkDialog (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:33:7)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:20:5)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
       at Proxy.openPublicLinkDialog (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:33:7)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:20:5)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 19 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 15 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.activatePanel (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:80:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openPublicLinkDialog (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:34:14)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:20:5)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-links-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 22 milliseconds.
√ Element <#files-file-link-add> was visible after 45 milliseconds.
√ Element <#oc-files-file-link-create> was visible after 49 milliseconds.
√ Element <//div[contains(@class, "files-file-link-role-button-wrapper")]//span[.="Editor"]> was visible after 39 milliseconds.
√ Element <#oc-files-file-link-create> was visible after 24 milliseconds.
√ Element <#oc-files-file-link-create> was not present after 10 milliseconds.
    And the public uses the webUI to access the last public link created by user "Alice"
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 313 milliseconds.
    And the user opens the sidebar for file "lorem.txt" on the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.isSideBarOpenForResource (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:57:18)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:11)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"85fb5102c6caefab8bae50da95e9e4d7","status":0,"value":[]}
       at Proxy.isSideBarOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 19 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 19 milliseconds.
waiting for 500ms ...
    Then the following panels should be visible in the details dialog on the webUI
      │ name     │
      │ versions │
      │ links    │
      │ people   │
    ✖ failed
      Error: versions,links,people panels was expected to be visible but not found.
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:883:13)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
saving screenshot of failed test
```

**Comment by phil-davis** [comment]
But web CI is currently running against some older version of oCIS. PR #6474 is currently bumping the oCIS commit id - so let's see if that somehow helps.
