### ISSUE TITLE
Acceptance test `webUITrashbinFilesFolders/trashbinFilesFolders.feature:23` is failing in XGAPortrait

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6594]
```
Scenario: Delete files & folders one by one and check that they are all in the trashbin
✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem-big.txt" to "lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "new-lorem.txt" to "textfile0.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "testavatar.png" to "testimage.png" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "sample,1.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "strängé filename (duplicate #2 &).txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "Folder,With,Comma" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "strängé नेपाली folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem.txt" to "simple-folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem.txt" to "strängé नेपाली folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ When the user deletes the following elements using the webUI # stepDefinitions/filesContext.js:174
       | name                                  |
       | simple-folder                         |
       | lorem.txt                             |
       | strängé नेपाली folder                 |
       | strängé filename (duplicate #2 &).txt |
   ✔ And the user browses to the trashbin page # stepDefinitions/filesContext.js:79
   ✔ Then as "Alice" folder "simple-folder" should exist in the trashbin in the server # stepDefinitions/middlewareContext.js:66
   ✔ And as "Alice" file "lorem.txt" should exist in the trashbin in the server # stepDefinitions/middlewareContext.js:66
   ✔ And as "Alice" folder "strängé नेपाली folder" should exist in the trashbin in the server # stepDefinitions/middlewareContext.js:66
   ✔ And as "Alice" file "strängé filename (duplicate #2 &).txt" should exist in the trashbin in the server # stepDefinitions/middlewareContext.js:66
   ✖ And the deleted elements should be listed on the webUI # stepDefinitions/filesContext.js:961
       AssertionError [ERR_ASSERTION]: Expected resource 'lorem.txt' to be 'present' but found 'not present'
           + expected - actual

           -false
           +true

           at assertElementsAreListed (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:912:12)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Pipelines:
https://drone.owncloud.com/owncloud/web/23591/44/20
Passed on retry: https://drone.owncloud.com/owncloud/web/23583/46/21

Hard failing on my machine

**Comment by saw-jan** [comment]
Fails frequently: https://drone.owncloud.com/owncloud/web/23655

**Comment by saw-jan** [comment]
As for the initial findings, this test started failing from this commit `9ce5a1a5ec3fdbd4d2072408748707527e4b9fe8` and I also saw that some tests were skipped on XGAPortrait with `@skipOnXGAPortraitResolution`
