### ISSUE TITLE
E2E tests are failing intermittently in OC10 and needs investigation

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6596]
https://drone.owncloud.com/owncloud/web/23656/10/17
```console
Alice shares file to Brian (attempt 1, retried) # tests/e2e/cucumber/shareFileJourney.feature:13
   ✔ Before # tests/e2e/cucumber/environment/index.ts:40
   ✔ Given the following users have been created # tests/e2e/cucumber/step_definitions/api.ts:6
       | Alice |
       | Brian |
   ✔ And the default folder for received shares has been set to "Shares" # tests/e2e/cucumber/step_definitions/api.ts:19
   ✔ And auto-accept shares has been disabled # tests/e2e/cucumber/step_definitions/api.ts:30
   ✔ When "Alice" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   ✔ And "Alice" creates the following folder # tests/e2e/cucumber/step_definitions/app.files.ts:30
       | folder_to_shared |
   ✔ And "Alice" uploads the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:43
       | resource        | to               |
       | testavatar.jpeg | folder_to_shared |
   ✖ And "Alice" shares the following resource via the quick action # tests/e2e/cucumber/step_definitions/app.files.ts:69
       | resource                         | user  | role   |
       | folder_to_shared/testavatar.jpeg | Brian | viewer |
       page.waitForSelector: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for selector ".vs--open" to be visible
       ============================================================
           at AllFilesPage.shareResource (/var/www/owncloud/web/tests/e2e/support/page/files/allFiles.ts:156:18)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/step_definitions/app.files.ts:95:7)
   - And "Brian" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
   - And "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - And "Brian" accepts the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:173
       | testavatar.jpeg |
   - And "Brian" copies the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:203
       | resource               | to       |
       | Shares/testavatar.jpeg | Personal |
   - And "Brian" downloads the following file # tests/e2e/cucumber/step_definitions/app.files.ts:141
       | resource        | from   |
       | testavatar.jpeg | Shares |
   - And "Alice" changes the shared resource recipient role for the following resources # tests/e2e/cucumber/step_definitions/app.files.ts:345
       | resource                         | user  | role   |
       | folder_to_shared/testavatar.jpeg | Brian | editor |
   - When "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - And "Brian" renames the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:189
       | resource               | as                  |
       | Shares/testavatar.jpeg | testavatar_new.jpeg |
   - And "Alice" removes the following collaborator from the share # tests/e2e/cucumber/step_definitions/app.files.ts:374
       | resource                         | user  |
       | folder_to_shared/testavatar.jpeg | Brian |
   - And "Alice" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   - When "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - Then "Brian" should not see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | Shares/testavatar_new.jpeg |
   - But "Brian" should see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | testavatar.jpeg |
   - And "Brian" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   ✔ After # tests/e2e/cucumber/environment/index.ts:94
```

https://drone.owncloud.com/owncloud/web/23654/10/17
```console
: Alice shares folder with file to Brian (attempt 1, retried) # tests/e2e/cucumber/shareFolderJourney.feature:12
   ✔ Before # tests/e2e/cucumber/environment/index.ts:40
   ✔ Given the following users have been created # tests/e2e/cucumber/step_definitions/api.ts:6
       | Alice |
       | Brian |
   ✔ And the default folder for received shares has been set to "Shares" # tests/e2e/cucumber/step_definitions/api.ts:19
   ✔ And auto-accept shares has been disabled # tests/e2e/cucumber/step_definitions/api.ts:30
   ✔ When "Alice" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
       Attachment (application/json)
       Attachment (application/json)
   ✔ And "Alice" navigates to the files page # tests/e2e/cucumber/step_definitions/app.files.ts:10
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
   ✖ And "Alice" creates the following folder # tests/e2e/cucumber/step_definitions/app.files.ts:30
       | folder_to_shared |
       page.waitForSelector: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for selector "#files-personal-table" to be visible
       ============================================================
           at AllFilesPage.createFolder (/var/www/owncloud/web/tests/e2e/support/page/files/allFiles.ts:47:16)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/step_definitions/app.files.ts:38:7)
   - And "Alice" uploads the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:43
       | resource  | to               |
       | lorem.txt | folder_to_shared |
   - Then "Alice" should see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | folder_to_shared/lorem.txt |
   - When "Alice" shares the following resource via the sidebar panel # tests/e2e/cucumber/step_definitions/app.files.ts:69
       | resource         | user  | role   |
       | folder_to_shared | Brian | editor |
   - And "Brian" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
   - And "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - And "Brian" accepts the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:173
       | folder_to_shared |
   - And "Brian" renames the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:189
       | resource                          | as            |
       | Shares/folder_to_shared/lorem.txt | lorem_new.txt |
   - And "Brian" uploads the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:43
       | resource   | to                      |
       | simple.pdf | Shares/folder_to_shared |
   - And "Brian" copies the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:203
       | resource                | to       |
       | Shares/folder_to_shared | Personal |
   - When "Alice" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - Then "Alice" should see the following resources # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | folder_to_shared/lorem_new.txt |
       | folder_to_shared/simple.pdf    |
   - When "Alice" creates a new version of the following files # tests/e2e/cucumber/step_definitions/app.files.ts:227
       | resource          | to               |
       | PARENT/simple.pdf | folder_to_shared |
   - Then "Alice" should see that the resource "folder_to_shared/simple.pdf" has 1 version # tests/e2e/cucumber/step_definitions/app.files.ts:286
   - When "Brian" restores old version of the following files # tests/e2e/cucumber/step_definitions/app.files.ts:300
       | resource   | to                      |
       | simple.pdf | Shares/folder_to_shared |
   - Then "Brian" should see that the version of resource "simple.pdf" has been restored # tests/e2e/cucumber/step_definitions/app.files.ts:323
   - When "Alice" deletes the following resources # tests/e2e/cucumber/step_definitions/app.files.ts:332
       | folder_to_shared/lorem_new.txt |
       | folder_to_shared               |
   - And "Alice" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   - And "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - Then "Brian" should not see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | Shares/folder_to_shared |
   - And "Brian" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   ✔ After # tests/e2e/cucumber/environment/index.ts:94
```

https://drone.owncloud.com/owncloud/web/23652/8/17

```console
Alice shares folder with file to Brian (attempt 1, retried) # tests/e2e/cucumber/shareFolderJourney.feature:12
   ✔ Before # tests/e2e/cucumber/environment/index.ts:40
   ✔ Given the following users have been created # tests/e2e/cucumber/step_definitions/api.ts:6
       | Alice |
       | Brian |
   ✔ And the default folder for received shares has been set to "Shares" # tests/e2e/cucumber/step_definitions/api.ts:19
   ✔ And auto-accept shares has been disabled # tests/e2e/cucumber/step_definitions/api.ts:30
   ✔ When "Alice" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
       Attachment (application/json)
       Attachment (application/json)
   ✔ And "Alice" navigates to the files page # tests/e2e/cucumber/step_definitions/app.files.ts:10
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
       Attachment (application/json)
   ✖ And "Alice" creates the following folder # tests/e2e/cucumber/step_definitions/app.files.ts:30
       | folder_to_shared |
       page.waitForSelector: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for selector "#files-personal-table" to be visible
       ============================================================
           at AllFilesPage.createFolder (/var/www/owncloud/web/tests/e2e/support/page/files/allFiles.ts:47:16)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/step_definitions/app.files.ts:38:7)
   - And "Alice" uploads the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:43
       | resource  | to               |
       | lorem.txt | folder_to_shared |
   - Then "Alice" should see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | folder_to_shared/lorem.txt |
   - When "Alice" shares the following resource via the sidebar panel # tests/e2e/cucumber/step_definitions/app.files.ts:69
       | resource         | user  | role   |
       | folder_to_shared | Brian | editor |
   - And "Brian" logs in # tests/e2e/cucumber/step_definitions/session.ts:24
   - And "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - And "Brian" accepts the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:173
       | folder_to_shared |
   - And "Brian" renames the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:189
       | resource                          | as            |
       | Shares/folder_to_shared/lorem.txt | lorem_new.txt |
   - And "Brian" uploads the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:43
       | resource   | to                      |
       | simple.pdf | Shares/folder_to_shared |
   - And "Brian" copies the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:203
       | resource                | to       |
       | Shares/folder_to_shared | Personal |
   - When "Alice" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - Then "Alice" should see the following resources # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | folder_to_shared/lorem_new.txt |
       | folder_to_shared/simple.pdf    |
   - When "Alice" creates a new version of the following files # tests/e2e/cucumber/step_definitions/app.files.ts:227
       | resource          | to               |
       | PARENT/simple.pdf | folder_to_shared |
   - Then "Alice" should see that the resource "folder_to_shared/simple.pdf" has 1 version # tests/e2e/cucumber/step_definitions/app.files.ts:286
   - When "Brian" restores old version of the following files # tests/e2e/cucumber/step_definitions/app.files.ts:300
       | resource   | to                      |
       | simple.pdf | Shares/folder_to_shared |
   - Then "Brian" should see that the version of resource "simple.pdf" has been restored # tests/e2e/cucumber/step_definitions/app.files.ts:323
   - When "Alice" deletes the following resources # tests/e2e/cucumber/step_definitions/app.files.ts:332
       | folder_to_shared/lorem_new.txt |
       | folder_to_shared               |
   - And "Alice" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   - And "Brian" opens the "files" app # tests/e2e/cucumber/step_definitions/runtime.ts:5
   - Then "Brian" should not see the following resource # tests/e2e/cucumber/step_definitions/app.files.ts:263
       | Shares/folder_to_shared |
   - And "Brian" logs out # tests/e2e/cucumber/step_definitions/session.ts:35
   ✔ After # tests/e2e/cucumber/environment/index.ts:94
```

**Comment by kiranparajuli589** [comment]
checked against the latest master, the test is failing
https://github.com/owncloud/web/pull/6597

**Comment by saw-jan** [comment]
@amrita-shrestha, some issues are with `locator.fill("some input")`

**Comment by amrita-shrestha** [comment]
> @amrita-shrestha, some issues are with `locator.fill("some input")`. the typed text gets cleared

**Comment by fschade** [comment]
please do not spent more time debugging the issue, will be fixed as part of #6603

**Comment by saw-jan** [comment]
e2e tests failing frequently on oC10
https://drone.owncloud.com/owncloud/web/23786
https://drone.owncloud.com/owncloud/web/23784

Mostly in download steps:
```
   ✔ And "Brian" navigates to the personal space page # tests/e2e/cucumber/steps/app-files/page/spaces/personal.ts:5
   ✖ And "Brian" downloads the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:37
       | resource | from             |
       | data.zip | Shares/meal plan |
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at clickResource (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:18:12)
           at downloadResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:103:24)
           at Resource.download (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:43:46)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/app-files/resource.ts:56:46)
```

**Comment by amrita-shrestha** [comment]
Fix in this PR https://github.com/owncloud/web/pull/6617
