### ISSUE TITLE
[QA] Acceptance test `webUITrashbinDelete/trashbinDelete.feature:143` failed nightly

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6706]
Nightly run: https://drone.owncloud.com/owncloud/web/24305/67/15

```feature

  @files_trashbin-app-required @issue-ocis-web-118 @issue-product-188 @issue-4582
  Scenario: Select all files and delete from trashbin in a batch # features/webUITrashbinDelete/trashbinDelete.feature:143
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (435ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has created file "lorem.txt" in the server
    Given user "Alice" has created file "lorem-big.txt" in the server
    And user "Alice" has created file "sample,1.txt" in the server
    And user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has created folder "Folder,With,Comma" in the server
    And user "Alice" has created file "simple-folder/lorem.txt" in the server
    And user "Alice" has created file "simple-folder/lorem-big.txt" in the server
    And user "Alice" has uploaded file "data.zip" to "data.zip" in the server
    And the following files have been deleted by user "Alice" in the server
      │ name              │
      │ lorem.txt         │
      │ simple-folder     │
      │ sample,1.txt      │
      │ lorem-big.txt     │
      │ Folder,With,Comma │
      │ data.zip          │
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 1181 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 133 milliseconds.
√ Element <#files-view> was visible after 875 milliseconds.
    And the user has browsed to the trashbin page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 677 milliseconds.
    When the user marks all files for batch action using the webUI
√ Element <.files-table> was visible after 45 milliseconds.
√ Element <#resource-table-select-all> was visible after 45 milliseconds.
    And the user batch deletes the marked files using the webUI
√ Element <//button[contains(@class, "oc-files-actions-delete-")]> was visible after 40 milliseconds.
√ Element <.oc-modal> was visible after 40 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
√ Element <.oc-modal> was not present after 15 milliseconds.
    Then there should be no resources listed on the webUI
Timed out while waiting for element <.files-empty> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10020ms)
undefined    ✖ failed
      Timed out while waiting for element <.files-empty> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10020ms)
          at Proxy.waitForNoContentMessageVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:459:18)
          at World.assertNoResourcesListed (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:345:52)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
saving screenshot of failed test
```

**Comment by saw-jan** [comment]
@Talank this might be same as https://github.com/owncloud/web/issues/6707
Batch actions are working correctly with oCIS server

**Comment by saw-jan** [comment]
will be tracked in https://github.com/owncloud/web/issues/6796
closing here
