### ISSUE TITLE
[QA] Acceptance test `webUIDeleteFilesFolders/deleteFilesFolders.feature:216` failed nightly

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6707]
Nightly run: https://drone.owncloud.com/owncloud/web/24306/53/15

```feature

  @issue-4582
  Scenario: Delete multiple files at once on a public share # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:216
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (307ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 869 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 122 milliseconds.
√ Element <#files-view> was visible after 692 milliseconds.
    And the user reloads the current page of the webUI
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has created file "simple-folder/data.zip" in the server
    And user "Alice" has created file "simple-folder/lorem.txt" in the server
    And user "Alice" has created file "simple-folder/simple-empty-folder" in the server
    And the user has reloaded the current page of the webUI
    And user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (295ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 772 milliseconds.
    And the user batch deletes these files using the webUI
      │ name                │
      │ data.zip            │
      │ lorem.txt           │
      │ simple-empty-folder │
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='data.zip' or @data-test-resource-path='/data.zip')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 38 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 29 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-empty-folder' or @data-test-resource-path='/simple-empty-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 37 milliseconds.
√ Element <//button[contains(@class, "oc-files-actions-delete-")]> was visible after 33 milliseconds.
√ Element <.oc-modal> was visible after 36 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal> was not present after 12 milliseconds.
    Then as "Alice" file "simple-folder/data.zip" should not exist in the server
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: file/folder should not exist, but does
          at /usr/src/app/src/stepDefinitions/webdavContext.js:95:12
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:66:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And as "Alice" file "simple-folder/lorem.txt" should not exist in the server
    - skipped
    And as "Alice" folder "simple-folder/simple-empty-folder" should not exist in the server
    - skipped
    And the deleted elements should not be listed on the webUI
    - skipped
    And the deleted elements should not be listed on the webUI after a page reload
    - skipped
```
```feature

  @issue-4582
  Scenario: Delete multiple files at once on a public share # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:216
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (301ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 842 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 106 milliseconds.
√ Element <#files-view> was visible after 729 milliseconds.
    And the user reloads the current page of the webUI
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has created file "simple-folder/data.zip" in the server
    And user "Alice" has created file "simple-folder/lorem.txt" in the server
    And user "Alice" has created file "simple-folder/simple-empty-folder" in the server
    And the user has reloaded the current page of the webUI
    And user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (306ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 800 milliseconds.
    And the user batch deletes these files using the webUI
      │ name                │
      │ data.zip            │
      │ lorem.txt           │
      │ simple-empty-folder │
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='data.zip' or @data-test-resource-path='/data.zip')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 36 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 36 milliseconds.
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-empty-folder' or @data-test-resource-path='/simple-empty-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 32 milliseconds.
√ Element <//button[contains(@class, "oc-files-actions-delete-")]> was visible after 42 milliseconds.
√ Element <.oc-modal> was visible after 36 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
√ Element <.oc-modal> was not present after 11 milliseconds.
    Then as "Alice" file "simple-folder/data.zip" should not exist in the server
    And as "Alice" file "simple-folder/lorem.txt" should not exist in the server
    And as "Alice" folder "simple-folder/simple-empty-folder" should not exist in the server
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: file/folder should not exist, but does
          at /usr/src/app/src/stepDefinitions/webdavContext.js:95:12
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:66:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And the deleted elements should not be listed on the webUI
    - skipped
    And the deleted elements should not be listed on the webUI after a page reload
    - skipped
saving screenshot of failed test
```

**Comment by saw-jan** [comment]
Issue https://github.com/owncloud/web/issues/4582 has reappeared now with oCIS server.

**Comment by saw-jan** [comment]
Batch delete action can sometime fail in oCIS, see https://github.com/owncloud/web/issues/4582#issuecomment-1085501222
CC @kulmann @pascalwengerter

**Comment by saw-jan** [comment]
While testing manually server request looks like this on failure:

Request:
```
DELETE /remote.php/dav/files/admin/large-folder/testfile60.txt HTTP/1.1
Host: host.docker.internal:9200
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"
sec-ch-ua-mobile: ?0
Authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3ZWIiLCJleHAiOjE2NDkwNDQyMTEsImp0aSI6Ii1va20zLWR4S1pEckdQSFFGX0xKaUVra1I1VnBGVXN5IiwiaWF0IjoxNjQ5MDQzNjExLCJpc3MiOiJodHRwczovL2hvc3QuZG9ja2VyLmludGVybmFsOjkyMDAiLCJzdWIiOiJmNnF2RDdoMmE1SFJsOWl6QEVDQjJOQzBCenJfTG54ZmJrZ3BsNFZ1UzJYOXM3T25zZnpVRFBONHVOU2RfanhFZ19sV0EzNGpzdXlXYW51RnREUHRIRlEiLCJsZy50IjoiMSIsInNjcCI6InByb2ZpbGUgZW1haWwgb3BlbmlkIiwibGcuaSI6eyJkbiI6ImFkbWluIiwiaWQiOiJjbj1hZG1pbixvdT11c2VycyxkYz1vY2lzLGRjPXRlc3QiLCJ1biI6ImFkbWluIn0sImxnLnAiOiJpZGVudGlmaWVyLWxkYXAifQ.y0J3mncDowKCdqkF-v13TjakUFT0vCCgKouDvwTYoKwz8nQYxSpwwHy6MRi7WZUNcUmzwty0H1II9O7pTETBtbSY3EO6A7Sn3-OJHybj5kREUnTiuPm5EsWoQd5DRgnwQ7tWRcGLSnjUyAx3Vocgr6rfudmXDfgMun2Td14Cv9HTicuoRFUfAgds68PvmTCVKgFA8x6F7anS6n5ZfdPRWFa1Taboy7cTAbJd7V8rFBbChQuyccR6WtFLeAoUXQdgkGJJuHsIZ11eVAnFyjI3VkJR8rCSWLWRO9kr8dJrwyL3lSX-6atC6CWKOV5fqObjgLrHCYFfqGprk2elVq_RzQ
OCS-APIREQUEST: true
Accept: application/json, text/plain, */*
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
X-Request-ID: b97b8fcb-2fcd-4e0c-99a5-747fcc3a2ddf
sec-ch-ua-platform: "Linux"
Origin: https://host.docker.internal:9200
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://host.docker.internal:9200/files/spaces/personal/home/large-folder?items-per-page=100
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```
Response:
```
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location
Content-Length: 0
Content-Security-Policy: default-src 'none';
Date: Mon, 04 Apr 2022 03:44:09 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-Xss-Protection: 1; mode=block
```

**Comment by saw-jan** [comment]
Some other fails due to some error while doing batch action:
https://drone.owncloud.com/owncloud/web/24385/67/15

**Comment by saw-jan** [comment]
oCIS server log:
```bash
{
  "level":"error",
  "service":"storage",
  "pkg":"rgrpc",
  "traceid":"00000000000000000000000000000000",
  "error":"remove /var/lib/ocis/storage/users/spacetypes/personal/5d86bd6d-1991-4d8e-9e91-7ebef9e8b65e.flock: no such file or directory",
  "node":"marshaling error: json: unsupported value: encountered a cycle via *node.Node",
  "time":"2022-04-08T06:46:51Z",
  "message":"could not convert to storage space"
}
{
  "level":"error",
  "service":"storage",
  "pkg":"rgrpc",
  "traceid":"00000000000000000000000000000000",
  "error":"stat /var/lib/ocis/storage/users/spaces/dd/c2004c-0977-11eb-9d3f-a793888cd0f8/nodes/dd/c2/00/4c/-0977-11eb-9d3f-a793888cd0f8/simple.pdf: no such file or directory",
  "childpath":"/var/lib/ocis/storage/users/spaces/dd/c2004c-0977-11eb-9d3f-a793888cd0f8/nodes/dd/c2/00/4c/-0977-11eb-9d3f-a793888cd0f8/simple.pdf",
  "time":"2022-04-08T06:46:51Z",
  "message":"could not stat child entry"
}
{
  "level":"error",
  "service":"storage",
  "pkg":"rgrpc",
  "traceid":"00000000000000000000000000000000",
  "error":"remove /var/lib/ocis/storage/users/spaces/dd/c2004c-0977-11eb-9d3f-a793888cd0f8/nodes/dd/c2/00/4c/-0977-11eb-9d3f-a793888cd0f8.flock: no such file or directory",
  "status":{
    "code":15,
    "message":"error listing spaces",
    "trace":"00000000000000000000000000000000"
  },
  "filters":
    [
      {
        "type":2,
        "Term":{
          "Id":{
            "opaque_id":"ddc2004c-0977-11eb-9d3f-a793888cd0f8!ddc2004c-0977-11eb-9d3f-a793888cd0f8"
          }
        }
      }
    ],
  "time":"2022-04-08T06:46:51Z",
  "message":"failed to list storage spaces"
}
```

**Comment by saw-jan** [comment]
will be tracked in https://github.com/owncloud/web/issues/6796
closing here
