### ISSUE TITLE
`webUIUpload/upload.feature:22` failed on recent nightly build

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6741]
### Description
`webUIUpload/upload.feature:22` has failed on this nightly build:
- https://drone.owncloud.com/owncloud/web/24491/64/15

```console
@smokeTest @ocisSmokeTest
  Scenario: simple upload of a folder that does not exist before # features/webUIUpload/upload.feature:22
- Connecting to selenium on port 4444...

  Using: chrome (94.0.4606.61) on Linux platform.

ℹ Connected to selenium on port 4444 (425ms).
    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has uploaded file with content "initial content" to "lorem.txt" in the server
    And user "Alice" has uploaded file with content "initial content" to "simple-folder/lorem.txt" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 1087 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 137 milliseconds.
√ Element <#files-view> was visible after 954 milliseconds.
    Given a folder "CUSTOM" has been created with the following files in separate sub-folders in the middleware
      │ subFolder │ file          │
      │           │ lorem.txt     │
      │ sub1      │ lorem.txt     │
      │ sub1      │ new-lorem.txt │
      │ sub2/sub3 │ new-lorem.txt │
    When the user uploads folder "CUSTOM" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 41 milliseconds.
√ Element <#files-file-upload-button> was visible after 65 milliseconds.
√ Element <#files-upload-progress> was visible after 56 milliseconds.
√ Element <#files-upload-progress> was not visible after 381 milliseconds.
    Then no message should be displayed on the webUI
    And folder "CUSTOM" should be listed on the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CUSTOM' or @data-test-resource-path='/CUSTOM') and @data-test-resource-type='folder']>: 
   {"sessionId":"8cb8b56fc8833abe14cde6a7fd53681c","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:356:51)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CUSTOM' or @data-test-resource-path='/CUSTOM') and @data-test-resource-type='folder']>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
    And as "Alice" folder "CUSTOM" should exist in the server
    - skipped
    And as "Alice" file "CUSTOM/lorem.txt" should exist in the server
    - skipped
    And as "Alice" file "CUSTOM/sub1/lorem.txt" should exist in the server
    - skipped
    And as "Alice" file "CUSTOM/sub1/new-lorem.txt" should exist in the server
    - skipped
    And as "Alice" file "CUSTOM/sub2/sub3/new-lorem.txt" should exist in the server
    - skipped
    And as "Alice" the content of "CUSTOM/lorem.txt" in the server should be the same as the content of local file "CUSTOM/lorem.txt"
    - skipped
    And as "Alice" the content of "CUSTOM/sub1/lorem.txt" in the server should be the same as the content of local file "CUSTOM/sub1/lorem.txt"
    - skipped
    And as "Alice" the content of "CUSTOM/sub1/new-lorem.txt" in the server should be the same as the content of local file "CUSTOM/sub1/new-lorem.txt"
    - skipped
    And as "Alice" the content of "CUSTOM/sub2/sub3/new-lorem.txt" in the server should be the same as the content of local file "CUSTOM/sub2/sub3/new-lorem.txt"
    - skipped
```
suspicious ocis logs https://drone.owncloud.com/owncloud/web/24491/64/10
```console
2022-04-06 04:16:32 ERR ../../../../go/pkg/mod/github.com/cs3org/reva/v2@v2.1.0/pkg/storage/utils/decomposedfs/upload.go:95 > Decomposedfs: could not write checksum error="Decomposedfs: could not set extended attribute: xattr.Set /srv/app/tmp/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/f8/ac/b8/f5/-cabe-4e70-b66a-abbe0d7ac6d1 user.ocis.cs.sha1: no such file or directory" binPath=/srv/app/tmp/ocis/storage/metadata/uploads/b1a45854-11c5-4489-9772-7bf117614124 csType=sha1 hash="�S�L�](Ɯ0���0�Q\x1c� �" info={"ID":"b1a45854-11c5-4489-9772-7bf117614124","IsFinal":false,"IsPartial":false,"MetaData":{"dir":"/groups","filename":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","lockid":""},"Offset":372,"PartialUploads":null,"Size":0,"SizeIsDeferred":false,"Storage":{"BinPath":"/srv/app/tmp/ocis/storage/metadata/uploads/b1a45854-11c5-4489-9772-7bf117614124","Idp":"","LogLevel":"trace","NodeId":"f8acb8f5-cabe-4e70-b66a-abbe0d7ac6d1","NodeName":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","NodeParentId":"2693de0b-abcb-4fc4-bcde-b48fc7e1de2b","SpaceRoot":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","Type":"OCISStore","UserId":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","UserName":"","UserType":"application"}} pid=12 
```
```console
2022-04-06 04:15:09 ERR ../../../../go/pkg/mod/github.com/cs3org/reva/v2@v2.1.0/pkg/rhttp/datatx/manager/simple/simple.go:78 > Decomposedfs: could not create version error="rename /srv/app/tmp/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/f8/ac/b8/f5/-cabe-4e70-b66a-abbe0d7ac6d1 /srv/app/tmp/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/f8/ac/b8/f5/-cabe-4e70-b66a-abbe0d7ac6d1.REV.2022-04-06T04:14:38.096375519Z: no such file or directory" binPath=/srv/app/tmp/ocis/storage/metadata/uploads/d2e6c5ed-726d-41a7-96be-79be237e7b42 info={"ID":"d2e6c5ed-726d-41a7-96be-79be237e7b42","IsFinal":false,"IsPartial":false,"MetaData":{"dir":"/groups","filename":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","lockid":""},"Offset":372,"PartialUploads":null,"Size":0,"SizeIsDeferred":false,"Storage":{"BinPath":"/srv/app/tmp/ocis/storage/metadata/uploads/d2e6c5ed-726d-41a7-96be-79be237e7b42","Idp":"","LogLevel":"trace","NodeId":"f8acb8f5-cabe-4e70-b66a-abbe0d7ac6d1","NodeName":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa","NodeParentId":"2693de0b-abcb-4fc4-bcde-b48fc7e1de2b","SpaceRoot":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","Type":"OCISStore","UserId":"95cb8724-03b2-11eb-a0a6-c33ef8ef53ad","UserName":"","UserType":"application"}} pid=12 targetPath=/srv/app/tmp/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/f8/ac/b8/f5/-cabe-4e70-b66a-abbe0d7ac6d1 versionsPath=/srv/app/tmp/ocis/storage/metadata/spaces/95/cb8724-03b2-11eb-a0a6-c33ef8ef53ad/nodes/f8/ac/b8/f5/-cabe-4e70-b66a-abbe0d7ac6d1.REV.2022-04-06T04:14:38.096375519Z
```

**Comment by saw-jan** [comment]
Uploading failed (`oCIS` server):
![test-test_feature-L21](https://user-images.githubusercontent.com/52366632/162420687-aa96578e-d230-4e44-a534-173875ee39a2.png)

**Comment by saw-jan** [comment]
oCIS server log:
```json
{
    "level":"error",
    "service":"storage",
    "pkg":"rgrpc",
    "traceid":"00000000000000000000000000000000",
    "error":"remove /var/lib/ocis/storage/users/spacetypes/personal/3e7b3241-73f8-4924-a77a-04fcf3d9eb7c.flock: no such file or directory",
    "node":"marshaling error: json: unsupported value: encountered a cycle via *node.Node",
    "time":"2022-04-12T07:09:05Z",
    "message":"could not convert to storage space"
}
```

**Comment by saw-jan** [comment]
will be tracked in https://github.com/owncloud/web/issues/6796
closing here
