### ISSUE TITLE
webUITrashbinRestore/trashbinRestore.feature:46 failed on nightly and needs further investigation

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6791]
https://drone.owncloud.com/owncloud/web/24755/68/15

```console
5) Scenario: Select some trashbin files and restore them in a batch # features/webUITrashbinRestore/trashbinRestore.feature:46
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "sample,1.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "Folder,With,Comma" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ Given user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "data.zip" to "data.zip" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "lorem-big.txt" to "lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the following files have been deleted by user "Alice" in the server # stepDefinitions/middlewareContext.js:76
       | name              |
       | data.zip          |
       | lorem.txt         |
       | lorem-big.txt     |
       | simple-folder     |
       | sample,1.txt      |
       | Folder,With,Comma |
   ✔ And the user has browsed to the trashbin page # stepDefinitions/filesContext.js:74
   ✔ When the user marks these files for batch action using the webUI # stepDefinitions/filesContext.js:513
       | name              |
       | lorem.txt         |
       | lorem-big.txt     |
       | sample,1.txt      |
       | Folder,With,Comma |
   ✔ And the user batch restores the marked files using the webUI # stepDefinitions/filesContext.js:544
   ✔ And the user reloads the current page of the webUI # stepDefinitions/filesContext.js:447
   ✔ Then file "data.zip" should be listed on the webUI # stepDefinitions/filesContext.js:351
   ✔ And folder "simple-folder" should be listed on the webUI # stepDefinitions/filesContext.js:355
   ✔ But file "lorem.txt" should not be listed on the webUI # stepDefinitions/filesContext.js:370
   ✔ And file "lorem-big.txt" should not be listed on the webUI # stepDefinitions/filesContext.js:370
   ✔ And file "sample,1.txt" should not be listed on the webUI # stepDefinitions/filesContext.js:370
   ✖ And folder "Folder,With,Comma" should not be listed on the webUI # stepDefinitions/filesContext.js:381
       Error while running "ok" command: Failed [ok]: (Error: Folder 'Folder,With,Comma' is listed on the filesList) - expected "true" but got: "false" (0ms)
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:388:28
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - When the user browses to the files page # stepDefinitions/filesContext.js:22
   - And file "lorem.txt" should be listed on the webUI # stepDefinitions/filesContext.js:351
   - And file "lorem-big.txt" should be listed on the webUI # stepDefinitions/filesContext.js:351
   - And file "sample,1.txt" should be listed on the webUI # stepDefinitions/filesContext.js:351
   - And folder "Folder,With,Comma" should be listed on the webUI # stepDefinitions/filesContext.js:355
   - But file "data.zip" should not be listed on the webUI # stepDefinitions/filesContext.js:370
   - And folder "simple-folder" should not be listed on the webUI # stepDefinitions/filesContext.js:381
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by SwikritiT** [comment]
Might be similar to https://github.com/owncloud/web/issues/6706 https://github.com/owncloud/web/issues/6707

**Comment by SwikritiT** [comment]
failed again : https://drone.owncloud.com/owncloud/web/24784/68/15

**Comment by saw-jan** [comment]
Will be tracked in https://github.com/owncloud/web/pull/6828
Closing here
