### ISSUE TITLE
webUITextEditor/textFile.feature:21 failed on nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6792]
Link to build: https://drone.owncloud.com/owncloud/web/24763/54/15

 ## In ocis backend
```console
Scenario: update a markdown file with new content # features/webUITextEditor/textFile.feature:21
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/generalContext.js:249
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file with content "simple markdown file" to "simple.md" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user has browsed to the personal page # stepDefinitions/filesContext.js:103
   ✔ Given the user has opened file "simple.md" in the text editor webUI # stepDefinitions/textEditorContext.js:9
   ✔ When the user inputs the content "updated content" in the text editor webUI # stepDefinitions/textEditorContext.js:20
   ✔ And the user saves the file in the text editor webUI # stepDefinitions/textEditorContext.js:28
   ✔ And the user closes the text editor using the webUI # stepDefinitions/textEditorContext.js:32
   ✖ Then as "Alice" the file "simple.md" should have the content "updated content" in the server # stepDefinitions/middlewareContext.js:66
       Error: AssertionError [ERR_ASSERTION]: File should have content "updated content", but found "simple markdown file"
           at fileShouldHaveContent (/usr/src/app/src/stepDefinitions/webdavContext.js:35:17)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at async /usr/src/app/src/app.js:66:7
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by SwikritiT** [comment]
Tried to add some pause and reload the page didn't work

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/10852/50/9
```
runsh: Total unexpected failed scenarios throughout the test run:
webUITextEditor/textFile.feature:29
```
looks like a similar problem

**Comment by SwikritiT** [comment]
The issue behind the failure: https://github.com/owncloud/web/issues/6798

**Comment by SagarGi** [comment]
Failed on today's nightly 
```
runsh: Total unexpected failed scenarios throughout the test run:
webUITextEditor/textFile.feature:21
webUITextEditor/textFile.feature:29```

https://drone.owncloud.com/owncloud/ocis/15221/69/14

**Comment by SwikritiT** [comment]
A similar failure in the recent nightly build as well https://drone.owncloud.com/owncloud/web/30214/19/18
```feature
 Scenario: append new content in a markdown file # features/webUITextEditor/textFile.feature:29
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/generalContext.js:256
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file with content "simple markdown file" to "simple.md" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✔ And the user has browsed to the personal page # stepDefinitions/filesContext.js:103
   ✔ Given the user has opened file "simple.md" in the text editor webUI # stepDefinitions/textEditorContext.js:9
   ✔ When the user appends the content " new content added" in the text editor webUI # stepDefinitions/textEditorContext.js:24
   ✔ And the user saves the file in the text editor webUI # stepDefinitions/textEditorContext.js:28
   ✔ And the user closes the text editor using the webUI # stepDefinitions/textEditorContext.js:32
   ✖ Then as "Alice" the file "simple.md" should have the content "simple markdown file new content added" in the server # stepDefinitions/middlewareContext.js:66
       Error: AssertionError [ERR_ASSERTION]: File should have content "simple markdown file new content added", but found "simple markdown file"
           at fileShouldHaveContent (/usr/src/app/src/stepDefinitions/webdavContext.js:35:17)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at async /usr/src/app/src/app.js:61:7
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:262
   ✔ After # stepDefinitions/generalContext.js:231
   ✔ After # stepDefinitions/generalContext.js:172
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80
```

**Comment by SwikritiT** [comment]
TODO: 
- [ ] check if it's the same issue as https://github.com/owncloud/web/issues/6798
- [ ] if yes close this issue and comment on https://github.com/owncloud/web/issues/6798
- [ ] if not open the new issue or solve the problem if solvable

> Note the above issue is for OCIS storage and the test failure in nightly is in oc10

**Comment by SagarGi** [comment]
> TODO:
> 
> * [ ]  check if it's the same issue as [Textarea in markdown text editor gets disable sometimes in OCIS #6798](https://github.com/owncloud/web/issues/6798)
> * [ ]  if yes close this issue and comment on [Textarea in markdown text editor gets disable sometimes in OCIS #6798](https://github.com/owncloud/web/issues/6798)
> * [ ]  if not open the new issue or solve the problem if solvable
> 
> > Note the above issue is for OCIS storage and the test failure in nightly is in oc10

Pass on locally and the same issue is hard to reproduce. I have debugged it in CI with multiple scenarios  https://github.com/owncloud/web/pull/8044

**Comment by SwikritiT** [comment]
> > TODO:
> > 
> > * [ ]   check if it's the same issue as [Textarea in markdown text editor gets disable sometimes in OCIS #6798](https://github.com/owncloud/web/issues/6798)
> > * [ ]   if yes close this issue and comment on [Textarea in markdown text editor gets disable sometimes in OCIS #6798](https://github.com/owncloud/web/issues/6798)
> > * [ ]   if not open the new issue or solve the problem if solvable
> > 
> > > Note the above issue is for OCIS storage and the test failure in nightly is in oc10
> 
> Pass on locally and the same issue is hard to reproduce. I have debugged it in CI with multiple scenarios #8044

Let's wait a few days, and see how much the issue re-occurs.

**Comment by SagarGi** [comment]
This issue is not seen in recent nightly builds. So this can be closed for now.
