### ISSUE TITLE
webUITrashbinDelete/trashbinDelete.feature:130 failed on nightly in ocis

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6797]
Link to build : https://drone.owncloud.com/owncloud/web/24784/68/15

```console
Select all except for some files and delete from trashbin in a batch # features/webUITrashbinDelete/trashbinDelete.feature:130
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "sample,1.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created folder "Folder,With,Comma" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created file "simple-folder/lorem-big.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file "data.zip" to "data.zip" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the following files have been deleted by user "Alice" in the server # stepDefinitions/middlewareContext.js:76
       | name              |
       | lorem.txt         |
       | simple-folder     |
       | sample,1.txt      |
       | lorem-big.txt     |
       | Folder,With,Comma |
       | data.zip          |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user has browsed to the trashbin page # stepDefinitions/filesContext.js:74
   ✔ When the user marks all files for batch action using the webUI # stepDefinitions/filesContext.js:455
   ✔ And the user unmarks these files for batch action using the webUI # stepDefinitions/filesContext.js:504
       | name          |
       | lorem.txt     |
       | lorem-big.txt |
   ✔ And the user batch deletes the marked files using the webUI # stepDefinitions/filesContext.js:463
   ✔ Then file "lorem.txt" should be listed on the webUI # stepDefinitions/filesContext.js:351
   ✔ And file "lorem-big.txt" should be listed on the webUI # stepDefinitions/filesContext.js:351
   ✔ But file "data.zip" should not be listed on the webUI # stepDefinitions/filesContext.js:370
   ✖ And folder "simple-folder" should not be listed on the webUI # stepDefinitions/filesContext.js:381
       Error while running "ok" command: Failed [ok]: (Error: Folder 'simple-folder' is listed on the filesList) - expected "true" but got: "false" (0ms)
           at /var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:388:28
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by saw-jan** [comment]
will be tracked in https://github.com/owncloud/web/issues/6796
closing here
