### ISSUE TITLE
webUITextEditor/textFile.feature:84 failed in nightly [OCIS]

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6802]
Link to build: https://drone.owncloud.com/owncloud/web/24824/54/15
 ```console
Scenario: Previewing text writen in markdown format # features/webUITextEditor/textFile.feature:84
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/generalContext.js:249
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has uploaded file with content "simple markdown file" to "simple.md" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user has browsed to the personal page # stepDefinitions/filesContext.js:103
   ✔ Given the user has opened file "simple.md" in the text editor webUI # stepDefinitions/textEditorContext.js:9
   ✔ When the user inputs the content "[link]()" in the text editor webUI # stepDefinitions/textEditorContext.js:20
   ✖ Then the preview panel should have "p > a" element with text "link" # stepDefinitions/textEditorContext.js:63
       Timed out while waiting for element <#text-editor-preview > p > a> to be present for 10000 milliseconds. - expected "found" but got: "not found" (10010ms)
           at assertHasElementWithText (/var/www/owncloud/web/tests/acceptance/stepDefinitions/textEditorContext.js:96:16)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/textEditorContext.js:66:18)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by SwikritiT** [comment]
Might be similar to: https://github.com/owncloud/web/issues/6792

**Comment by SwikritiT** [comment]
this is also because the text area gets disabled and no operation can be performed on it

![disabled](https://user-images.githubusercontent.com/41103328/164603224-491c4451-dc29-4a4d-aa18-19cee2474124.png)

![textAreaDisabled](https://user-images.githubusercontent.com/41103328/164603242-06fc8446-2086-402a-9e1c-bfb8314149a1.png)

**Comment by SwikritiT** [comment]
The issue behind the failure: https://github.com/owncloud/web/issues/6798
