### ISSUE TITLE
A Bunch of `shareWithGroups` tests failed nightly

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#6877]
build: https://drone.owncloud.com/owncloud/web/25313/58/15

Failed tests:
```diff
- webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:99
- webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:81
- webUISharingInternalGroups/shareWithGroups.feature:138
- webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:63
- webUISharingInternalGroups/shareWithGroups.feature:244
- webUISharingInternalGroups/shareWithGroups.feature:19
- webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:45
- webUISharingInternalGroupsEdgeCases/shareWithGroupsEdgeCases.feature:42
- webUISharingInternalGroups/shareWithGroups.feature:100
```

All failed on the same step.
```

  Scenario: share a folder with multiple collaborators and check collaborator list order # features/webUISharingInternalGroups/shareWithGroups.feature:19
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (2046ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    ✖ failed
      Error: Error: HTTP Request Failed: Failed while creating user, Status: 401 undefined
          at Object.checkStatus (/usr/src/app/src/helpers/httpHelper.js:44:11)
          at /usr/src/app/src/helpers/graphHelper.js:27:33
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async Promise.all (index 1)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And group "grp1" has been created in the server
    - skipped
    And user "Alice" has been added to group "grp1" in the server
    - skipped
    And user "Brian" has been added to group "grp1" in the server
    - skipped
    Given group "grp11" has been created in the server
    - skipped
    And user "Carol" has created folder "simple-folder" in the server
    - skipped
    And user "Carol" has logged in using the webUI
    - skipped
    When the user shares folder "simple-folder" with group "grp11" as "Viewer" using the webUI
    - skipped
    And the user shares folder "simple-folder" with user "Brian Murphy" as "Viewer" using the webUI
    - skipped
    And the user shares folder "simple-folder" with group "grp1" as "Viewer" using the webUI
    - skipped
    And the user shares folder "simple-folder" with user "Alice Hansen" as "Viewer" using the webUI
    - skipped
    Then the current collaborators list should have order "Alice Hansen,Brian Murphy,grp1,grp11"
    - skipped
```

Might be helpful: https://github.com/owncloud/ocis/pull/3680/files

**Comment by saw-jan** [comment]
Will be resolved by https://github.com/owncloud/web/pull/6876

**Comment by individual-it** [comment]
#6876 is merged, can we close this?

CC @kulmann

**Comment by saw-jan** [comment]
Haven't seen any fails till now. Should be fine to close this

**Comment by phil-davis** [comment]
Closing - we can easily open it again if we see these failing tonight.
