### ISSUE TITLE
webUICreateFilesFolders/createFile.feature:31 is flaky

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#6949]
https://drone.owncloud.com/owncloud/ocis/11757/49/9
```
runsh: Total unexpected failed scenarios throughout the test run:
webUICreateFilesFolders/createFile.feature:31
```

```
  Scenario: redirect to subfolder after closing the text editor # features/webUICreateFilesFolders/createFile.feature:31
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (240ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created file "/lorem.txt" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 687 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 139 milliseconds.
√ Element <#files-view> was visible after 454 milliseconds.
    And the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'Personal')]> was visible after 93 milliseconds.
    Given user "Alice" has created folder "parent-folder" in the server
    When the user reloads the current page of the webUI
    And the user opens folder "parent-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='parent-folder' or @data-test-resource-path='/parent-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 27 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 93 milliseconds.
    Then there should be no resources listed on the webUI
√ Element <.files-empty> was visible after 18 milliseconds.
    When the user creates a markdown file with the name "sample.md" using the webUI
√ Element <#new-file-menu-btn:enabled> was visible after 21 milliseconds.
√ Element <#new-file-menu-drop .new-file-btn-md> was visible after 34 milliseconds.
√ Element <.oc-modal> was visible after 24 milliseconds.
√ Element <.oc-modal> was not present after 8 milliseconds.
    And the user closes the text editor using the webUI
√ Element <#text-editor-controls-close> was visible after 22 milliseconds.
    Then breadcrumb for folder "parent-folder" should be displayed on the webUI
 Error while running .isElementDisplayed() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference: element i...

 Error while running .isElementDisplayed() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference: element i...

 Error while running .isElementDisplayed() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference: element i...
...
    ✖ failed
      timeout error
      TimeoutError: timeout error
          at PeriodicPromise.getError (/srv/app/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:161:12)
          at PeriodicPromise.perform (/srv/app/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:111:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And file "sample.md" should be listed on the webUI
    - skipped
```

This scenario was previously reported as flaky in issue #6931 and was fixed by PR #6934 

Maybe we are not using that web test code change yet in oCIS?

I will check the web test commit id that is being used in oCIS first, and report back here...

**Comment by phil-davis** [comment]
web commit id in oCIS is currently only up to https://github.com/owncloud/web/commit/54495e55a46c051680e121dae8c9c4f7938746cb

I will try to bump it and see if there are other changes that make that difficult or easy.
