### ISSUE TITLE
Investigate nightly failure `webUISharingInternalGroups/shareWithGroups.feature:100`

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6978]
Build link https://drone.owncloud.com/owncloud/web/25589/26/20

```console
@issue-ocis-1943 @skipOnOCIS
  Scenario: share a folder with an internal group and a member uploads, overwrites and deletes files # features/webUISharingInternalGroups/shareWithGroups.feature:100
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (375ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    And group "grp1" has been created in the server
    And user "Alice" has been added to group "grp1" in the server
    And user "Brian" has been added to group "grp1" in the server
    Given user "Carol" has created folder "simple-folder" in the server
    And user "Carol" has created file "simple-folder/lorem.txt" in the server
    And user "Carol" has created file "simple-folder/data.zip" in the server
    And user "Carol" has logged in using the webUI
√ Element <#user> was visible after 1396 milliseconds.
√ Element <#user> was not present after 26 milliseconds.
√ Element <#files-view> was visible after 1617 milliseconds.
    When the user renames folder "simple-folder" to "new-simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 41 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 15 milliseconds.
√ Element <.oc-modal> was visible after 45 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal> was not present after 153 milliseconds.
    And the user shares folder "new-simple-folder" with group "grp1" as "Editor" using the webUI
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 20 milliseconds.
√ Element <#files-share-invite-input> was visible after 41 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 47 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 40 milliseconds.
√ Element <#new-collaborators-form-create-button> was present after 28 milliseconds.
    And user "Alice" accepts the share "Shares/new-simple-folder" offered by user "Carol" using the sharing API in the server
    And user "Brian" accepts the share "Shares/new-simple-folder" offered by user "Carol" using the sharing API in the server
    And the user re-logs in as "Alice" using the webUI
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (459ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <#user> was visible after 1313 milliseconds.
√ Element <#user> was not present after 27 milliseconds.
√ Element <#files-view> was visible after 1778 milliseconds.
    And the user opens folder "Shares" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='Shares' or @data-test-resource-path='/Shares')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 44 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 233 milliseconds.
    And the user opens folder "new-simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-simple-folder' or @data-test-resource-path='/new-simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 44 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 246 milliseconds.
    Then as "Alice" the content of "/Shares/new-simple-folder/lorem.txt" in the server should not be the same as the content of local file "lorem.txt"
    When the user uploads overwriting file "lorem.txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 44 milliseconds.
√ Element <#files-file-upload-button> was visible after 68 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal-body-actions-confirm:enabled> was visible after 42 milliseconds.
√ Element <.oc-modal> was not present after 38 milliseconds.
    Then file "lorem.txt" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 38 milliseconds.
    And as "Alice" the content of "/Shares/new-simple-folder/lorem.txt" in the server should be the same as the content of local file "lorem.txt"
    When the user uploads file "new-lorem.txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 28 milliseconds.
√ Element <#files-file-upload-button> was visible after 25 milliseconds.
√ Element <#upload-info> was visible after 42 milliseconds.
    Then as "Alice" the content of "/Shares/new-simple-folder/new-lorem.txt" in the server should be the same as the content of local file "new-lorem.txt"
    ✖ failed
      Error: Error: HTTP Request Failed: Could not download file., Status: 404 undefined
          at Object.checkStatus (/usr/src/app/src/helpers/httpHelper.js:44:11)
          at Object.exports.download (/usr/src/app/src/helpers/webdavHelper.js:41:20)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async StepDef.action (/usr/src/app/src/stepDefinitions/filesContext.js:130:18)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    When the user deletes file "data.zip" using the webUI
    - skipped
    Then file "data.zip" should not be listed on the webUI
    - skipped
    When the user re-logs in as "Brian" using the webUI
    - skipped
    And the user opens folder "Shares" using the webUI
    - skipped
    And the user opens folder "new-simple-folder" using the webUI
    - skipped
    Then as "Brian" the content of "/Shares/new-simple-folder/lorem.txt" in the server should be the same as the content of local file "lorem.txt"
    - skipped
    And as "Brian" the content of "/Shares/new-simple-folder/new-lorem.txt" in the server should be the same as the content of local file "new-lorem.txt"
    - skipped
    And file "data.zip" should not be listed on the webUI
    - skipped
    When the user re-logs in as "Carol" using the webUI
    - skipped
    And the user opens folder "new-simple-folder" using the webUI
    - skipped
    Then as "Carol" the content of "new-simple-folder/lorem.txt" in the server should be the same as the content of local file "lorem.txt"
    - skipped
    And as "Carol" the content of "new-simple-folder/new-lorem.txt" in the server should be the same as the content of local file "new-lorem.txt"
    - skipped
    And file "data.zip" should not be listed on the webUI
    - skipped

  Result: FAILED
```

**Comment by saw-jan** [comment]
@SagarGi what I think is that the test tried to assert the content before the upload succeeds.
after the `When the user uploads file "new-lorem.txt" using the webUI` step there's no `then` step to check file exists in the webUI.
Since there has been changes in upload and upload progress, I suspect that's the case here.
But it might not be the case, just giving you some hints.

**Comment by SagarGi** [comment]
Closing this issue with this PR https://github.com/owncloud/web/pull/6983 is merged.
