### ISSUE TITLE
Investigate nightly build failure: `webUIDeleteFilesFolders/deleteFilesFolders.feature:244`

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#6979]
## Description
Test failed on last nightly build.
Build link: https://drone.owncloud.com/owncloud/web/25589/54/15
```feature
  Scenario: Try to delete file and folder that used to exist but does not anymore # features/webUIDeleteFilesFolders/deleteFilesFolders.feature:244
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (306ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 864 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 328 milliseconds.
√ Element <#files-view> was visible after 550 milliseconds.
    And the user reloads the current page of the webUI
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has created file "lorem.txt" in the server
    And the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'Personal')]> was visible after 458 milliseconds.
    And the following files have been deleted by user "Alice" in the server
      │ name          │
      │ lorem.txt     │
      │ simple-folder │
    When the user deletes file "lorem.txt" using the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>: 
   {"sessionId":"b8a6dc0ef6959ebaf251fad009788533","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
       at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:7)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
          at Proxy.deleteFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:56:7)
    Then the error message with header 'Failed to delete "lorem.txt"' should be displayed on the webUI
    - skipped
    When the user clears all error message from the webUI
    - skipped
    And the user deletes folder "simple-folder" using the webUI
    - skipped
    Then the error message with header 'Failed to delete "simple-folder"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
    And folder "simple-folder" should not be listed on the webUI
    - skipped
    And as "Alice" file "lorem.txt" should not exist in the server
    - skipped
    And as "Alice" folder "simple-folder" should not exist in the server
    - skipped
```

_Originally posted by @kiranparajuli589 in https://github.com/owncloud/web/issues/6925#issuecomment-1127238692_

**Comment by saw-jan** [comment]
Sometimes the file disappear when the UI flickers (refreshes).

https://user-images.githubusercontent.com/52366632/168578191-d5cb02af-8dda-46dc-9cfb-6d0001032ff1.mp4

**Comment by pascalwengerter** [comment]
I think it should be fine to delete the `And the user has browsed to the personal page` step before trying to delete the files using the webUI (since that is most likely where the flakiness comes from?)
