### ISSUE TITLE
investigate `webUIRenameFiles/renameFiles.feature:257` failure in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#6986]
Build: https://drone.owncloud.com/owncloud/web/25635/56/15
<details>
<summary>features/webUIRenameFiles/renameFiles.feature:257</summary>

```
  Scenario: User tries to rename a file that used to exist but does not anymore # features/webUIRenameFiles/renameFiles.feature:257
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (371ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Alice" has uploaded file "data.zip" to "data.zip" in the server
    And user "Alice" has uploaded file "lorem-big.txt" to "lorem-big.txt" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 891 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 205 milliseconds.
√ Element <#files-view> was visible after 660 milliseconds.
    And the user reloads the current page of the webUI
    Given the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'Personal')]> was visible after 351 milliseconds.
    And the following files have been deleted by user "Alice" in the server
      │ name      │
      │ lorem.txt │
    When the user tries to rename file "lorem.txt" to "new-lorem.txt" using the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>: 
   {"sessionId":"bc181cb85f79b8cd068853f45b0510f6","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
       at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
          at Proxy.openFileActionsMenu (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:249:7)
          at Proxy.renameFile (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
    Then the error message with header 'Failed to rename "lorem.txt" to "new-lorem.txt"' should be displayed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "lorem.txt" should not be listed on the webUI
    - skipped
    And file "new-lorem.txt" should not be listed on the webUI
    - skipped
    And as "Alice" file "lorem.txt" should not exist in the server
    - skipped
    And as "Alice" file "new-lorem.txt" should not exist in the server
    - skipped
```
</details>

**Comment by saw-jan** [comment]
looks like it needed the same fix as done for https://github.com/owncloud/web/issues/6979

**Comment by Talank** [comment]
This test failed again today https://drone.owncloud.com/owncloud/web/25887/56/15

**Comment by saw-jan** [comment]
Some details are in https://github.com/owncloud/web/issues/6986
I will reopen that one and close this one.
