### ISSUE TITLE
Preview from share-with-others page doesn't work in oc10

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7049]
### Steps to reproduce
1. As user "Alice" upload a picture `test.jpeg`
2. Share the picture with user `Brian`
3. Go to shares -> shared with others
4. There's no option to preview the image while on ocis there is

### Expected behaviour
It should be possible to preview the image like in OCIS
![ocisPreview](https://user-images.githubusercontent.com/41103328/169975691-85c5c719-7960-4720-9f94-353639f2d55c.png)

### Actual behaviour
It's not possible to preview the image
![OC10Preview](https://user-images.githubusercontent.com/41103328/169975768-1e66a84d-f4ab-4879-9ed7-a458dd476055.png)

**Comment by pascalwengerter** [comment]
@SwikritiT could you disclose the config.json's for both backends / how you have started them? This _could_ be an issue of not having activated the mediaviewer (now 'preview') extension

**Comment by SwikritiT** [comment]
> @SwikritiT could you disclose the config.json's for both backends / how you have started them? This _could_ be an issue of not having activated the mediaviewer (now 'preview') extension

I ran both backends from docker `docker-compose up oc10` `docker-compose up ocis` . The preview is not working only in shared-with-others page in OC10, it works in other pages. The related test also fails in CI https://drone.owncloud.com/owncloud/web/25817/20/20

```feature
1) Scenario: Open jpeg file with preview app in shared-with-others page (attempt 1, retried) # features/webUIPreview/mediaPreview.feature:143
   ✔ Before # setup.js:41
   ✔ Before # setup.js:45
   ✔ Before # setup.js:49
   ✔ Before # setup.js:66
   ✔ Before # setup.js:73
   ✔ Before # setup.js:84
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Brian" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Brian" has uploaded file "testavatar.png" to "testavatar.png" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Brian" has shared file "testavatar.png" with user "Alice" with "all" permissions in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Brian" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✔ And the user browses to the shared-with-others page # stepDefinitions/filesContext.js:58
   ✔ When the user views the file "testavatar.png" in the preview app by clicking on the file name using the webUI # stepDefinitions/previewContext.js:51
   ✖ Then the file "testavatar.png" should be displayed in the preview app webUI # stepDefinitions/previewContext.js:39
       Timed out while waiting for element <//p[contains(@class, "preview-file-name") and contains(text(),"testavatar.png")]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10001ms)
           at Proxy.waitForPreviewLoaded (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/previewPage.js:16:30)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/previewContext.js:40:22)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:117
   ✔ After # setup.js:113
   ✔ After # setup.js:109
   ✔ After # setup.js:102
   ✔ After # setup.js:93
```

**Comment by pascalwengerter** [comment]
> > @SwikritiT could you disclose the config.json's for both backends / how you have started them? This _could_ be an issue of not having activated the mediaviewer (now 'preview') extension
> 
> I ran both backends from docker `docker-compose up oc10` `docker-compose up ocis` . The preview is not working only in shared-with-others page in OC10, it works in other pages. The related test also fails in CI https://drone.owncloud.com/owncloud/web/25817/20/20
> 
> ```
> 1) Scenario: Open jpeg file with preview app in shared-with-others page (attempt 1, retried) # features/webUIPreview/mediaPreview.feature:143
>    ✔ Before # setup.js:41
>    ✔ Before # setup.js:45
>    ✔ Before # setup.js:49
>    ✔ Before # setup.js:66
>    ✔ Before # setup.js:73
>    ✔ Before # setup.js:84
>    ✔ Before # stepDefinitions/filesContext.js:17
>    ✔ Before # stepDefinitions/generalContext.js:199
>    ✔ Before # stepDefinitions/generalContext.js:237
>    ✔ Before # stepDefinitions/middlewareContext.js:46
>    ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
>    ✔ Given user "Brian" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
>    ✔ And user "Brian" has uploaded file "testavatar.png" to "testavatar.png" in the server # stepDefinitions/middlewareContext.js:66
>    ✔ And user "Brian" has shared file "testavatar.png" with user "Alice" with "all" permissions in the server # stepDefinitions/middlewareContext.js:66
>    ✔ And user "Brian" has logged in using the webUI # stepDefinitions/loginContext.js:64
>    ✔ And the user browses to the shared-with-others page # stepDefinitions/filesContext.js:58
>    ✔ When the user views the file "testavatar.png" in the preview app by clicking on the file name using the webUI # stepDefinitions/previewContext.js:51
>    ✖ Then the file "testavatar.png" should be displayed in the preview app webUI # stepDefinitions/previewContext.js:39
>        Timed out while waiting for element <//p[contains(@class, "preview-file-name") and contains(text(),"testavatar.png")]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10001ms)
>            at Proxy.waitForPreviewLoaded (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/previewPage.js:16:30)
>            at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/previewContext.js:40:22)
>    ✔ After # stepDefinitions/middlewareContext.js:60
>    ✔ After # stepDefinitions/generalContext.js:255
>    ✔ After # stepDefinitions/generalContext.js:224
>    ✔ After # stepDefinitions/generalContext.js:165
>    ✔ After # setup.js:117
>    ✔ After # setup.js:113
>    ✔ After # setup.js:109
>    ✔ After # setup.js:102
>    ✔ After # setup.js:93
> ```

Thanks for the details, I'll investigate! :)

**Comment by JanAckermann** [comment]
Note this also happened to other apps like: pdf-viewer and text-editor as the mimeType was missing
