### ISSUE TITLE
Investigate webUIUpload/upload.feature:69 failure in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7106]
Following scenario failed in recent nightly build and needs investigation: https://drone.owncloud.com/owncloud/web/26111/65/15

```feature
Scenario: Upload of a folder inside a subdirectory # features/webUIUpload/upload.feature:69
    ✔ Before # setup.js:41
    ✔ Before # setup.js:45
    ✔ Before # setup.js:49
    ✔ Before # setup.js:66
    ✔ Before # setup.js:73
    ✔ Before # setup.js:84
    ✔ Before # stepDefinitions/filesContext.js:17
    ✔ Before # stepDefinitions/generalContext.js:199
    ✔ Before # stepDefinitions/generalContext.js:237
    ✔ Before # stepDefinitions/middlewareContext.js:46
    ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has uploaded file with content "initial content" to "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has uploaded file with content "initial content" to "simple-folder/lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
    ✔ Given user "Alice" has created folder "simple-empty-folder" in the server # stepDefinitions/middlewareContext.js:66
    ✔ And the user has reloaded the current page of the webUI # stepDefinitions/filesContext.js:451
    ✔ When the user browses to the folder "simple-empty-folder" on the files page # stepDefinitions/filesContext.js:1002
    ✔ And the user uploads folder "PARENT" using the webUI # stepDefinitions/filesContext.js:250
    ✔ Then no message should be displayed on the webUI # stepDefinitions/generalContext.js:120
    ✔ And folder "PARENT" should be listed on the webUI # stepDefinitions/filesContext.js:355
    ✔ When the user opens folder "PARENT" using the webUI # stepDefinitions/filesContext.js:155
    ✖ Then the following resources should be listed on the webUI # stepDefinitions/filesContext.js:949
        | entry_name |
        | parent.txt |
        | CHILD      |
        AssertionError [ERR_ASSERTION]: Expected resource 'parent.txt' to be 'present' but found 'not present'
            + expected - actual

            -false
            +true

            at assertElementsAreListed (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:917:12)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:95:5)
    - And as "Alice" folder "simple-empty-folder/PARENT" should exist in the server # stepDefinitions/middlewareContext.js:66
    - And as "Alice" file "simple-empty-folder/PARENT/parent.txt" should exist in the server # stepDefinitions/middlewareContext.js:66
    - And as "Alice" folder "simple-empty-folder/PARENT/CHILD" should exist in the server # stepDefinitions/middlewareContext.js:66
    ✔ After # stepDefinitions/middlewareContext.js:60
    ✔ After # stepDefinitions/generalContext.js:255
    ✔ After # stepDefinitions/generalContext.js:224
    ✔ After # stepDefinitions/generalContext.js:165
    ✔ After # setup.js:117
    ✔ After # setup.js:113
    ✔ After # setup.js:109
    ✔ After # setup.js:102
    ✔ After # setup.js:93

```

**Comment by SwikritiT** [comment]
Couldn't reproduce it locally and it's passing in the ci as well on  multiple runs https://drone.owncloud.com/owncloud/web/26117
https://drone.owncloud.com/owncloud/web/26116 
Closing this for now, re-open if it arises again
