### ISSUE TITLE
[acceptance-test] Sharing with multiple users/groups tests are failing intermittently

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#7154]
builds: https://drone.owncloud.com/owncloud/web/26339/64/15, https://drone.owncloud.com/owncloud/web/26340/63/15

### webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:57
```
  Scenario Outline: share a folder with multiple users with different roles and permissions # features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:17
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (224ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 721 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 265 milliseconds.
√ Element <#files-view> was visible after 481 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 29 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 26 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 11 milliseconds.
    And the user selects the following collaborators for the share as "Custom permissions" with "share" permissions:
      │ collaborator │ type │
      │ Brian Murphy │ user │
      │ Carol King   │ user │
√ Element <#files-share-invite-input> was visible after 30 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 27 milliseconds.
√ Element <#files-share-invite-input> was visible after 17 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 23 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 27 milliseconds.
    And the user shares with the selected collaborators
√ Element <#new-collaborators-form-create-button> was present after 12 milliseconds.
    And user "Brian" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    ✖ failed
      Error: Error: Could not find the share to be accepted:
          at Object.acceptShare (/usr/src/app/src/helpers/sharingHelper.js:372:13)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And user "Carol" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    - skipped
    Then custom permissions "share" should be set for user "Brian Murphy" for folder "simple-folder" on the webUI
    - skipped
    And custom permissions "share" should be set for user "Carol King" for folder "simple-folder" on the webUI
    - skipped
    And user "Brian Murphy" should be listed as "Viewer" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Carol King" should be listed as "Viewer" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Brian" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Brian                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
    And user "Carol" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Carol                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
```
<details>
<summary> ### webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:57</summary>

```
  Scenario Outline: share a folder with multiple groups with role as advanced permissions and different extra permissions # features/webUISharingFolderAdvancedPermissionsGroups/shareAdvancePermissionsGroup.feature:23
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (244ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    And these groups have been created in the server:
      │ groupname │
      │ grp1      │
      │ grp2      │
    And user "Brian" has been added to group "grp1" in the server
    And user "Carol" has been added to group "grp2" in the server
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 747 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 147 milliseconds.
√ Element <#files-view> was visible after 539 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 30 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 21 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 10 milliseconds.
    And the user selects the following collaborators for the share as "Custom permissions" with "delete, update" permissions:
      │ collaborator │ type  │
      │ grp1         │ group │
      │ grp2         │ group │
√ Element <#files-share-invite-input> was visible after 20 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 23 milliseconds.
√ Element <#files-share-invite-input> was visible after 16 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 22 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 48 milliseconds.
    And the user shares with the selected collaborators
√ Element <#new-collaborators-form-create-button> was present after 11 milliseconds.
    And user "Brian" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    ✖ failed
      Error: Error: Could not find the share to be accepted:
          at Object.acceptShare (/usr/src/app/src/helpers/sharingHelper.js:372:13)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And user "Carol" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    - skipped
    Then custom permissions "delete, update" should be set for group "grp2" for folder "simple-folder" on the webUI
    - skipped
    And custom permissions "delete, update" should be set for group "grp1" for folder "simple-folder" on the webUI
    - skipped
    And group "grp2" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And group "grp1" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Brian" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ grp1                  │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
    And user "Carol" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ grp2                  │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
```
</details>

<details>
<summary> ### webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:53</summary>

```
  Scenario Outline: share a folder with multiple users with different roles and permissions # features/webUISharingFolderPermissionMultipleUsers/shareFolderWithMultipleUsers.feature:17
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (237ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 725 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 250 milliseconds.
√ Element <#files-view> was visible after 458 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 38 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 25 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 12 milliseconds.
    And the user selects the following collaborators for the share as "Custom permissions" with "share, delete, update, create" permissions:
      │ collaborator │ type │
      │ Brian Murphy │ user │
      │ Carol King   │ user │
√ Element <#files-share-invite-input> was visible after 21 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 28 milliseconds.
√ Element <#files-share-invite-input> was visible after 22 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 24 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 29 milliseconds.
    And the user shares with the selected collaborators
√ Element <#new-collaborators-form-create-button> was present after 16 milliseconds.
    And user "Brian" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    ✖ failed
      Error: Error: Could not find the share to be accepted:
          at Object.acceptShare (/usr/src/app/src/helpers/sharingHelper.js:372:13)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And user "Carol" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    - skipped
    Then custom permissions "delete, update, create, share" should be set for user "Brian Murphy" for folder "simple-folder" on the webUI
    - skipped
    And custom permissions "delete, update, create, share" should be set for user "Carol King" for folder "simple-folder" on the webUI
    - skipped
    And user "Brian Murphy" should be listed as "Editor" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Carol King" should be listed as "Editor" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Brian" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Brian                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
    And user "Carol" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Carol                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
```
</details>

**Comment by saw-jan** [comment]
There was a very similar issue before: https://github.com/owncloud/web/issues/6721

**Comment by saw-jan** [comment]
Couldn't get a single fail locally. Let's see tomorrow's nightly.

**Comment by saw-jan** [comment]
Haven't appeared in today's nightly. Closing for now
