### ISSUE TITLE
`User Creation` failed nightly 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7184]
Build : https://drone.owncloud.com/owncloud/web/26474/56/15

```
runsh: Total unexpected failed scenarios throughout the test run:
webUILogin/openidLogin.feature:22
webUILogin/openidLogin.feature:29
webUIRenameFiles/renameFiles.feature:283
webUILogin/openidLogin.feature:44
webUIRenameFiles/renameFiles.feature:92
webUIRenameFiles/renameFiles.feature:78
webUILogin/openidLogin.feature:38
webUIRenameFiles/renameFiles.feature:167
webUIRenameFiles/renameFiles.feature:188
webUIRenameFiles/renameFiles.feature:160
webUIRenameFiles/renameFiles.feature:194
webUIRenameFiles/renameFiles.feature:269
webUIRenameFiles/renameFiles.feature:174
webUIRenameFiles/renameFiles.feature:62
webUIRenameFiles/renameFiles.feature:145
webUIRenameFiles/renameFilesInsideProblematicFolderName.feature:21
webUIRenameFiles/renameFiles.feature:141
webUIRenameFiles/renameFilesInsideProblematicFolderName.feature:22
webUIRenameFiles/renameFiles.feature:140
webUIRenameFiles/renameFilesInsideProblematicFolderName.feature:36
webUIRenameFiles/renameFiles.feature:153
webUIRenameFiles/renameFiles.feature:37
webUIRenameFiles/renameFiles.feature:39
webUIRenameFiles/renameFiles.feature:38
webUIRenameFiles/renameFiles.feature:21
webUIRenameFiles/renameFiles.feature:22
webUIRenameFiles/renameFiles.feature:23
webUIRenameFiles/renameFiles.feature:24
webUIRenameFiles/renameFiles.feature:25
webUIRenameFiles/renameFiles.feature:42
webUILogin/openidLogin.feature:15
```

```
@smokeTest @ocisSmokeTest @disablePreviews
  Scenario Outline: Rename a file # features/webUIRenameFiles/renameFiles.feature:13
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (1266ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    ✖ failed
      Error: FetchError: request to https://ocis:9200/graph/v1.0/users/Alice failed, reason: getaddrinfo ENOTFOUND ocis
          at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1491:11)
          at ClientRequest.emit (node:events:527:28)
          at TLSSocket.socketErrorListener (node:_http_client:454:9)
          at TLSSocket.emit (node:events:527:28)
          at emitErrorNT (node:internal/streams/destroy:157:8)
          at emitErrorCloseNT (node:internal/streams/destroy:122:3)
          at processTicksAndRejections (node:internal/process/task_queues:83:21)
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt" in the server
    - skipped
    And user "Alice" has uploaded file "data.zip" to "data.zip" in the server
    - skipped
    And user "Alice" has uploaded file "lorem-big.txt" to "lorem-big.txt" in the server
    - skipped
    Given user "Alice" has logged in using the webUI
    - skipped
    When the user renames file "lorem.txt" to "simple-name.txt" using the webUI
    - skipped
    Then file "simple-name.txt" should be listed on the webUI
    - skipped
    When the user reloads the current page of the webUI
    - skipped
    Then file "simple-name.txt" should be listed on the webUI
    - skipped
saving screenshot of failed test

```

**Comment by amrita-shrestha** [comment]
not reproduce currently so closing this issue
