### ISSUE TITLE
webUISharingPermissionsUsers/sharePermissionsUsers.feature failed nightly

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7203]
Build: https://drone.owncloud.com/owncloud/web/26573/62/15

`webUISharingPermissionsUsers/sharePermissionsUsers.feature:122`

```
  @issue-ocis-2260
  Scenario Outline: Change permissions of the previously shared file # features/webUISharingPermissionsUsers/sharePermissionsUsers.feature:106
- Connecting to selenium on port 4444...

  Using: chrome (94.0.4606.61) on Linux platform.

ℹ Connected to selenium on port 4444 (399ms).
    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Brian" has created folder "simple-folder" in the server
    And user "Brian" has created folder "simple-empty-folder" in the server
    And user "Brian" has created folder "simple-folder/simple-empty-folder" in the server
    And user "Brian" has uploaded file "data.zip" to "data.zip" in the server
    And user "Brian" has uploaded file "lorem.txt" to "lorem.txt" in the server
    And user "Brian" has uploaded file "lorem.txt" to "simple-folder/lorem.txt" in the server
    Given user "Brian" has shared file "lorem.txt" with user "Alice" with "read" permissions in the server
    And user "Alice" has accepted the share "Shares/lorem.txt" offered by user "Brian" in the server
    And user "Brian" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 1042 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 226 milliseconds.
√ Element <#files-view> was visible after 1020 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 58 milliseconds.
    Then custom permission "," should be set for user "Alice Hansen" for file "lorem.txt" on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 34 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 18 milliseconds.
√ Element <//span[contains(@class, "files-collaborators-collaborator-name") and contains(text(),"Alice Hansen")]/ancestor::div[contains(@class, "files-collaborators-collaborator")]//button[contains(@class, "files-recipient-role-select-btn")]> was visible after 40 milliseconds.
    When the user sets custom permission for current role of collaborator "Alice Hansen" for file "lorem.txt" to "share" using the webUI
√ Element <.files-recipient-custom-permissions-drop> was not present after 279 milliseconds.
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 12 milliseconds.
√ Element <//span[contains(@class, "files-collaborators-collaborator-name") and contains(text(),"Alice Hansen")]/ancestor::div[contains(@class, "files-collaborators-collaborator")]//button[contains(@class, "files-recipient-role-select-btn")]> was visible after 24 milliseconds.
    Then user "Alice" should have received a share with these details in the server:
      │ field       │ value             │
      │ uid_owner   │ Brian             │
      │ share_with  │ Alice             │
      │ file_target │ /Shares/lorem.txt │
      │ item_type   │ file              │
      │ permissions │ <permissions>     │
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: could not find expected share in "{
        "ocs": {
          "meta": {
            "status": "ok",
            "statuscode": 200,
            "message": "OK"
          },
          "data": [
            {
              "id": "2d31d45e-0c3f-4993-bd62-be7156373a47",
              "share_type": 0,
              "uid_owner": "Brian",
              "displayname_owner": "Brian Murphy",
              "additional_info_owner": "brian@example.org",
              "permissions": 1,
              "stime": 1656638236,
              "parent": "",
              "expiration": "",
              "token": "",
              "uid_file_owner": "Brian",
              "displayname_file_owner": "Brian Murphy",
              "additional_info_file_owner": "brian@example.org",
              "state": 0,
              "path": "/Shares/lorem.txt",
              "item_type": "file",
              "mimetype": "text/plain",
              "storage_id": "shared::/Shares/lorem.txt",
              "storage": 0,
              "item_source": "1284d238-aa92-42ce-bdc4-0b0000009157$8b6d52e3-e6c9-49af-81a4-b89e3c924ea1!0c520e3c-63b2-40ba-9b4f-02a1e9ec9ad6",
              "file_source": "1284d238-aa92-42ce-bdc4-0b0000009157$8b6d52e3-e6c9-49af-81a4-b89e3c924ea1!0c520e3c-63b2-40ba-9b4f-02a1e9ec9ad6",
              "file_parent": "",
              "file_target": "/Shares/lorem.txt",
              "share_with": "Alice",
              "share_with_user_type": 0,
              "share_with_displayname": "Alice Hansen",
              "share_with_additional_info": "alice@example.org",
              "mail_send": 0,
              "name": ""
            }
          ]
        }
      }"
          at /usr/src/app/src/helpers/sharingHelper.js:146:16
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by grgprarup** [comment]
Passed in CI https://drone.owncloud.com/owncloud/web/26611/10/16 with default retry in multiple runs and also passing in current nightly builds. So, closing for now. If this re-occurs we can open in again and look closely into it!

**Comment by SwikritiT** [comment]
> Passed in CI https://drone.owncloud.com/owncloud/web/26611/10/16 with default retry in multiple runs and also passing in current nightly builds. So, closing for now. If this re-occurs we can open in again and look closely into it!

If this cannot be reproduced now let's wait and see how `re-occuring` this issue is and if we can reproduce it and hopefully find some solution. So re-opening

**Comment by sushmita56** [comment]
Failed on today's nightly build too
Build: https://drone.owncloud.com/owncloud/web/26849/62/15

**Comment by saw-jan** [comment]
Everything seems fine from webUI:
- role has changed from `Custom permissions` to `Viewer`

![test-test_feature-L20](https://user-images.githubusercontent.com/52366632/178961210-1cbc2ead-c36f-4692-8a6e-6206b0997c76.png)
Vid.

https://user-images.githubusercontent.com/52366632/178961266-fdcae64c-63ea-43c6-b1a8-f6cf7e4f58aa.mp4
