### ISSUE TITLE
Cannot read properties after creating file in console

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7221]
After creating file in personal space -> errors appear in console:

```
vendor.js:53462 [Vue warn]: Error in nextTick: "TypeError: Cannot read properties of null (reading 'getBoundingClientRect')"

found in

---> <Anonymous>
       <Anonymous>
         <Anonymous>
           <Anonymous>
             <Root>
```
```
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at VueComponent.scrollToResource (web-app-files.js:9852:31)
    at VueComponent.<anonymous> (web-app-files.js:10016:32)
    at Array.<anonymous> (vendor.js:54826:14)
    at flushCallbacks (vendor.js:54752:16)
```

https://user-images.githubusercontent.com/84779829/177594514-efb48b93-f981-424c-8f04-f400e37cf198.mov

**Comment by JammingBen** [comment]
This error has been fixed meanwhile.
