### ISSUE TITLE
webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature while editing expiration date failed in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#7227]
Build: https://drone.owncloud.com/owncloud/web/26696/66/15
The following scenario failed in recent nightly and needs investigation 

```feature
Scenario: user changes the expiration date of an already existing public link using webUI # features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:199
   ✔ Before # stepDefinitions/generalContext.js:237
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created a public link with following settings in the server # stepDefinitions/middlewareContext.js:76
       | path       | lorem.txt   |
       | name       | Public link |
       | expireDate | 2038-10-14  |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:64
   ✖ When the user edits the public link named "Public link" of file "lorem.txt" changing expireDate to "2038 July 21" # stepDefinitions/publicLinkContext.js:122
       Timed out while waiting for element <//span[contains(@class, "vc-nav-item") and @role="button" and normalize-space(.)="2038"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10007ms)
           at Page.setExpiryDateYear (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:59:10)
           at Page.setExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:205:18)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:126:5)
   - Then the last public link share response of user "Alice" should include the following fields in the server # stepDefinitions/middlewareContext.js:76
       | expireDate | 2038-07-21 |
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:255
   ✔ After # stepDefinitions/generalContext.js:224
   ✔ After # stepDefinitions/generalContext.js:165
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80
```

**Comment by grgprarup** [comment]
Passed in CI https://drone.owncloud.com/owncloud/web/26809/10/16 with default retry in multiple runs and also passing in current nightly builds without retry. But failed here (https://drone.owncloud.com/owncloud/web/26810/10/16) in 3 out of 100 runs without retry. For now, this issue will be remained open, and if this re-occurs we will look closely into it.

**Comment by sushmita56** [comment]
Failed on today's nightly build too
Build: https://drone.owncloud.com/owncloud/web/26849/66/15

**Comment by saw-jan** [comment]
This issue can occur sometimes.
The test failed because sometimes the year popup gets closed due to which the test was not able to locate the year selector.

![test-test_feature-L9](https://user-images.githubusercontent.com/52366632/179452812-38693527-f1f1-4080-b983-2d2a706b7de2.png)

Vid:

https://user-images.githubusercontent.com/52366632/179453393-f14a0a83-7e27-4f2e-9722-47071e381217.mp4

**Comment by kiranparajuli589** [comment]
found this case again here at https://drone.owncloud.com/owncloud/web/27197/66/15

**Comment by SwikritiT** [comment]
re-occured here again:https://drone.owncloud.com/owncloud/web/27698/66/15
```console
 Scenario: user changes the expiration date of an already existing public link using webUI # features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created a public link with following settings in the server # stepDefinitions/middlewareContext.js:76
       | path       | lorem.txt   |
       | name       | Public link |
       | expireDate | 2038-10-14  |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✖ When the user edits the public link named "Public link" of file "lorem.txt" changing expireDate to "2038 July 21" # stepDefinitions/publicLinkContext.js:122
       Timed out while waiting for element <//span[contains(@class, "vc-nav-item") and @role="button" and normalize-space(.)="2038"]> to be present for 10000 milliseconds. - expected "visible" but got: "not found" (10021ms)
           at Page.isExpiryDateDisabled (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:125:10)
           at Page.setExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:194:37)
           at Proxy.changeExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js:196:68)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:126:5)
   - Then the last public link share response of user "Alice" should include the following fields in the server # stepDefinitions/middlewareContext.js:76
       | expireDate | 2038-07-21 |
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:262
   ✔ After # stepDefinitions/generalContext.js:231
   ✔ After # stepDefinitions/generalContext.js:172
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80

```

**Comment by saw-jan** [comment]
was able to reproduce.
Looks like the year picker popup gets closed sometimes for some reason (maybe due to execution speed)

SS:
![test-test_feature-L9](https://user-images.githubusercontent.com/52366632/186831392-10d9bb4f-9d6e-4a8f-96d3-c5a7d9b62f6b.png)

SR:

https://user-images.githubusercontent.com/52366632/186831572-652e6dd9-57ac-4456-ab59-2bc15d37dbfa.mp4

**Comment by saw-jan** [comment]
I see this difference between failing and passing tests:

During test execution, the `execute` js command updates the date-picker to the expected date range.

When failing, the **month is not selected** yet.
![t-failing](https://user-images.githubusercontent.com/52366632/186836718-0be81a0f-6a6c-4eb9-b222-7595973fda5a.png)

When passing, the month is set (shows as the selected month).
![t-passing](https://user-images.githubusercontent.com/52366632/186836788-203bc5dc-e677-4e84-ae60-1ed670fc2423.png)

**Comment by amrita-shrestha** [comment]
Re-occured again at same step : https://drone.owncloud.com/owncloud/web/29884/35/18

**Comment by phil-davis** [comment]
Note: It is now 16 November. Adding 15 days takes the date just into December. Maybe there is a problem with navigating a date-picker in this case.

**Comment by SagarGi** [comment]
> Note: It is now 16 November. Adding 15 days takes the date just into December. Maybe there is a problem with navigating a date-picker in this case.

i will be overtaking it since prarup is on leave.

**Comment by SagarGi** [comment]
@JammingBen i think https://github.com/owncloud/web/issues/7227#issuecomment-1316590303 issue might be due to change in state of UI an year ago and at present. I am not sure if this issue is related to scrolling the date. I will have a look for this.

**Comment by SwikritiT** [comment]
fix PR is merged https://github.com/owncloud/web/pull/7984 closing as done.
