### ISSUE TITLE
E2E test fails on deleting the resources steps

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7276]
Sometimes Failing on CI: https://drone.owncloud.com/owncloud/web/26837/10/13#:~:text=%E2%9C%96%20And%20%22Brian%22%20deletes,2024
```feature
1) Scenario: participant management # tests/e2e/cucumber/features/integrations/spaces/participantManagement.ocis.feature:465
   ✔ Before # tests/e2e/cucumber/environment/index.ts:45
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
       | Brian |
       | Carol |
   ✔ And "Admin" assigns following roles to the users # tests/e2e/cucumber/steps/api.ts:24
       | id    | role       |
       | Alice | SpaceAdmin |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/runtime/application.ts:5
   ✔ And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Alice" creates the following project spaces # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:15
       | name | id     |
       | team | team.1 |
   ✔ And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:75
       | user  | role   |
       | Brian | editor |
       | Carol | viewer |
   ✔ When "Brian" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Brian" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ And "Brian" creates the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:8
       | resource | type   |
       | parent   | folder |
   ✔ And "Brian" uploads the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:24
       | resource  | to     |
       | lorem.txt | parent |
   ✔ When "Carol" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Carol" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   ✔ And "Carol" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   ✔ Then "Carol" should see folder "parent" but should not be able to edit # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:102
   ✔ When "Alice" reloads the spaces page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:123
   ✔ And "Alice" creates a public link for the resource "parent" using the sidebar panel # tests/e2e/cucumber/steps/app-files/link.ts:6
   ✔ And "Alice" edits the public link named "Link" of resource "parent" changing role to "editor" # tests/e2e/cucumber/steps/app-files/link.ts:58
   ✔ And "Anonymous" opens the public link "Link" # tests/e2e/cucumber/steps/app-files/page/public.ts:10
   ✔ And "Anonymous" uploads the following resources in public link page # tests/e2e/cucumber/steps/app-files/page/public.ts:108
       | resource     |
       | textfile.txt |
   ✔ And "Anonymous" deletes the following resources from public link # tests/e2e/cucumber/steps/app-files/page/public.ts:130
       | resource  |
       | lorem.txt |
   ✖ And "Brian" deletes the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:113
       | resource            |
       | parent/textfile.txt |
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at deleteResource (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:330:14)
           at async Resource.delete (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:76:5)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/app-files/resource.ts:120:7)
   - And "Anonymous" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   - When "Carol" navigates to the trashbin of the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:132
   - Then "Carol" should not be able to delete following resources from the trashbin # tests/e2e/cucumber/steps/app-files/resource.ts:162
       | resource            |
       | parent/lorem.txt    |
       | parent/textfile.txt |
   - And "Carol" should not be able to restore following resources from the trashbin # tests/e2e/cucumber/steps/app-files/resource.ts:185
       | resource            |
       | parent/lorem.txt    |
       | parent/textfile.txt |
   - And "Carol" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   - When "Brian" navigates to the trashbin of the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:132
   - Then "Brian" should be able to restore following resources from the trashbin # tests/e2e/cucumber/steps/app-files/resource.ts:185
       | resource            |
       | parent/lorem.txt    |
       | parent/textfile.txt |
   - When "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   - And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:27
   - And "Alice" removes access to following users from the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:89
       | user  |
       | Brian |
   - When "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:6
   - Then "Brian" should not be able to see space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:112
   - And "Brian" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   - When "Alice" changes the roles of the following users in the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:143
       | user  | role    |
       | Carol | manager |
   - And "Alice" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ After # tests/e2e/cucumber/environment/index.ts:98
```
Most of the times it fails locally too.
```console
✔ And "Anonymous" opens the public link "Link" # tests/e2e/cucumber/steps/app-files/page/public.ts:10
   ✔ And "Anonymous" uploads the following resources in public link page # tests/e2e/cucumber/steps/app-files/page/public.ts:108
       | resource     |
       | textfile.txt |
   ✔ And "Anonymous" deletes the following resources from public link # tests/e2e/cucumber/steps/app-files/page/public.ts:130
       | resource  |
       | lorem.txt |
   ✖ And "Brian" deletes the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:113
       | resource            |
       | parent/textfile.txt |
       page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
           at deleteResource (/home/prarup/www/web/tests/e2e/support/objects/app-files/resource/actions.ts:330:14)
           at async Resource.delete (/home/prarup/www/web/tests/e2e/support/objects/app-files/resource/index.ts:76:5)
           at async World.<anonymous> (/home/prarup/www/web/tests/e2e/cucumber/steps/app-files/resource.ts:120:7)
   - And "Anonymous" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   - When "Carol" navigates to the trashbin of the project space "team.1" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:132
   - Then "Carol" should not be able to delete following resources from the trashbin # tests/e2e/cucumber/steps/app-files/resource.ts:162
       | resource            |
       | parent/lorem.txt    |
       | parent/textfile.txt |
   - And "Carol" should not be able to restore following resources from the trashbin
```
CC: @ScharfViktor @phil-davis @individual-it @SwikritiT @SagarGi

**Comment by grgprarup** [comment]
The PR https://github.com/owncloud/web/pull/7277 for this issue is merged, so closing this issue.
