### ISSUE TITLE
project.ocis.feature:3 failed in CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/web#7507]
https://drone.owncloud.com/owncloud/ocis/14792/75/9
```
Feature: spaces.personal # tests/e2e/cucumber/features/integrations/spaces/project.ocis.feature:1

  Scenario: unstructured collection of testable space interactions, # tests/e2e/cucumber/features/integrations/spaces/project.ocis.feature:3
    Given "Admin" creates following users
      │ id    │
      │ Alice │
      │ Brian │
    Then "Admin" assigns following roles to the users
      │ id    │ role       │
      │ Alice │ SpaceAdmin │
    When "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" navigates to the projects space page
    And "Alice" creates the following project spaces
      │ name │ id     │
      │ team │ team.1 │
      │ team │ team.2 │
    And "Alice" navigates to the project space "team.1"
    And "Alice" updates the space "team.1" name to "developer team"
    And "Alice" updates the space "team.1" subtitle to "developer team - subtitle"
    And "Alice" updates the space "team.1" description to "developer team - description"
    And "Alice" updates the space "team.1" quota to "50"
    And "Alice" updates the space "team.1" image to "testavatar.png"
    And "Alice" creates the following resources
      │ resource         │ type   │
      │ folderPublic     │ folder │
      │ folder_to_shared │ folder │
    And "Alice" uploads the following resources
      │ resource  │ to               │
      │ lorem.txt │ folderPublic     │
      │ lorem.txt │ folder_to_shared │
    And "Alice" creates a public link for the resource "folderPublic" using the sidebar panel
    And "Alice" renames the most recently created public link of resource "folderPublic" to "team.1"
    And "Alice" edits the public link named "team.1" of resource "folderPublic" changing role to "uploader"
    And "Alice" sets the expiration date of the public link named "team.1" of resource "folderPublic" to "+5 days"
    And "Alice" sets the password of the public link named "team.1" of resource "folderPublic" to "12345"
    When "Alice" shares the following resource using the sidebar panel
      │ resource         │ user  │ role   │
      │ folder_to_shared │ Brian │ editor │
    And "Alice" navigates to the projects space page
    And "Alice" navigates to the project space "team.2"
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for selector "[data-space-id="1284d238-aa92-42ce-bdc4-0b0000009157$b5bcac31-af7e-49bf-86ec-fda2afc6e42e"]"
      ============================================================
          at openSpace (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/actions.ts:64:56)
          at Spaces.open (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/index.ts:48:20)
          at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:33:24)
```

This scenario also mentioned in #7244 and #7288 - but the step where it failed is a bit different.

Can someone who is familiar with this have a look, and add comments in the appropriate issue, or raise a new issue or...

**Comment by SwikritiT** [comment]
@grgprarup If I'm not wrong issue: https://github.com/owncloud/web/issues/7288 explains this failure? 

Sometimes when a user navigates to the spaces then the created `space` is not displayed in the webUI so when the test tries to click it, it doesn't find it.

**Comment by phil-davis** [comment]
See #7288 - hopefully when that issue is fixed, then these sort of intermittent failures will stop happening.
Closing here.

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/14799/75/9 - happened again
