### ISSUE TITLE
[QA] [E2E] [oC10] Failed on tests/e2e/cucumber/features/integrations/reshare.feature:6

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#7566]
Failing on most PRs on the same step for e2e tests with `oC10`.

Failed step: https://drone.owncloud.com/owncloud/web/27937/11/18
```feature
And "Brian" reshares the following resource # tests/e2e/cucumber/steps/app-files/share.ts:44
       | resource         | recipient | type  | role   |
       | folder_to_shared | sales     | group | viewer |
       Error: function timed out, ensure the promise resolves within 60000 milliseconds
           at Timeout._onTimeout (/var/www/owncloud/web/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
           at listOnTimeout (internal/timers.js:557:17)
           at processTimers (internal/timers.js:500:7)
```
Failed step: https://drone.owncloud.com/owncloud/web/27950/11/18
```feature
And "Carol" reshares the following resource # tests/e2e/cucumber/steps/app-files/share.ts:44
       | resource         | recipient | type | role   |
       | folder_to_shared | Alice     | user | viewer |
       Error: function timed out, ensure the promise resolves within 60000 milliseconds
           at Timeout._onTimeout (/var/www/owncloud/web/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
           at listOnTimeout (internal/timers.js:557:17)
           at processTimers (internal/timers.js:500:7)
```
Passed on nightly with retry:
https://drone.owncloud.com/owncloud/web/27951/9/17

Complete scenario:
```console
1) Scenario: re-sharing (attempt 1, retried) # tests/e2e/cucumber/features/integrations/reshare.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:45
   ✔ Given "Admin" disables share auto accepting # tests/e2e/cucumber/steps/api.ts:53
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
       | Brian |
       | Carol |
   ✔ And "Admin" creates following group # tests/e2e/cucumber/steps/api.ts:69
       | id      |
       | sales   |
       | finance |
   ✔ And "Admin" adds user to the group # tests/e2e/cucumber/steps/api.ts:87
       | user  | group |
       | Carol | sales |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/runtime/application.ts:5
   ✔ And "Alice" navigates to the personal space page # tests/e2e/cucumber/steps/app-files/page/spaces/personal.ts:5
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/app-files/resource.ts:8
       | resource         | type   |
       | folder_to_shared | folder |
   ✔ When "Alice" shares the following resource using the sidebar panel # tests/e2e/cucumber/steps/app-files/share.ts:5
       | resource         | recipient | type | role   |
       | folder_to_shared | Brian     | user | editor |
   ✔ And "Alice" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ And "Brian" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   ✔ And "Brian" opens the "files" app # tests/e2e/cucumber/steps/runtime/application.ts:5
   ✔ And "Brian" navigates to the shared with me page # tests/e2e/cucumber/steps/app-files/page/shares/withMe.ts:5
   ✔ And "Brian" accepts the following share # tests/e2e/cucumber/steps/app-files/share.ts:76
       | name             |
       | folder_to_shared |
   ✖ And "Brian" reshares the following resource # tests/e2e/cucumber/steps/app-files/share.ts:44
       | resource         | recipient | type  | role   |
       | folder_to_shared | sales     | group | viewer |
       Error: function timed out, ensure the promise resolves within 60000 milliseconds
           at Timeout._onTimeout (/var/www/owncloud/web/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
           at listOnTimeout (internal/timers.js:557:17)
           at processTimers (internal/timers.js:500:7)
   - And "Brian" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   - And "Carol" logs in # tests/e2e/cucumber/steps/runtime/session.ts:24
   - And "Carol" opens the "files" app # tests/e2e/cucumber/steps/runtime/application.ts:5
   - And "Carol" navigates to the shared with me page # tests/e2e/cucumber/steps/app-files/page/shares/withMe.ts:5
   - And "Carol" accepts the following share # tests/e2e/cucumber/steps/app-files/share.ts:76
       | name             |
       | folder_to_shared |
   - And "Carol" reshares the following resource # tests/e2e/cucumber/steps/app-files/share.ts:44
       | resource         | recipient | type | role   |
       | folder_to_shared | Alice     | user | viewer |
   - And "Carol" logs out # tests/e2e/cucumber/steps/runtime/session.ts:37
   ✔ After # tests/e2e/cucumber/environment/index.ts:98
```
Might be related to PR https://github.com/owncloud/web/pull/7544

CC @ScharfViktor @individual-it @phil-davis

**Comment by kulmann** [comment]
The scenario is indeed flaky. I ran it multiple times locally and had it failing once now. In that test run the invite form field (where you enter the name of the sharee) was not focused. Focusing it manually didn't help though...

**Comment by ScharfViktor** [comment]
Ohh, sorry that brought flaky.  @grgprarup are you already trying to fix this? or can I assign it to me?

**Comment by kulmann** [comment]
@ScharfViktor any luck debugging this? fails quite often in CI...

**Comment by ScharfViktor** [comment]
I worked together wit @grgprarup. For my laptop, the test passes at every run, it's too hard to fix something that works.  @grgprarup could reproduce it.

problem here: `await locatorUtils.waitForEvent(nextPanel, 'transitionend')` https://github.com/owncloud/web/blob/master/tests/e2e/support/objects/app-files/utils/sidebar.ts#L53. it works differently than in "All files". need help from developers

commenting `await locatorUtils.waitForEvent(nextPanel, 'transitionend')` helps and we can do it how hot fix

**Comment by grgprarup** [comment]
Closing this issue on behalf of the PR https://github.com/owncloud/web/pull/7571.
