### ISSUE TITLE
Nightly fail on `webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature:44`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#7615]
Investigate on the failing scenarios on web.
Build : https://drone.owncloud.com/owncloud/web/28207/34/19

```console
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature:44
```

```
1) Scenario: share a folder with multiple users using role as advanced permissions role and different extra permissions # features/webUISharingPermissionToRoot/sharedFolderWithMultipleUsersAdvancedPermissions.feature:44
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:76
       | username |
       | Alice    |
       | Brian    |
       | Carol    |
   ✔ And user "Alice" has created folder "simple-folder" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✔ When the user opens the share dialog for folder "simple-folder" using the webUI # stepDefinitions/sharingContext.js:588
   ✔ And the user selects the following collaborators for the share as "Custom permissions" with "share, update, create" permissions: # stepDefinitions/sharingContext.js:371
       | collaborator | type |
       | Brian Murphy | user |
       | Carol King   | user |
   ✔ And the user shares with the selected collaborators # stepDefinitions/sharingContext.js:420
   ✔ Then custom permissions "share, update, create" should be set for user "Brian Murphy" for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:312
   ✔ And custom permissions "share, update, create" should be set for user "Carol King" for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:312
   ✔ And user "Brian Murphy" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:703
   ✖ And user "Carol King" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI # stepDefinitions/sharingContext.js:703
       Timed out while waiting for element <.share-access-details-drop> to be removed for 300 milliseconds. - expected "not found" but got: "found" (1659ms)
           at Proxy.getCollaboratorsList (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js:200:20)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And user "Brian" should have received a share with these details in the server: # stepDefinitions/middlewareContext.js:76
       | field       | value                       |
       | uid_owner   | Alice                       |
       | share_with  | Brian                       |
       | file_target | /simple-folder              |
       | item_type   | folder                      |
       | permissions | read, share, update, create |
```

**Comment by SagarGi** [comment]
This failure cannot be reproduce locally:
I tried it.
```
144 scenarios (144 passed)
1728 steps (1728 passed)
72m40.003s (executing steps: 72m36.560s)
```

**Comment by SagarGi** [comment]
unassigning myself and put in for backlog.

**Comment by amrita-shrestha** [comment]
failed at the same step could be related to issue https://github.com/owncloud/web/issues/7666 so closing this issue
