### ISSUE TITLE
webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:51 in OC10 failed in nightly and needs further investigation 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7666]
Build link: https://drone.owncloud.com/owncloud/web/28470/24/19

Failed Scenario:
```
 Scenario: share a file with multiple users with different roles and permissions # features/webUISharingFilePermissionMultipleUsers/shareFileWithMultipleUsers.feature:51
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And the administrator has set the default folder for received shares to "Shares" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And these users have been created with default attributes and without skeleton files in the server: # stepDefinitions/middlewareContext.js:76
       | username |
       | Alice    |
       | Brian    |
       | Carol    |
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✔ When the user opens the share dialog for file "lorem.txt" using the webUI # stepDefinitions/sharingContext.js:588
   ✔ And the user selects the following collaborators for the share as "Custom permissions" with "update" permissions: # stepDefinitions/sharingContext.js:371
       | collaborator | type |
       | Brian Murphy | user |
       | Carol King   | user |
   ✔ And the user shares with the selected collaborators # stepDefinitions/sharingContext.js:420
   ✔ And user "Brian" accepts the share "Shares/lorem.txt" offered by user "Alice" using the sharing API in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Carol" accepts the share "Shares/lorem.txt" offered by user "Alice" using the sharing API in the server # stepDefinitions/middlewareContext.js:66
   ✔ Then custom permissions "update" should be set for user "Brian Murphy" for file "lorem.txt" on the webUI # stepDefinitions/sharingContext.js:312
   ✔ And custom permissions "update" should be set for user "Carol King" for file "lorem.txt" on the webUI # stepDefinitions/sharingContext.js:312
   ✖ And user "Brian Murphy" should be listed as "Custom permissions" in the collaborators list for file "lorem.txt" on the webUI # stepDefinitions/sharingContext.js:703
       Timed out while waiting for element <.share-access-details-drop> to be removed for 300 milliseconds. - expected "not found" but got: "found" (305ms)
           at Proxy.getCollaboratorsList (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js:200:20)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:95:5)
   - And user "Carol King" should be listed as "Custom permissions" in the collaborators list for file "lorem.txt" on the webUI # stepDefinitions/sharingContext.js:703
   - And user "Brian" should have received a share with these details in the server: # stepDefinitions/middlewareContext.js:76
       | field       | value             |
       | uid_owner   | Alice             |
       | share_with  | Brian             |
       | file_target | /Shares/lorem.txt |
       | item_type   | file              |
       | permissions | read, update      |
   - And user "Carol" should have received a share with these details in the server: # stepDefinitions/middlewareContext.js:76
       | field       | value             |
       | uid_owner   | Alice             |
       | share_with  | Carol             |
       | file_target | /Shares/lorem.txt |
       | item_type   | file              |
       | permissions | read, update      |
```

**Comment by amrita-shrestha** [comment]
From inestigation it was found that sometime `await this.api.elementIdClick(collaboratorAvatarElId)` doesn't resolve before 
``` 
await this.waitForElementNotPresent(
          '@collaboratorAccessDetailsDrop',
          this.api.globals.waitForNegativeConditionTimeout
        )
```
that result `.share-access-details-drop` element to be visible

**Comment by saw-jan** [comment]
Similar test failure:
`webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:56`

```feature
Scenario Outline: share a folder with multiple users using role as advanced permissions role and different extra permissions # features/webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:16
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (11393ms).
  Using: chrome (104.0.5112.79) on Linux platform.

    Given the setting "shareapi_auto_accept_share" of app "core" has been set to "no" in the server
    And the administrator has set the default folder for received shares to "Shares" in the server
    And these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
      │ Carol    │
    Given user "Alice" has created folder "/simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <#user> was visible after 790 milliseconds.
√ Element <#user> was not present after 18 milliseconds.
√ Element <#files-view> was visible after 845 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 101 milliseconds.
    When the user opens the share dialog for folder "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 24 milliseconds.
waiting for 500ms ...
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 10 milliseconds.
    And the user selects the following collaborators for the share as "Custom permissions" with "share, delete, update" permissions:
      │ collaborator │ type │
      │ Brian Murphy │ user │
      │ Carol King   │ user │
√ Element <#files-share-invite-input> was visible after 25 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 29 milliseconds.
√ Element <#files-share-invite-input> was visible after 16 milliseconds.
√ Element <#new-collaborators-form .vs__dropdown-menu .files-collaborators-autocomplete-user-text> was visible after 23 milliseconds.
√ Element <#files-collaborators-role-button-new> was visible after 28 milliseconds.
    And the user shares with the selected collaborators
√ Element <#new-collaborators-form-create-button> was present after 13 milliseconds.
    And user "Brian" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    And user "Carol" accepts the share "Shares/simple-folder" offered by user "Alice" using the sharing API in the server
    Then custom permissions "share, delete, update" should be set for user "Brian Murphy" for folder "simple-folder" on the webUI
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 9 milliseconds.
√ Element <//span[contains(@class, "files-collaborators-collaborator-name") and contains(text(),"Brian Murphy")]/ancestor::li//button[contains(@class, "files-recipient-role-select-btn")]> was visible after 26 milliseconds.
    And custom permissions "share, delete, update" should be set for user "Carol King" for folder "simple-folder" on the webUI
√ Element <.files-recipient-custom-permissions-drop> was not present after 225 milliseconds.
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 9 milliseconds.
√ Element <//span[contains(@class, "files-collaborators-collaborator-name") and contains(text(),"Carol King")]/ancestor::li//button[contains(@class, "files-recipient-role-select-btn")]> was visible after 26 milliseconds.
    And user "Brian Murphy" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI
√ Element <.files-recipient-custom-permissions-drop> was not present after 252 milliseconds.
√ Element <//*[@id="sidebar-panel-sharing-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 10 milliseconds.
√ Element <#files-collaborators-list> was present after 14 milliseconds.
√ Element <.share-access-details-drop> was visible after 1011 milliseconds.
Timed out while waiting for element <.share-access-details-drop> to be removed for 300 milliseconds. - expected "not found" but got: "found" (315ms)
undefined    ✖ failed
      Timed out while waiting for element <.share-access-details-drop> to be removed for 300 milliseconds. - expected "not found" but got: "found" (315ms)
          at Proxy.getCollaboratorsList (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/SharingDialog/collaboratorsDialog.js:200:20)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
    And user "Carol King" should be listed as "Custom permissions" in the collaborators list for folder "simple-folder" on the webUI
    - skipped
    And user "Brian" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Brian                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped
    And user "Carol" should have received a share with these details in the server:
      │ field       │ value                 │
      │ uid_owner   │ Alice                 │
      │ share_with  │ Carol                 │
      │ file_target │ /Shares/simple-folder │
      │ item_type   │ folder                │
      │ permissions │ <actual-permissions>  │
    - skipped

  Result: FAILED
```
