### ISSUE TITLE
web failing to build

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#7825]
### Steps to reproduce
1. get the latest `master` of the `web` repo
2. run `yarn install`
3. run `make dist`

### Expected behaviour
build should suceed

### Actual behaviour
```
/usr/bin/yarn build

[!] SyntaxError: Unexpected identifier

SyntaxError: Unexpected identifier

    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)

    at link (internal/modules/esm/module_job.js:67:21)


make[1]: *** [Makefile.release:37: build-web] Error 1
```

See failing build at https://drone.owncloud.com/owncloud/web/29169/8/5

**Comment by kiranparajuli589** [comment]
qa-todo: it would be very helpful if we can find the real cause for this.

**Comment by kiranparajuli589** [comment]
It was due to the recent node version bump and not-rebased PRs. closing now.
