### ISSUE TITLE
[e2e-test] `smoke/upload.feature:6` test failing a lot in ci

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8189]
The following feature is failing a lot in normal PRs in CI with OC10 

```feature
 Scenario: Upload resources in personal space
  Given "Admin" creates following users
    | id    |
    | Alice |
  And "Alice" logs in
  And "Alice" opens the "files" app
  And "Alice" creates the following resources
    | resource          | type    | content             |
    | new-lorem-big.txt | txtFile | new lorem big file  |
    | lorem.txt         | txtFile | lorem file          |
    | textfile.txt      | txtFile | some random content |
  When "Alice" uploads the following resources
    | resource          | option    |
    | new-lorem-big.txt | replace   |
    | lorem.txt         | skip      |
    | textfile.txt      | keep both |
  And "Alice" creates the following resources
    | resource           | type    | content      |
    | PARENT/parent.txt  | txtFile | some text    |
    | PARENT/example.txt | txtFile | example text |
  #  currently upload folder feature is not available in playwright
  #  And "Alice" uploads the following resources
  #    | resource |
  #    | PARENT   |
  And "Alice" logs out
```
## Failure
```feature
Scenario: Upload resources in personal space (attempt 1, retried) # tests/e2e/cucumber/features/smoke/upload.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following users # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:19
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:5
   ✖ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:12
       | resource          | type    | content             |
       | new-lorem-big.txt | txtFile | new lorem big file  |
       | lorem.txt         | txtFile | lorem file          |
       | textfile.txt      | txtFile | some random content |
       page.waitForNavigation: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for navigation until "load"
       ============================================================
           at editTextDocument (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:147:29)
           at createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:93:13)
           at createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:138:5)
           at Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:13:9)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:16:9)
   - When "Alice" uploads the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource          | option    |
       | new-lorem-big.txt | replace   |
       | lorem.txt         | skip      |
       | textfile.txt      | keep both |
   - And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:12
       | resource           | type    | content      |
       | PARENT/parent.txt  | txtFile | some text    |
       | PARENT/example.txt | txtFile | example text |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:28
   ✔ After # tests/e2e/cucumber/environment/index.ts:83

```

Build links
1. https://drone.owncloud.com/owncloud/web/31188/11/16
2. https://drone.owncloud.com/owncloud/web/31187/11/16
3. https://drone.owncloud.com/owncloud/web/31140/11/16
4. https://drone.owncloud.com/owncloud/web/31108/11/16

**Comment by SwikritiT** [comment]
passing this this build: https://drone.owncloud.com/owncloud/web/31189

So seems like a flaky test. But it's still failing a lo.

**Comment by SagarGi** [comment]
i will be trying to reproduce it locally.

**Comment by SagarGi** [comment]
We also have this scenarios failing similarly:
```featureScenario: Upload resources in personal space # tests/e2e/cucumber/features/smoke/upload.feature:6
    Given "Admin" creates following users
      │ id    │
      │ Alice │
    And "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" creates the following resources
      │ resource          │ type    │ content             │
      │ new-lorem-big.txt │ txtFile │ new lorem big file  │
      │ lorem.txt         │ txtFile │ lorem file          │
      │ textfile.txt      │ txtFile │ some random content │
    When "Alice" uploads the following resources
      │ resource          │ option    │
      │ new-lorem-big.txt │ replace   │
      │ lorem.txt         │ skip      │
      │ textfile.txt      │ keep both │
    And "Alice" creates the following resources
      │ resource           │ type    │ content      │
      │ PARENT/parent.txt  │ txtFile │ some text    │
      │ PARENT/example.txt │ txtFile │ example text │
    ✖ failed
      page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"
          at createNewFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:73:14)
          at createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:134:13)
          at Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:13:9)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:16:9)
    And "Alice" logs out
    - skipped```

**Comment by SagarGi** [comment]
Findings for the above information.

**Comment by SagarGi** [comment]
A debug PR for the failed scenarios passed ran multiple times in drone.
https://drone.owncloud.com/owncloud/web/31284

**Comment by saw-jan** [comment]
Fix PR https://github.com/owncloud/web/pull/8191 has been merged. I will close it here
We can re-open anytime if it re-appears again
