### ISSUE TITLE
[acceptance-test] [oc10][ocis] Nightly failure `webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature`

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#8296]
Nightly failure on `webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11` with oc10 and OCIS
Build: https://drone.owncloud.com/owncloud/web/32014/36/18, https://drone.owncloud.com/owncloud/web/32014/67/13

```feature
Scenario: user changes the expiration date of an already existing public link using webUI # features/webUISharingPublicExpire/shareByPublicLinkExpiringLinks.feature:11
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:206
   ✔ Before # stepDefinitions/generalContext.js:244
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given user "Alice" has been created with default attributes and without skeleton files in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given user "Alice" has created file "lorem.txt" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "Alice" has created a public link with following settings in the server # stepDefinitions/middlewareContext.js:76
       | path       | lorem.txt   |
       | name       | Public link |
       | expireDate | +10         |
   ✔ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✖ When the user edits the public link named "Public link" of file "lorem.txt" changing expireDate to "+5" # stepDefinitions/publicLinkContext.js:122
       Timed out while waiting for element <//div[not(contains(@class, "is-not-in-month"))]/span[contains(@class, "vc-day-content vc-focusable") and normalize-space(.)="29" and @aria-label="Sunday, January 29, 2023"]> to be removed for 10000 milliseconds. - expected "not found" but got: "found" (10016ms)
           at Page.setExpiryDateDay (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:90:10)
           at Page.setExpirationDate (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/expirationDatePicker.js:220:10)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (node:internal/process/task_queues:96:5)
           at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/publicLinkContext.js:126:5)
   - Then user "Alice" should have a share with these details in the server: # stepDefinitions/middlewareContext.js:76
       | field      | value       |
       | share_type | public_link |
       | name       | Public link |
       | uid_owner  | Alice       |
       | expiration | +5          |
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:262
   ✔ After # stepDefinitions/generalContext.js:231
   ✔ After # stepDefinitions/generalContext.js:172
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80
```

**Comment by grgprarup** [comment]
The issue with this failure is the same as reported in https://github.com/owncloud/web/issues/7513

**Comment by grgprarup** [comment]
The test is skipped for now with PR https://github.com/owncloud/web/pull/8301, and the main issue is reported here https://github.com/owncloud/web/issues/7513, so closing this issue.
