### ISSUE TITLE
[oC10] [acceptance] Nightly failed webUITextEditor/textFile.feature:29

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#8329]
Build: 
[oC10Files5-chrome-latest](https://drone.owncloud.com/owncloud/web/32198/20/18)

```feature
Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has uploaded file with content "simple markdown file" to "simple.md" in the server
    And user "Alice" has logged in using the webUI
√ Element <#user> was visible after 598 milliseconds.
√ Element <#user> was not present after 224 milliseconds.
√ Element <#files-view> was visible after 766 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 47 milliseconds.
    And the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'All files')]> was visible after 46 milliseconds.
    Given the user has opened file "simple.md" in the text editor webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple.md' or @data-test-resource-path='/simple.md') and @data-test-resource-type='file']/parent::*> was visible after 97 milliseconds.
√ Element <#text-editor-input> was visible after 141 milliseconds.
√ Element <.oc-resource-name> was visible after 39 milliseconds.
    When the user appends the content " new content added" in the text editor webUI
√ Element <#text-editor-input> was visible after 25 milliseconds.
    And the user saves the file in the text editor webUI
√ Element <#text-editor-controls-save> was visible after 33 milliseconds.
    And the user closes the text editor using the webUI
√ Element <#app-top-bar-close> was visible after 33 milliseconds.
    Then as "Alice" the file "simple.md" should have the content "simple markdown file new content added" in the server
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: File should have content "simple markdown file new content added", but found "simple markdown file"
          at fileShouldHaveContent (/usr/src/app/src/stepDefinitions/webdavContext.js:35:17)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)

  Result: FAILED
```

**Comment by SwikritiT** [comment]
might be simialr issue in oc10? https://github.com/owncloud/web/issues/6798

**Comment by grgprarup** [comment]
Cannot reproduce locally and manually, and failure not occurring in PRs and current nightly. So let this issue remains open and investigate thoroughly if failure reoccurs.

**Comment by saw-jan** [comment]
Similar failure appeared
```feature
@disablePreviews
  Scenario: update a markdown file with new content # features/webUITextEditor/textFile.feature:21
- Connecting to selenium on port 4444...
ℹ Connected to selenium on port 4444 (5804ms).
  Using: chrome (104.0.5112.79) on Linux platform.
    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has uploaded file with content "simple markdown file" to "simple.md" in the server
    And user "Alice" has logged in using the webUI
    And the user has browsed to the personal page
    Given the user has opened file "simple.md" in the text editor webUI
    When the user inputs the content "updated content" in the text editor webUI
    And the user saves the file in the text editor webUI
    And the user closes the text editor using the webUI
    Then as "Alice" the file "simple.md" should have the content "updated content" in the server
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: File should have content "updated content", but found "simple markdown file"
          at fileShouldHaveContent (/usr/src/app/src/stepDefinitions/webdavContext.js:35:17)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /var/www/owncloud/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
  Result: FAILED
```
