### ISSUE TITLE
OIDC token refresh failing

### ISSUE THREAD

**Issue by wkloucek** [owncloud/web#8420]
### Steps to reproduce
1. Log in to https://ocis.ocis-web.daily.owncloud.works/
2. Wait some minutes
3. See screen that you have been logged out. If you click on "login again" you will be immediately logged in again 

If you watch the browser console you will see this:

![image](https://user-images.githubusercontent.com/34452982/218449543-b595501f-b9b1-4d99-9f0f-ec405573ec62.png)

### Expected behaviour

Token refresh works and indeed it does on https://ocis.ocis-traefik.daily.owncloud.works

### Actual behaviour
The "logged out" screen appears

### Environment general
Latest oCIS master with latest web

**Comment by tbsbdr** [comment]
Console Screenshot in higher resolution:
![Clipboard - February 13, 2023 12_36 PM](https://user-images.githubusercontent.com/26610733/218460330-22358c9c-8232-4543-a759-f4cafeb89179.png)

```
A » [IFrameWindow] navigate: no state found in response url
• • (oidcClient] readSigninResponseState: Error: No state in response at Pfe. readSigninResponseState (vendor-aceee24.mjs:2:96800)
at Pfe.processSigninResponse (vendor-aceee24.mis:2:97145)
at fo. signinEnd (vendor-ac6eee24.mjs:2:117839)
at fo. signin (vendor-ac6eee24.mjs:2:117349)
at async fo.signinSilent (VM242 vendor-aceee24.mjs:2:114818)
at async Ufe. tokenExpiring (VM242 vendor-aceee24.mjs:2:111289)
© > (SilentRenewService] tokenExpiring: Error from signinSilent: Error: No state in response
at Pfe. readSigninResponseState (vendor-aceee24.mis:2:96800)
at Pfe.processSigninResponse (vendor-aceee24.mis:2:97145)
at fo. signinEnd (vendor-ac6eee24.mjs:2:117839)
at fo. signin (vendor-ac6eee24.mjs:2:117349)
at async fo.signinSilent (VM242 vendor-ac6eee24.mjs:2:114818)
at async Ufe. tokenExpiring (VM242 vendor-aceee24.mjs:2:111289)
© Silent Renew Error: Error: No state in response
at Pfe. readSigninResponseState (vendor -aceee24.mjs:2:96800) at pfe.processSigninResponse (vendor-ac6eee24.mis:2:97145)
at fo. signinEnd (vendor-aceee24.mis:2:117839)
at fo. signin (vendor-aceee24.mis:2:117349)
at async fo.signinSilent (VM242 vendor-aceee24.mis:2:114818)
at async Ufe. tokenExpiring (VM242 vendor-aceee24.mjs:2:111289)
[UserManagerl removeUser: user removed from storage user unloaded...
[UserManagerl getUser: user not found in storage
© • Uncaught TypeError: Cannot read properties of null (reading 'style')
at Proxy. onResize (web-app-search-6c65a554.mis:1:5016)
A An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
```
