### ISSUE TITLE
[QA] Selector can resolve to multiple elements (with oC10 server)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#8564]
Element selector `.sidebar-panel .header__close:visible` can sometimes resolve to multiple elements with oC10 server.

builds: 
https://drone.owncloud.com/owncloud/web/33411/9/16,
https://drone.owncloud.com/owncloud/web/33412/9/16,
https://drone.owncloud.com/owncloud/web/33423/9/16
```feature
✖ And "Carol" downloads the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:30
   | resource      | from             | type   |
   | data.zip      | Shares/meal plan | file   |
   | lorem.txt     | Shares/meal plan | file   |
   | lorem-big.txt | Shares/meal plan | file   |
   | meal plan     | Shares           | folder |
   locator.click: Error: strict mode violation: locator('.sidebar-panel .header__close:visible') resolved to 2 elements:
       1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-details').getByRole('button', { name: 'Close file sidebar' })
       2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-actions').getByRole('button', { name: 'Close file sidebar' })

   =========================== logs ===========================
   waiting for locator('.sidebar-panel .header__close:visible')
     strict mode violation: locator('.sidebar-panel .header__close:visible') resolved to 2 elements:
       1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-details').getByRole('button', { name: 'Close file sidebar' })
       2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-actions').getByRole('button', { name: 'Close file sidebar' })

   ============================================================
       at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:65)
       at downloadResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:218:39)
       at Resource.download (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:26:27)
       at processDownload (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:221:21)
       at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:33:5)
- And "Carol" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
```
```feature
✖ And "Alice" downloads the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:30
   | resource            | from                                 | type   |
   | parent.txt          | groups/Kindergarten Koalas/meal plan | file   |
...

   locator.click: Error: strict mode violation: locator('.sidebar-panel .header__close:visible') resolved to 2 elements:
       1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-details').getByRole('button', { name: 'Close file sidebar' })
       2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-actions').getByRole('button', { name: 'Close file sidebar' })

   =========================== logs ===========================
   waiting for locator('.sidebar-panel .header__close:visible')
     strict mode violation: locator('.sidebar-panel .header__close:visible') resolved to 2 elements:
       1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-details').getByRole('button', { name: 'Close file sidebar' })
       2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka getByTestId('sidebar-panel-actions').getByRole('button', { name: 'Close file sidebar' })

   ============================================================
       at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:65)
       at downloadResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:218:39)
       at Resource.download (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:26:27)
       at processDownload (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:221:21)
       at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:33:5)
```

**Comment by SwikritiT** [comment]
failure in today's nightly too https://drone.owncloud.com/owncloud/web/33607/9/16

**Comment by SwikritiT** [comment]
failure in today's nightly as wee https://drone.owncloud.com/owncloud/web/33763/9/16

**Comment by SwikritiT** [comment]
seen again in today's nightly https://drone.owncloud.com/owncloud/web/33959/9/16

**Comment by JammingBen** [comment]
I have this error in my PRs on a regular basis. Maybe we could add `first()` to the selector (at least until a proper solution is found)?

**Comment by grgprarup** [comment]
I tried with `first()`, but it still flakyness occurs. 
```
And "Carol" downloads the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:30
       | resource      | from             | type   |
       | data.zip      | Shares/meal plan | file   |
       | lorem.txt     | Shares/meal plan | file   |
       | lorem-big.txt | Shares/meal plan | file   |
       | meal plan     | Shares           | folder |
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('.sidebar-panel .header__close:visible').first()
         locator resolved to visible <button type="button" aria-label="Close file sidebar" cl…>…</button>
       attempting click action
         waiting for element to be visible, enabled and stable
           element is not stable - waiting...
           element is not visible - waiting...
       ============================================================
           at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:73)
           at downloadResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:218:39)
           at Resource.download (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:26:27)
           at processDownload (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:221:21)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:33:5)
 ```
 https://drone.owncloud.com/owncloud/web/34148/10/16

**Comment by grgprarup** [comment]
Here is the fix PR https://github.com/owncloud/web/pull/8635
@JammingBen @JanAckermann @kulmann
