### ISSUE TITLE
[QA] e2e test failure in nightly with ocis

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8627]
The following test failed at nightly and needs investigation 
build link: https://drone.owncloud.com/owncloud/web/33718/10/12
```feature
 Scenario: Copy and move resources in personal space # tests/e2e/cucumber/features/smoke/copyMove.feature:6
    Given "Admin" creates following users
      │ id    │
      │ Alice │
    And "Alice" creates the following folders in personal space using API
      │ name        │
      │ PARENTCopy1 │
      │ PARENTCopy2 │
      │ PARENTMove  │
      │ PARENTCopy3 │
    And "Alice" creates the following files into personal space using API
      │ pathToFile              │ content                             │
      │ PARENTCopy3/example.txt │ example text                        │
      │ KeyboardExample.txt     │ copy with the help of keyboard      │
      │ dragDrop.txt            │ copy with the help of drag-drop     │
      │ sidebar.txt             │ copy with the help of sidebar panel │
    And "Alice" logs in
    And "Alice" opens the "files" app
    When "Alice" copies the following resource using sidebar-panel
      │ resource    │ to          │
      │ sidebar.txt │ PARENTCopy2 │
    And "Alice" copies the following resource using dropdown-menu
      │ resource                │ to          │
      │ PARENTCopy3/example.txt │ PARENTCopy1 │
    And "Alice" copies the following resource using keyboard
      │ resource            │ to          │
      │ KeyboardExample.txt │ PARENTCopy3 │
    And "Alice" moves the following resource using drag-drop
      │ resource     │ to          │
      │ dragDrop.txt │ PARENTCopy2 │
    ✖ failed
      page.waitForSelector: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for locator('[data-test-resource-name="dragDrop.txt"]') to be visible
      ============================================================
          at /var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/utils.ts:30:48
          at waitForResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/utils.ts:30:29)
          at moveOrCopyResource (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:324:48)
          at Resource.move (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:47:9)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:51:9)
    And "Alice" moves the following resource using dropdown-menu
      │ resource                │ to         │
      │ PARENTCopy1/example.txt │ PARENTMove │
    - skipped
    And "Alice" moves the following resource using keyboard
      │ resource    │ to         │
      │ PARENTCopy2 │ PARENTMove │
    - skipped
    And "Alice" moves the following resource using sidebar-panel
      │ resource    │ to         │
      │ PARENTCopy3 │ PARENTMove │
    - skipped
    And "Alice" logs out
    - skipped
```

**Comment by ScharfViktor** [comment]
closed as complited #8634
