### ISSUE TITLE
[QA][OCIS]e2e test failing in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8902]
The following test is failing on CI
```feature
Scenario: space members can be invited with an expiration date (attempt 1, retried) # tests/e2e/cucumber/features/smoke/spaces/memberExpiry.ocis.feature:4
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
       | Brian |
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:24
       | id    | role        |
       | Alice | Space Admin |
   ✔ And "Alice" creates the following project space using API # tests/e2e/cucumber/steps/api.ts:125
       | name | id     |
       | team | team.1 |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✔ And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   ✔ And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   ✔ And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/ui/spaces.ts:54
       | user  | role   | kind |
       | Brian | editor | user |
   ✖ And "Alice" sets the expiration date of the member "Brian" of the project space to "+5 days" # tests/e2e/cucumber/steps/ui/spaces.ts:132
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('.vc-day.id-2023-04-30').first()
         locator resolved to visible <div class="vc-day id-2023-04-30 day-30 day-from-end-…>…</div>
       attempting click action
         waiting for element to be visible, enabled and stable
           element is not stable - waiting...
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #1
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #2
         waiting 20ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #3
         waiting 100ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #4
         waiting 100ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #5
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #6
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #7
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #8
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #9
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #10
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #11
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #12
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #13
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #14
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #15
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #16
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #17
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #18
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #19
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #20
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #21
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #22
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #23
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #24
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #25
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #26
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #27
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #28
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #29
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #30
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #31
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #32
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #33
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #34
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #35
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #36
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #37
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #38
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #39
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #40
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #41
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #42
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #43
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #44
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #45
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #46
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #47
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #48
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #49
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #50
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #51
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #52
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #53
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #54
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #55
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #56
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #57
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #58
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #59
         waiting 500ms
         waiting for element to be visible, enabled and stable
         element is visible, enabled and stable
         scrolling into view if needed
         done scrolling
         performing click action
         <span tabindex="-1" role="button" aria-disabled="true"…>23</span> from <div class="vc-day id-2023-04-23 day-23 day-from-end-…>…</div> subtree intercepts pointer events
       retrying click action, attempt #60
         waiting 500ms
       ============================================================
           at Function.setExpirationDateForCollaborator (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:172:14)
           at addExpirationDateToMember (/var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/actions.ts:199:5)
           at Spaces.addExpirationDate (/var/www/owncloud/web/tests/e2e/support/objects/app-files/spaces/index.ts:76:9)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/spaces.ts:136:5)
   - When "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Brian" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Alice" removes the expiration date of the member "Brian" of the project space # tests/e2e/cucumber/steps/ui/spaces.ts:138
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:83
```

Build link: https://drone.owncloud.com/owncloud/web/35092/10/12

**Comment by SwikritiT** [comment]
This error is in both ocis and web repo 
https://drone.owncloud.com/owncloud/ocis/21728/87/9

**Comment by SwikritiT** [comment]
This looks like a bug in the calender.

**Comment by SwikritiT** [comment]
It is because of the same issue as https://github.com/owncloud/web/issues/7513
https://user-images.githubusercontent.com/41103328/234180249-5fcce143-5509-4afb-a4f9-8e95a9e72212.mov
