### ISSUE TITLE
[ocis] features/webUISharingPublicBasic/publicLinkCreate.feature:165 test is failing in ocis

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8929]
The following Nightwatch test is failing in ocis CI a lot and needs further investigation
```feature
@public_link_share-feature-required
  Scenario: User can create a public link via quick action # features/webUISharingPublicBasic/publicLinkCreate.feature:165
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (8399ms).
  Using: chrome (104.0.5112.79) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 334 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 189 milliseconds.
√ Element <#files-view> was visible after 720 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 29 milliseconds.
    When the user creates a public link via quick action for resource "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 28 milliseconds.
waiting for 500ms ...
    Then user "Alice" should have a share with these details in the server:
      │ field       │ value          │
      │ share_type  │ public_link    │
      │ uid_owner   │ Alice          │
      │ permissions │ read           │
      │ path        │ /simple-folder │
      │ name        │ Link           │
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: could not find expected share in "{
        "ocs": {
          "meta": {
            "status": "ok",
            "statuscode": 200,
            "message": "OK"
          },
          "data": [
            {
              "id": "tizIHEwKpjeYgss",
              "share_type": 3,
              "uid_owner": "Alice",
              "displayname_owner": "Alice Hansen",
              "additional_info_owner": "alice@example.org",
              "permissions": 1,
              "stime": 1682567276,
              "parent": "",
              "expiration": "",
              "token": "lrCmVsRqwDMCEzA",
              "uid_file_owner": "Alice",
              "displayname_file_owner": "Alice Hansen",
              "additional_info_file_owner": "alice@example.org",
              "state": 0,
              "path": "/simple-folder",
              "item_type": "folder",
              "mimetype": "httpd/unix-directory",
              "storage_id": "shared::/simple-folder",
              "storage": 0,
              "item_source": "55b9740b-f540-42e0-beb2-52f434d726e8$7bf63a5c-32a4-4ef6-ba32-7d6a006c941f!baa63091-3712-4a85-af1e-3d2815bd054d",
              "file_source": "55b9740b-f540-42e0-beb2-52f434d726e8$7bf63a5c-32a4-4ef6-ba32-7d6a006c941f!baa63091-3712-4a85-af1e-3d2815bd054d",
              "file_parent": "55b9740b-f540-42e0-beb2-52f434d726e8$7bf63a5c-32a4-4ef6-ba32-7d6a006c941f!7bf63a5c-32a4-4ef6-ba32-7d6a006c941f",
              "file_target": "/simple-folder",
              "share_with_user_type": 0,
              "share_with_additional_info": "",
              "mail_send": 0,
              "name": "Quicklink",
              "url": "https://ocis-server:9200/s/lrCmVsRqwDMCEzA",
              "quicklink": true
            }
          ]
        }
      }"
          at /usr/src/app/src/helpers/sharingHelper.js:146:16
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:61:7
          at /drone/src/webTestRunner/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
    And the following success message should be displayed on the webUI
      """
      The link has been copied to your clipboard.
      """
```

Build link: https://drone.owncloud.com/owncloud/ocis/21813/80/13

**Comment by SwikritiT** [comment]
The wording was changed by this PR https://github.com/owncloud/web/pull/8898/files#diff-ff7e6abf8fc8a18e4bb375ae59dad60a97b2a317e9fe8c7c17561a5c04881d5e

**Comment by saw-jan** [comment]
Looks like this may not be the issue. Passes with latest ocis and web

**Comment by saw-jan** [comment]
Ahh, now it looks we did the web bump in https://github.com/owncloud/ocis/pull/6157 without an rc release. Due to this, the test code is latest but the required src code is not present in ocis-web.
CC @ScharfViktor

**Comment by ScharfViktor** [comment]
> Ahh, now it looks we did the web bump in [owncloud/ocis#6157](https://github.com/owncloud/ocis/pull/6157) without an rc release. Due to this, the test code is latest but the required src code (from #8898) isn't present in ocis-web. CC @ScharfViktor

https://github.com/owncloud/web/pull/8943

**Comment by ScharfViktor** [comment]
green again https://drone.owncloud.com/owncloud/ocis/21873/80/13
