### ISSUE TITLE
e2e tests related to public link role failed in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8930]
Tests related to public link role is failing in CI and needs further investigation.
Build link: https://drone.owncloud.com/owncloud/web/35222/9/16

```feature
Feature: reshare # tests/e2e/cucumber/features/smoke/reshare.feature:1

  Scenario: re-sharing # tests/e2e/cucumber/features/smoke/reshare.feature:6
    Given "Admin" disables share auto accepting
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
      │ Brian │
      │ Carol │
    And "Admin" creates following group using API
      │ id      │
      │ sales   │
      │ finance │
    And "Admin" adds user to the group using API
      │ user  │ group │
      │ Carol │ sales │
    And "Alice" creates the following folder in personal space using API
      │ name             │
      │ folder_to_shared │
    And "Alice" shares the following resource using API
      │ resource         │ recipient │ type │ role   │
      │ folder_to_shared │ Brian     │ user │ editor │
    And "Brian" accepts the following share using API
      │ name             │
      │ folder_to_shared │
    And "Brian" logs in
    And "Brian" opens the "files" app
    And "Brian" navigates to the shared with me page
    And "Brian" reshares the following resource
      │ resource         │ recipient │ type  │ role   │ resourceType │
      │ folder_to_shared │ sales     │ group │ viewer │ folder       │
    And "Carol" logs in
    And "Carol" opens the "files" app
    And "Carol" navigates to the shared with me page
    And "Carol" accepts the following share
      │ name             │
      │ folder_to_shared │
    And "Carol" reshares the following resource
      │ resource         │ recipient │ type │ role   │ resourceType │
      │ folder_to_shared │ Alice     │ user │ viewer │ folder       │
    And "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" navigates to the personal space page
    Then "Alice" should see the following recipients
      │ resource         │ recipient │ type  │ role   │
      │ folder_to_shared │ Brian     │ user  │ editor │
      │ folder_to_shared │ sales     │ group │ viewer │
    ✖ failed
      locator.waitFor: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for locator('xpath=//*[@data-testid="collaborator-user-item-brian"]//button[contains(@class,"files-recipient-role-select-btn")]/span[text()="Editor"]') to be visible
      ============================================================
          at Function.checkCollaborator (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/collaborator.ts:152:46)
          at checkSharee (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/actions.ts:124:9)
          at Share.checkSharee (/var/www/owncloud/web/tests/e2e/support/objects/app-files/share/index.ts:36:9)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/shares.ts:77:9)
    And "Alice" logs out
    - skipped
    When "Brian" updates following sharee role
      │ resource         │ recipient │ type  │ role                    │ resourceType │
      │ folder_to_shared │ sales     │ group │ custom_permissions:read │ folder       │
    - skipped
    And "Brian" logs out
    - skipped
    And "Carol" navigates to the shared with me page
    - skipped
    Then "Carol" should not be able to reshare the following resource
      │ resource         │
      │ folder_to_shared │
    - skipped
    And "Carol" logs out
    - skipped
```

```feature
 ✖ And "Alice" edits the public link named "myPublicLink" of resource "folderPublic" changing role to "uploader" # tests/e2e/cucumber/steps/ui/links.ts:41
       Error: expect(received).toBe(expected) // Object.is equality

       Expected: "secret file drop"
       Received: "uploader"
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/links.ts:45:30)
```

**Comment by SwikritiT** [comment]
This PR merged yesterday so that might be the reason https://github.com/owncloud/web/pull/8876

**Comment by JammingBen** [comment]
Ahhh yes, https://github.com/owncloud/web/pull/8876 is definitely the reason. The PR went through because the e2e tests were disabled by accident, which was fixed after that PR got merged.

**Comment by SagarGi** [comment]
> Ahhh yes, #8876 is definitely the reason. The PR went through because the e2e tests were disabled by accident, which was fixed after that PR got merged.

@JammingBen i will be fixing the failure.

**Comment by SagarGi** [comment]
Fixed by this PR https://github.com/owncloud/web/pull/8934 so closing this issue.
