### ISSUE TITLE
Nightly failing at `e2e-oc10` at `smoke/link.feature:3`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#8997]
### Description
Nighlty is failing in assertion when user changes the role to `editor` but seems to be passing in ocis.

```feature
Scenario: public link (attempt 1, retried) # tests/e2e/cucumber/features/smoke/link.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:36
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:12
       | resource     | type   |
       | folderPublic | folder |
   ✔ And "Alice" uploads the following resources # tests/e2e/cucumber/steps/ui/resources.ts:19
       | resource  | to           |
       | lorem.txt | folderPublic |
   ✔ And "Alice" creates a public link for the resource "folderPublic" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "folderPublic" to "myPublicLink" # tests/e2e/cucumber/steps/ui/links.ts:19
   ✔ And "Alice" edits the public link named "myPublicLink" of resource "folderPublic" changing role to "uploader" # tests/e2e/cucumber/steps/ui/links.ts:41
   ✔ And "Alice" sets the expiration date of the public link named "myPublicLink" of resource "folderPublic" to "+5 days" # tests/e2e/cucumber/steps/ui/links.ts:31
   ✔ And "Alice" sets the password of the public link named "myPublicLink" of resource "folderPublic" to "12345" # tests/e2e/cucumber/steps/ui/links.ts:36
   ✔ When "Anonymous" opens the public link "myPublicLink" # tests/e2e/cucumber/steps/ui/public.ts:10
   ✔ And "Anonymous" unlocks the public link with password "12345" # tests/e2e/cucumber/steps/ui/public.ts:32
   ✔ And "Anonymous" drop uploads following resources # tests/e2e/cucumber/steps/ui/public.ts:37
       | resource     |
       | textfile.txt |
   ✔ When "Alice" downloads the following resources using the batch action # tests/e2e/cucumber/steps/ui/resources.ts:30
       | resource     | from         | type |
       | lorem.txt    | folderPublic | file |
       | textfile.txt | folderPublic | file |
   ✖ And "Alice" edits the public link named "myPublicLink" of resource "folderPublic" changing role to "editor" # tests/e2e/cucumber/steps/ui/links.ts:41
       Error: expect(received).toBe(expected) // Object.is equality

       Expected: "secret file drop"
       Received: "anyone with the link can edit"
           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/links.ts:45:72)
           at runNextTicks (node:internal/process/task_queues:60:5)
           at processImmediate (node:internal/timers:447:9)
```

Build link: https://drone.owncloud.com/owncloud/web/35522/9/16 need some investigation regarding it.

**Comment by SagarGi** [comment]
This issue is hard to reproduce. Cannot be reproduce locally. Looked into trace of failure and seemed to me like the button is not clicked because of the race condition or speed to test. Will see if this occurs again in following days.

**Comment by ScharfViktor** [comment]
no chance of reproduction. How oft is happens? 

web clicks by button
<img width="1273" alt="Screenshot 2023-05-11 at 15 59 48" src="https://github.com/owncloud/web/assets/84779829/f1cc785c-0e83-417b-a26d-22ad3f410f2d">

**Comment by SwikritiT** [comment]
This error has not happened in the recent build so this is not a priority. Let's keep it open and see if it occurs again. we can close it after some time if it doesn't reproduce.

**Comment by SwikritiT** [comment]
This error hasn't occurred in the past two weeks, so I'm closing this.

**Comment by saw-jan** [comment]
Flakiness fixed in PR https://github.com/owncloud/web/pull/9120
