### ISSUE TITLE
[E2E] Investigate flaky test

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9313]
The step `When "Brian" enables the option to search in file content` is being flaky.
Builds:
https://drone.owncloud.com/owncloud/web/36854/12/12
https://drone.owncloud.com/owncloud/web/36848/12/12

```
When "Brian" enables the option to search in file content # tests/e2e/cucumber/steps/ui/search.ts:27
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('xpath=//div[contains(@class,"files-search-filter-full-text")]//button[contains(@class,"oc-filter-chip-button")]')
       ============================================================
           at Object.toggleSearchInFileContent (/var/www/owncloud/web/tests/e2e/support/objects/app-files/search/actions.ts:38:34)
           at Search.toggleSearchInFileContent (/var/www/owncloud/web/tests/e2e/support/objects/app-files/search/index.ts:46:18)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/search.ts:30:24)
```

<details><summary>Full Scenario</summary>

```
Scenario: search for content of file (attempt 2) # tests/e2e/cucumber/features/smoke/fullTextSearch.ocis.feature:6
   ✔ Before # tests/e2e/cucumber/environment/index.ts:39
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
       | Brian |
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:22
       | id    | role        |
       | Brian | Space Admin |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" uploads the following local file into personal space using API # tests/e2e/cucumber/steps/api.ts:125
       | localFile                   | to              |
       | filesForUpload/textfile.txt | fileToShare.txt |
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✔ And "Alice" adds the following tags for the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:359
       | resource        | tags      |
       | fileToShare.txt | alice tag |
   ✔ And "Alice" shares the following resource using API # tests/e2e/cucumber/steps/api.ts:83
       | resource        | recipient | type | role     |
       | fileToShare.txt | Brian     | user | Can edit |
   ✔ And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ And "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Brian" accepts the following share using API # tests/e2e/cucumber/steps/api.ts:96
       | name            |
       | fileToShare.txt |
   ✔ And "Brian" creates the following folder in personal space using API # tests/e2e/cucumber/steps/api.ts:71
       | name       |
       | testFolder |
   ✔ And "Brian" uploads the following local file into personal space using API # tests/e2e/cucumber/steps/api.ts:125
       | localFile                   | to                           |
       | filesForUpload/textfile.txt | textfile.txt                 |
       | filesForUpload/textfile.txt | fileWithTag.txt              |
       | filesForUpload/textfile.txt | withTag.txt                  |
       | filesForUpload/textfile.txt | testFolder/innerTextfile.txt |
   ✔ And "Brian" creates the following project spaces using API # tests/e2e/cucumber/steps/api.ts:137
       | name           | id               |
       | FullTextSearch | fulltextsearch.1 |
   ✔ And "Brian" creates the following folder in space "FullTextSearch" using API # tests/e2e/cucumber/steps/api.ts:169
       | name        |
       | spaceFolder |
   ✔ And "Brian" creates the following file in space "FullTextSearch" using API # tests/e2e/cucumber/steps/api.ts:147
       | name                          | content                   |
       | spaceFolder/spaceTextfile.txt | This is test file. Cheers |
   ✔ And "Brian" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✔ And "Brian" adds the following tags for the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/resources.ts:359
       | resource        | tags  |
       | fileWithTag.txt | tag 1 |
       | withTag.txt     | tag 1 |
   ✔ When "Brian" searches "" using the global search bar # tests/e2e/cucumber/steps/ui/search.ts:6
   ✔ Then "Brian" should see the message "Search for files" on the webUI # tests/e2e/cucumber/steps/ui/search.ts:11
   ✔ When "Brian" selects tag "alice tag" from the search result filter chip # tests/e2e/cucumber/steps/ui/search.ts:17
   ✔ Then following resources should be displayed in the files list for user "Brian" # tests/e2e/cucumber/steps/ui/resources.ts:195
       | resource        |
       | fileToShare.txt |
   ✔ When "Brian" clears tag filter # tests/e2e/cucumber/steps/ui/search.ts:22
   ✔ And "Brian" selects tag "tag 1" from the search result filter chip # tests/e2e/cucumber/steps/ui/search.ts:17
   ✔ Then following resources should be displayed in the files list for user "Brian" # tests/e2e/cucumber/steps/ui/resources.ts:195
       | resource        |
       | fileWithTag.txt |
       | withTag.txt     |
   ✔ When "Brian" searches "file" using the global search bar # tests/e2e/cucumber/steps/ui/search.ts:6
   ✔ Then following resources should be displayed in the files list for user "Brian" # tests/e2e/cucumber/steps/ui/resources.ts:195
       | resource        |
       | fileWithTag.txt |
   ✔ When "Brian" clears tag filter # tests/e2e/cucumber/steps/ui/search.ts:22
   ✔ Then following resources should be displayed in the files list for user "Brian" # tests/e2e/cucumber/steps/ui/resources.ts:195
       | resource                      |
       | textfile.txt                  |
       | fileWithTag.txt               |
       | testFolder/innerTextfile.txt  |
       | fileToShare.txt               |
       | spaceFolder/spaceTextfile.txt |
   ✖ When "Brian" enables the option to search in file content # tests/e2e/cucumber/steps/ui/search.ts:27
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('xpath=//div[contains(@class,"files-search-filter-full-text")]//button[contains(@class,"oc-filter-chip-button")]')
       ============================================================
           at Object.toggleSearchInFileContent (/var/www/owncloud/web/tests/e2e/support/objects/app-files/search/actions.ts:38:34)
           at Search.toggleSearchInFileContent (/var/www/owncloud/web/tests/e2e/support/objects/app-files/search/index.ts:46:18)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/search.ts:30:24)
   - And "Brian" searches "Cheers" using the global search bar # tests/e2e/cucumber/steps/ui/search.ts:6
   - Then following resources should be displayed in the files list for user "Brian" # tests/e2e/cucumber/steps/ui/resources.ts:195
       | resource                      |
       | textfile.txt                  |
       | testFolder/innerTextfile.txt  |
       | fileToShare.txt               |
       | fileWithTag.txt               |
       | withTag.txt                   |
       | spaceFolder/spaceTextfile.txt |
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:89
```
</details>

**Comment by grgprarup** [comment]
The Tika service did not run for that PR. I think just the test code was rebased, later the PR was fully rebased so the Tika code was available and the CI passed. It's not an issue with the step. So closing this.
Before (No tika service):
![image](https://github.com/owncloud/web/assets/8559121/b7ba4b74-9e6b-4150-8b40-33a8b74a30a5)

After (With tika service):
![image](https://github.com/owncloud/web/assets/8559121/99695b26-c65a-4856-b0c5-883864afe1b2)
