### ISSUE TITLE
[E2E] Investigate flaky step 

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9314]
The step `And "Anonymous" closes the editor` is getting flaky.

Builds: 
https://drone.owncloud.com/owncloud/web/36882/12/14
https://drone.owncloud.com/owncloud/web/36848/12/12

```
And "Anonymous" closes the editor # tests/e2e/cucumber/steps/ui/public.ts:29
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#app-top-bar-close')
       ============================================================
           at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/editor.ts:8:53)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/public.ts:31:26)
```

<details><summary>Full Scenario</summary>

```
Scenario: Quick link (attempt 2) # tests/e2e/cucumber/features/smoke/link.feature:48
   ✔ Before # tests/e2e/cucumber/environment/index.ts:39
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" creates the following folders in personal space using API # tests/e2e/cucumber/steps/api.ts:71
       | name         |
       | folderPublic |
   ✔ And "Alice" creates the following files into personal space using API # tests/e2e/cucumber/steps/api.ts:105
       | pathToFile             | content     |
       | folderPublic/lorem.txt | lorem ipsum |
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✔ When "Alice" copies quick link of the resource "folderPublic" from the context menu # tests/e2e/cucumber/steps/ui/shares.ts:115
   ✔ And "Anonymous" opens the public link "Link" # tests/e2e/cucumber/steps/ui/public.ts:7
   ✖ And "Anonymous" closes the editor # tests/e2e/cucumber/steps/ui/public.ts:29
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#app-top-bar-close')
       ============================================================
           at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/editor.ts:8:53)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/public.ts:31:26)
   - And "Anonymous" downloads the following public link resources using the single share view # tests/e2e/cucumber/steps/ui/public.ts:46
       | resource  | type |
       | lorem.txt | file |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:89
```
</details>

**Comment by saw-jan** [comment]
Should be fixed by removing the step. See https://github.com/owncloud/web/pull/9307/files#r1246357491

**Comment by saw-jan** [comment]
Fixed in https://github.com/owncloud/web/pull/9307
