### ISSUE TITLE
Frontend build error windows 10 vite error htmlInlineProxyPlugin

### ISSUE THREAD

**Issue by lunatiqqc** [owncloud/web#9370]
### Steps to reproduce
1. Clone this repo
2. run pnpm install
3. run pnpm build

### Expected behaviour
build succeeding

### Actual behaviour
I get this error:
```
eposecommerceowncloudwebindex.html?html-proxy&index=1.js (imported by index.html): Cannot read properties of undefined (reading '1')
error during build:
eposecommerceowncloudwebindex.html?html-proxy&index=1.js (imported by index.html): Cannot read properties of undefined (reading '1')
    at Object.load (file:///C:/Users/Lunatiqqc/source/repos/ecommerce/owncloudweb/node_modules/.pnpm/vite@4.4.2_@types+node@16.18.30_sass@1.62.1/node_modules/vite/dist/node/chunks/dep-8609dc5d.js:37315:65)
    at file:///C:/Users/Lunatiqqc/source/repos/ecommerce/owncloudweb/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25332:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/Lunatiqqc/source/repos/ecommerce/owncloudweb/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25232:28)
    at async file:///C:/Users/Lunatiqqc/source/repos/ecommerce/owncloudweb/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:24401:75
    at async Queue.work (file:///C:/Users/Lunatiqqc/source/repos/ecommerce/owncloudweb/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25442:32)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

### Environment general
**Operating system**: windows 10

**Node version**: v16.20.0

**Comment by pascalwengerter** [comment]
Thanks for reporting this! Not sure how timely it will get fixed though, since the whole core developer is on Linux/Mac AFAIK. In the meantime, could you look into updating to Node v18 and/or looking into [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)? :)

**Comment by kulmann** [comment]
No response from the issue creator since the original, closing. If still relevant please re-open with additional information. :-)
