### ISSUE TITLE
Flaky e2e test: `upload.feature:40`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9399]
Builds: https://drone.owncloud.com/owncloud/ocis/24250/69/9, https://drone.owncloud.com/owncloud/ocis/24223/69/9
`upload.feature:40`

```feature
Scenario: upload multiple small files (attempt 2) # tests/e2e/cucumber/features/smoke/upload.feature:40
   ✔ Before # tests/e2e/cucumber/environment/index.ts:39
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   ✖ When "Alice" uploads 50 small files in personal space # tests/e2e/cucumber/steps/ui/resources.ts:447
       Error: Timed out 5000ms waiting for expect(received).toHaveText(expected)

       Expected string: "50 items uploaded"
       Received string: ""
       Call log:
         - expect.toHaveText with timeout 5000ms
         - waiting for locator('.upload-info-label.upload-info-success')
         - waiting for locator('.upload-info-label.upload-info-success')

           at Proxy.<anonymous> (/drone/src/webTestRunner/node_modules/.pnpm/@playwright+test@1.29.1/node_modules/@playwright/test/lib/expect.js:130:37)
           at Object.uploadLargeNumberOfResources (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/actions.ts:246:76)
           at runNextTicks (node:internal/process/task_queues:60:5)
           at processImmediate (node:internal/timers:447:9)
           at Resource.uploadLargeNumberOfResources (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/index.ts:50:9)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/resources.ts:458:5)
   - Then "Alice" should see the text "50 items with 600 B in total (50 files, 0 folders)" at the footer of the page # tests/e2e/cucumber/steps/ui/resources.ts:422
   - And "Alice" should see 50 resources in the personal space files view # tests/e2e/cucumber/steps/ui/resources.ts:428
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:89
```

**Comment by PrajwolAmatya** [comment]
In one of the CI https://drone.owncloud.com/owncloud/ocis/24372/89/13 found a trace with following screnshot:
![Screenshot from 2023-07-14 17-09-09](https://github.com/owncloud/web/assets/83579989/70678c76-f953-4a8d-97b5-7a07ad2e0ae2)
Trace: npx playwright show-trace https://cache.owncloud.com/public/owncloud/ocis/24372/tracing/upload-multiple-small-files-alice-2023-7-14-07-55-51.zip

**Comment by saw-jan** [comment]
First Request failed:
```bash
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor-72a9528b.mjs:134[Uppy] [07:55:56] tus: unexpected response while creating upload, originated from request (method: POST, url: https://ocis-server:9200/remote.php/dav/spaces/84928670-6b4c-4902-94d6-f65c5e20c42b$d03a1d8e-f89a-4343-a125-d8833f7ac110, response code: 500, response text: , request id: 798c8496-dc4b-44a4-8dc7-2d4c10c061f5)
vendor-72a9528b.mjs:134[Uppy] [07:55:56] tus: unexpected response while creating upload, originated from request (method: POST, url: https://ocis-server:9200/remote.php/dav/spaces/84928670-6b4c-4902-94d6-f65c5e20c42b$d03a1d8e-f89a-4343-a125-d8833f7ac110, response code: 500, response text: , request id: 798c8496-dc4b-44a4-8dc7-2d4c10c061f5)
```

![Screenshot from 2023-07-14 21-03-17](https://github.com/owncloud/web/assets/52366632/c6507987-968b-46cf-8bcf-4a20308231e4)

**Comment by PrajwolAmatya** [comment]
The mentioned test scenario started being flaky after merging the PR https://github.com/owncloud/ocis/pull/6748. Is this issue related to this PR? @rhafer

**Comment by amrita-shrestha** [comment]
does not occur recently. So closing this issue
