### ISSUE TITLE
e2e test failing in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#9505]
Following test failed in nightly

```feature 
Scenario: User should be able to read and dismiss notifications # tests/e2e/cucumber/features/smoke/notifications.oc10.feature:14
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
      │ Brian │
    And "Admin" sets the default folder for received shares to "Shares"
    And "Admin" disables share auto accepting
    Given "Alice" creates the following folder in personal space using API
      │ name             │
      │ folder_to_shared │
    And "Alice" logs in
    And "Alice" opens the "files" app
    And "Alice" shares the following resource using the sidebar panel
      │ resource         │ recipient │ type │ role     │ resourceType │
      │ folder_to_shared │ Brian     │ user │ Can edit │ folder       │
    When "Brian" logs in
    Then "Brian" should see the following notifications
      │ message                                               │
      │ "Alice Hansen" invited you to view "folder_to_shared" │
    ✖ failed
      Error: expect(received).toContain(expected) // indexOf

      Expected value: "\"Alice Hansen\" invited you to view \"folder_to_shared\""
      Received array: []
          at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.33.0/node_modules/@playwright/test/lib/matchers/expect.js:135:37)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/notifications.ts:11:38)
    And "Brian" marks all notifications as read
    - skipped
    Then "Brian" should see no notifications
    - skipped
    And "Alice" logs out
    - skipped
    And "Brian" logs out
    - skipped
```

Build link: https://drone.owncloud.com/owncloud/web/37790/9/16

**Comment by SwikritiT** [comment]
this failure is not that flaky and web team is dropping support for oc10 soon (see https://github.com/owncloud/web/pull/9530), let's not invest much time trying to fix this.

Closing this here
