### ISSUE TITLE
[E2E] Nightly failed on `smoke/spaces/internalLink.feature:3` with master

### ISSUE THREAD

**Issue by grgprarup** [owncloud/web#9614]
Build: https://drone.owncloud.com/owncloud/web/38345/10/12
```console
Scenario: share a link with internal role (attempt 2) # tests/e2e/cucumber/features/smoke/spaces/internalLink.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:30
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:9
       | id    |
       | Alice |
       | Brian |
       | Carol |
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:16
       | id    | role        |
       | Alice | Space Admin |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Alice" creates the following project space using API # tests/e2e/cucumber/steps/api.ts:105
       | name      | id          |
       | Marketing | marketing.1 |
   ✔ And "Alice" creates the following folder in space "Marketing" using API # tests/e2e/cucumber/steps/api.ts:137
       | name     |
       | myfolder |
   ✔ And "Alice" creates the following file in space "Marketing" using API # tests/e2e/cucumber/steps/api.ts:115
       | name              | content     |
       | myfolder/plan.txt | secret plan |
   ✔ And "Alice" adds the following members to the space "Marketing" using API # tests/e2e/cucumber/steps/api.ts:157
       | user  | role     | shareType |
       | Brian | Can edit | space     |
       | Carol | Can view | space     |
   ✔ And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   ✔ And "Alice" navigates to the project space "marketing.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   ✔ And "Alice" creates a public link for the space using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:14
   ✔ And "Alice" renames the most recently created public link of space to "spaceLink" # tests/e2e/cucumber/steps/ui/links.ts:25
   ✔ And "Alice" edits the public link named "spaceLink" of the space changing role to "Invited people" # tests/e2e/cucumber/steps/ui/links.ts:72
   ✖ And "Alice" creates a public link for the resource "myfolder" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
       Error: Timed out 5000ms waiting for expect(received).not.toBeVisible()
       Call log:
         - locator._expect with timeout 5000ms
         - waiting for locator('xpath=//div[contains(@class,"oc-notification-message-title")]')
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"
         -   locator resolved to <div class="oc-notification-message-title">Link was created successfully</div>
         -   unexpected value "visible"

           at Proxy.<anonymous> (/var/www/owncloud/web/node_modules/.pnpm/@playwright+test@1.33.0/node_modules/@playwright/test/lib/matchers/expect.js:135:37)
           at clearPopups (/var/www/owncloud/web/tests/e2e/support/objects/app-files/link/actions.ts:180:66)
           at runNextTicks (node:internal/process/task_queues:60:5)
           at processImmediate (node:internal/timers:447:9)
           at Object.createLink (/var/www/owncloud/web/tests/e2e/support/objects/app-files/link/actions.ts:45:5)
           at Link.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/link/index.ts:45:21)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/links.ts:9:5)
   - When "Alice" edits the public link named "Link" of resource "myfolder" changing role to "Invited people" # tests/e2e/cucumber/steps/ui/links.ts:41
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - And "Brian" opens the public link "Link" # tests/e2e/cucumber/steps/ui/public.ts:8
   - And "Brian" logs in from the internal link # tests/e2e/cucumber/steps/ui/session.ts:44
   - And "Brian" uploads the following resource in internal link named "Link" # tests/e2e/cucumber/steps/ui/public.ts:79
       | resource   |
       | simple.pdf |
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Carol" opens the public link "spaceLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   - And "Carol" logs in from the internal link # tests/e2e/cucumber/steps/ui/session.ts:44
   - And "Carol" opens folder "myfolder" # tests/e2e/cucumber/steps/ui/resources.ts:200
   - Then "Carol" should see file "simple.pdf" but should not be able to edit # tests/e2e/cucumber/steps/ui/spaces.ts:85
   - And "Carol" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:80
```

**Comment by SagarGi** [comment]
@nabim777  This was also failed when i was working with collabora PR. Would be good to look into it.
