### ISSUE TITLE
Nightly web failing on office suites tests in `master`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/web#9674]
### Description
NIghtly test failing:
```feature
Scenario: create an OpenDocument file with Collabora # tests/e2e/cucumber/features/smoke/app-provider/officeSuites.feature:15
    Given "Admin" creates following users using API
      │ id    │
      │ Alice │
(node:21) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
    And "Alice" logs in
    And "Alice" opens the "files" app
    When "Alice" creates the following resources
      │ resource         │ type         │ content              │
      │ OpenDocument.odt │ OpenDocument │ OpenDocument Content │
    ✖ failed
      page.waitForEvent: Timeout 30000ms exceeded while waiting for event "popup"
      =========================== logs ===========================
      waiting for event "popup"
      ============================================================
          at createDocumentFile (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:217:14)
          at createNewFileOrFolder (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:194:13)
          at Object.createResources (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/actions.ts:304:5)
          at Resource.create (/var/www/owncloud/web/tests/e2e/support/objects/app-files/resource/index.ts:35:9)
          at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/resources.ts:40:9)
    And "Alice" creates a public link for the resource "OpenDocument.odt" using the sidebar panel
    - skipped
    And "Alice" edits the public link named "Link" of resource "OpenDocument.odt" changing role to "Can edit"
    - skipped
    And "Alice" logs out
    - skipped
    And "Anonymous" opens the public link "Link"
    - skipped
    Then "Anonymous" should see the content "OpenDocument Content" in editor "Collabora"
    - skipped
```
Build link: https://drone.owncloud.com/owncloud/web/38597/11/18
Need some investigation regarding it.

**Comment by SagarGi** [comment]
Seems like this is a hard failure can be reproduce locally. Will be digging into it.

**Comment by SagarGi** [comment]
Can be closed since https://github.com/owncloud/web/pull/9677 this PR is merged.
