### ISSUE TITLE
[QA] Nightwatch tests failing in nightly 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#9945]
## Description
Nightwatch tests are failing in ocis CI

## Test failure
```console
webUISharingAutocompletion/shareAutocompletionSpecialChars.feature:75
webUISharingAutocompletion/shareAutocompletionSpecialChars.feature:77
```
```console
Scenario: autocompletion of groups having special characters in their names (attempt 1, retried) # features/webUISharingAutocompletion/shareAutocompletionSpecialChars.feature:77
   ✔ Before # setup.js:38
   ✔ Before # setup.js:42
   ✔ Before # setup.js:53
   ✔ Before # setup.js:60
   ✔ Before # setup.js:71
   ✔ Before # stepDefinitions/filesContext.js:17
   ✔ Before # stepDefinitions/generalContext.js:149
   ✔ Before # stepDefinitions/generalContext.js:187
   ✔ Before # stepDefinitions/middlewareContext.js:46
   ✔ Given the administrator has set the default folder for received shares to "Shares" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And these users have been created with default attributes and without skeleton files in the server but not initialized: # stepDefinitions/middlewareContext.js:76
       | username    |
       | regularuser |
   ✔ And these users have been created without initialization and without skeleton files in the server: # stepDefinitions/middlewareContext.js:76
       | username | password  | displayname  | email        |
       | two      | %regular% | Brian Murphy | u2@oc.com.np |
       | u444     | %regular% | Four         | u3@oc.com.np |
   ✔ And these groups have been created in the server: # stepDefinitions/middlewareContext.js:76
       | groupname |
       | finance1  |
       | finance2  |
   ✔ And the setting "outgoing_server2server_share_enabled" of app "files_sharing" has been set to "no" in the server # stepDefinitions/middlewareContext.js:66
   ✔ Given these groups have been created in the server: # stepDefinitions/middlewareContext.js:76
       | groupname |
       | -_.ocgrp  |
   ✔ And user "regularuser" has created file "data.zip" in the server # stepDefinitions/middlewareContext.js:66
   ✔ And user "regularuser" has logged in using the webUI # stepDefinitions/loginContext.js:68
   ✔ And the user has browsed to the personal page # stepDefinitions/filesContext.js:103
   ✔ And the user has opened the share dialog for file "data.zip" # stepDefinitions/filesContext.js:159
   ✔ When the user types "-_" in the share-with-field # stepDefinitions/sharingContext.js:263
   ✖ Then only users and groups that contain the string "-_" in their name or displayname should be listed in the autocomplete list on the webUI # stepDefinitions/sharingContext.js:478
       AssertionError [ERR_ASSERTION]: "-_.ocgrp" was listed in autocomplete list, but should not have been. (check if that is a manually added user/group)
           + expected - actual

           -false
           +true

           at forEach (/drone/src/webTestRunner/tests/acceptance/stepDefinitions/sharingContext.js:506:18)
           at Array.forEach (<anonymous>)
           at /drone/src/webTestRunner/tests/acceptance/stepDefinitions/sharingContext.js:488:19
           at processTicksAndRejections (node:internal/process/task_queues:95:5)
   ✔ After # stepDefinitions/middlewareContext.js:60
   ✔ After # stepDefinitions/generalContext.js:205
   ✔ After # stepDefinitions/generalContext.js:174
   ✔ After # stepDefinitions/generalContext.js:115
   ✔ After # setup.js:104
   ✔ After # setup.js:100
   ✔ After # setup.js:96
   ✔ After # setup.js:89
   ✔ After # setup.js:80

```

Build link: https://drone.owncloud.com/owncloud/ocis/28804/43/13

**Comment by SwikritiT** [comment]
bumping ocis commit id here https://github.com/owncloud/web/pull/9946 to see if the tests fail in web repo as well

**Comment by saw-jan** [comment]
Fix merged https://github.com/owncloud/web/pull/9934
