### ISSUE TITLE
[QA] Flaky public-link e2e test

### ISSUE THREAD

**Issue by saw-jan** [owncloud/web#9977]
Builds: https://drone.owncloud.com/owncloud/web/40327/11/16
Tracings:
```
npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/40327/tracing/copy-and-move-resources-in-personal-space-alice-2023-11-17-08-28-06.zip

npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/40327/tracing/public-link-for-folder-and-file-by-authenticated-user-alice-2023-11-17-08-33-35.zip

npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/40327/tracing/public-link-for-folder-and-file-by-authenticated-user-brian-2023-11-17-08-34-25.zip
```
```feature
Scenario: public link for folder and file (by authenticated user) (attempt 2) # tests/e2e/cucumber/features/smoke/link.feature:68
   ✔ Before # tests/e2e/cucumber/environment/index.ts:43
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Alice |
   ✔ Given "Admin" creates following user using API # tests/e2e/cucumber/steps/api.ts:6
       | id    |
       | Brian |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:13
       | resource     | type   |
       | folderPublic | folder |
   ✔ And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:13
       | resource                      | type    | content   |
       | folderPublic/shareToBrian.txt | txtFile | some text |
       | folderPublic/shareToBrian.md  | mdFile  | readme    |
   ✔ And "Alice" uploads the following resources via drag-n-drop # tests/e2e/cucumber/steps/ui/resources.ts:621
       | resource       |
       | simple.pdf     |
       | testavatar.jpg |
   ✔ And "Alice" shares the following resources using the sidebar panel # tests/e2e/cucumber/steps/ui/shares.ts:29
       | resource       | recipient | type | role     |
       | folderPublic   | Brian     | user | Can edit |
       | simple.pdf     | Brian     | user | Can edit |
       | testavatar.jpg | Brian     | user | Can edit |
   ✔ And "Alice" creates a public link for the resource "folderPublic" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "folderPublic" to "folderLink" # tests/e2e/cucumber/steps/ui/links.ts:27
   ✔ And "Alice" creates a public link for the resource "folderPublic/shareToBrian.txt" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "folderPublic/shareToBrian.txt" to "textLink" # tests/e2e/cucumber/steps/ui/links.ts:27
   ✔ And "Alice" creates a public link for the resource "folderPublic/shareToBrian.md" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "folderPublic/shareToBrian.md" to "markdownLink" # tests/e2e/cucumber/steps/ui/links.ts:27
   ✔ And "Alice" creates a public link for the resource "simple.pdf" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "simple.pdf" to "pdfLink" # tests/e2e/cucumber/steps/ui/links.ts:27
   ✔ And "Alice" creates a public link for the resource "testavatar.jpg" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   ✔ And "Alice" renames the most recently created public link of resource "testavatar.jpg" to "imageLink" # tests/e2e/cucumber/steps/ui/links.ts:27
   ✔ And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:43
   ✔ And "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:30
   ✔ When "Brian" opens the public link "folderLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   ✔ And "Brian" uploads the following resources # tests/e2e/cucumber/steps/ui/resources.ts:25
       | resource  |
       | lorem.txt |
   ✔ When "Brian" opens the public link "textLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   ✔ And "Brian" closes the file viewer # tests/e2e/cucumber/steps/ui/public.ts:41
   ✔ When "Brian" opens the public link "markdownLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   ✔ And "Brian" closes the file viewer # tests/e2e/cucumber/steps/ui/public.ts:41
   ✔ When "Brian" opens the public link "pdfLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   ✔ And "Brian" closes the file viewer # tests/e2e/cucumber/steps/ui/public.ts:41
   ✔ When "Brian" opens the public link "imageLink" # tests/e2e/cucumber/steps/ui/public.ts:8
   ✖ And "Brian" closes the file viewer # tests/e2e/cucumber/steps/ui/public.ts:41
       locator.click: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#app-top-bar-close')
       ============================================================
           at Object.close (/var/www/owncloud/web/tests/e2e/support/objects/app-files/utils/editor.ts:9:49)
           at World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/ui/public.ts:45:18)
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:43
   ✔ After # tests/e2e/cucumber/environment/index.ts:109
```

**Comment by grgprarup** [comment]
The failure is tracked in the issue https://github.com/owncloud/web/issues/9941. Let's wait for the PR https://github.com/owncloud/web/pull/9948 to get merged. This can be close.
